### ISSUE TITLE
[Create a bootable USB stick on macOS] Problem

### ISSUE THREAD

**Issue by CoolWhipTwentyThree** [canonical-web-and-design/tutorials.ubuntu.com#1003]
The issue is that macOS is not seeing by bootable USB even after going clicking option/alt key before booting macOS. It comes up with Macintosh HD and EFI Boot, however, that takes me to the recovery mode of the MacBook. Now, my USB seems to be corrupted as well.

How can I solve this?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
