### ISSUE TITLE
[Install Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by wildmanjohn69** [canonical-web-and-design/tutorials.ubuntu.com#1004]
<describe the issue>I'm looking for the installation walkthrough for dual booting with win10, partitioned in windows and now I don't know how to assign the partitions during the install, I have root set to ext4 but I don't know if home is ext3 and what is ext2

**Comment by evilnick** [comment]
Hi,
We don't have a tutorial here on dual booting with windows.
However, I can tell you that ext3/ext4 aren't labels for the partitions, they are the _filesystem_ linux uses. There should be an ext4 partition for the root, ext4 for /home (though you don't need a separate partition for that) and usually a swap partition.
There is a tutorial [here](https://itsfoss.com/install-ubuntu-1404-dual-boot-mode-windows-8-81-uefi/) you may find helpful
