### ISSUE TITLE
update default id_rsa location in docs for 'Generate SSH Keys on Windows 10'

### ISSUE THREAD

**Issue by mike715** [canonical-web-and-design/tutorials.ubuntu.com#1007]
Currently, on page 2 of the 'Generate SSH Keys on Windows 10' docs found here:

[https://tutorials.ubuntu.com/tutorial/tutorial-ssh-keygen-on-windows#2]

the default location of the `~/.ssh` folder in the ubuntu file system is mapped to the following location within Windows 10:

`C:\Users\<Windows username>\AppData\Local\lxss\home\<Ubuntu username>\.ssh`

However, the new location is actually:

`C:\Users\%USERNAME%\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\`

as referenced in the following Nov 9, 2017 post on stackoverflow:

[https://stackoverflow.com/questions/39886862/the-lxss-folder-in-windows-for-bash-on-ubuntu-on-windows-is-missing]

**Comment by evilnick** [comment]
Thanks for spotting this, should be fixed shortly
