### ISSUE TITLE
[Install Ubuntu Server tutorial] Ubuntu cannot be installed without internet connection

### ISSUE THREAD

**Issue by alvindizon** [canonical-web-and-design/tutorials.ubuntu.com#1014]
The [networking](https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-server#6) part of the Install Ubuntu Server tutorial  is not true if you're using the live ISO to install Ubuntu Server 18.04. Use the traditional installer and not the live ISO one instead according to [this](https://askubuntu.com/questions/1042364/install-18-04-server-without-network-connection).

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
