### ISSUE TITLE
Ubuntu Checksum Tutorial fails in WSL 18.04LTS

### ISSUE THREAD

**Issue by k7aay** [canonical-web-and-design/tutorials.ubuntu.com#1015]
The [Ubuntu checksum tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#3)   fails in WSL 18.04 LTS when I try to download the public key with 

`gpg --keyid-format long --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x46181433FBB75451 0xD94AA3F0EFE21092`

with 

> gpg: connecting dirmngr at '/home/tester/.gnupg/S.dirmngr' failed: IPC connect call failed  
> gpg: keyserver receive failed: No dirmngr

**Comment by evilnick** [comment]
This is I believe a bug in WSL

The recommended workaround is to use apt-key, e.g.

curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x46181433FBB75451 | sudo apt-key add
