### ISSUE TITLE
[Basic snap usage] 'snap find' fails to find canonical snap

### ISSUE THREAD

**Issue by donnlee** [canonical-web-and-design/tutorials.ubuntu.com#1018]
Followed the Snap tutorial, 'hello' and 'hello-world' by 'canonical' is not in the output.

```
donn@pailu:~$ sudo snap find hello | grep canon
donn@pailu:~$ 
```

I see others:

donn@pailu:~$ sudo snap find hello | grep cy
hello-tempgauge-cytoza  2.10     cytoza             -      GNU Hello Temp Gauge, a temperature gauge hello world snap

donn@pailu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
