### ISSUE TITLE
[Create a bootable USB stick on Windows] trial version only?

### ISSUE THREAD

**Issue by xucaen** [canonical-web-and-design/tutorials.ubuntu.com#1019]
I followed the instructions at https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#0
but after it finished and I tried to boot to Ubuntu I saw the temporary trial version grub menu. I wanted my USB to contain the full official version, not a trial version. How do I get rid of that grub menu and install the full version ON USB drive? In other words I do not want to install ubuntu onto my hard drive, just on the USB drive. Thanks!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
