### ISSUE TITLE
iso file not partioned

### ISSUE THREAD

**Issue by Orocalian** [canonical-web-and-design/tutorials.ubuntu.com#1023]
Cannot create the bootable USB with the downloaded ISO file. <img width="495" alt="Screen Shot 2019-08-07 at 12 20 20 PM" src="https://user-images.githubusercontent.com/46055835/62639559-c60d8900-b90d-11e9-96d2-5cfafc61388d.png">

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
