### ISSUE TITLE
18.04.3 LTS Image exceeds 2 GB at "Create a bootable USB stick (on Ubuntu etc.) - 2. Requirements"

### ISSUE THREAD

**Issue by T-E-N** [canonical-web-and-design/tutorials.ubuntu.com#1024]
"You will need: A 2GB or larger USB stick/flash drive"
...is no longer sufficient in size for today's most-recommended ubuntu-18.04.3-desktop-amd64.iso image weighing in at 2.1 GB (2082816000 bytes).

Likely to apply to versions of these instructions in other places / for further operating systems as well.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
