### ISSUE TITLE
[Basic snap usage] <please add a title>

### ISSUE THREAD

**Issue by ramtintk** [canonical-web-and-design/tutorials.ubuntu.com#1026]
<describe the issue>It could be much better if this tutorial started with an introduction to package managers and repositories or at least what is snappy | snap | snapd for beginners.
But totally it was okay and well written

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
