### ISSUE TITLE
No Selection

### ISSUE THREAD

**Issue by NunYahBiz** [canonical-web-and-design/tutorials.ubuntu.com#1030]
So I go to selection in Rufus to create a Ubuntu boot thumb drive and there is no way to add the file I downloaded to a different folder than the one that microcrap thinks is the only place one should be downloading files to, the download folder.
Houston, we have a problem . . .

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
