### ISSUE TITLE
tutorial/install-and-configure-wordpress#4 mistake localhost/blog

### ISSUE THREAD

**Issue by kaczalapa** [canonical-web-and-design/tutorials.ubuntu.com#1033]
Hi!
I try to configurate wordpress on ubuntu.
I am using this tutorial: https://tutorials.ubuntu.com/tutorial/install-and-configure-wordpress#4

On step 5 I should have possibility to configure WordPress. Unfortunetly I have ERR_CONNECTION_REFUSED while I try to get http://localhost/blog

EDIT1: I just discovered that I tried to connect from the another VM. How can I reconfigure file to available connection from another VM in the some network?

Can you try to help me find the solution have to get the site like on tutorial?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
