### ISSUE TITLE
It's incredibly easy to miss the link to create the installation media

### ISSUE THREAD

**Issue by allanonmage** [canonical-web-and-design/tutorials.ubuntu.com#1034]
I'm not new to installing Ubuntu, but I clicked on the tutorial because I hadn't done it in a while and wanted to see what software was recommended to create a USB installation disc.  As I was skimming the steps, I got about halfway through and was surprised there wasn't the usual 10 - 15 pages about how to burn an ISO to a DVD or make a bootable USB drive.

The 3rd time I re-read the directions I noticed a small footnote which appeared to link to such a tutorial.

Given that these tutorials are meant for people unfamiliar with the process, such a thing should not be the last sentence of several footnotes on a step.  It needs to be more attention grabbing.

As far as a solution, maybe a step all to itself like **"Create installation media"** with a brief overview and direct links on how to create each type of media.  Doesn't have to be fancy or complicated, but if I need to give my mom a link on how to install Ubuntu, it should walk her through it, not generate a tech support call for me.  Right now, eve if you spot the footnote, you get dumped out to the main tutorials page, which is the opposite of helpful to a newbie.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
