### ISSUE TITLE
[Run Linux Containers on Windows] Error in running the script

### ISSUE THREAD

**Issue by eduwht** [canonical-web-and-design/tutorials.ubuntu.com#1035]
![image](https://user-images.githubusercontent.com/16917316/63634847-5eb93e00-c65c-11e9-8780-f181d66c495d.png)
Error calling SetAccessRule, some identity references can not be converted.

Someone is having the same problem? Any ideas?
Thanks.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
