### ISSUE TITLE
instructions for making a ubuntu dvd doesn't work

### ISSUE THREAD

**Issue by tin1a23** [canonical-web-and-design/tutorials.ubuntu.com#1038]
Hi, I followed the instructions and used brasero to burn a new dvd with ubuntu 18.04, and after cliking on burn, brasero indicated there was an error, and I couldn't install it.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
