### ISSUE TITLE
[Upgrade Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by irfannn2** [canonical-web-and-design/tutorials.ubuntu.com#1045]
when I upgrade my Ubuntu than 19.4 so much lake 
my laptop 
gamer laptop dell 5577
lntel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 
lntel® HD Graphics 630 (Kaby Lake GT2)
ram 8gb

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
