### ISSUE TITLE
How to make a LFS about Ubuntu

### ISSUE THREAD

**Issue by EricLzu** [canonical-web-and-design/tutorials.ubuntu.com#1046]
Now, I want to build a Ubuntu System by myself, but i don't know how to do it.  Is it a same process   with LFS? Hope to get your help, thank you.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
