### ISSUE TITLE
[Create a bootable USB stick on Ubuntu] Installation failed

### ISSUE THREAD

**Issue by Mbodin** [canonical-web-and-design/tutorials.ubuntu.com#1047]
After clicking on “make Startup Disk”, the program “Make Startup Disk” warned me that any existing data will be lost. I clicked Yes. Then I just got a message “Installation failed” with only one option: “Quit”.
I believe that such tutorial for non-technical users should only be done on stable programs that work and provide useful error messages when failing. This is clearly not the case of the program “Make Startup Disk”.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
