### ISSUE TITLE
Insufficient permissions to access MicroK8s

### ISSUE THREAD

**Issue by sanjaygeeky** [canonical-web-and-design/tutorials.ubuntu.com#1053]
sanju@buntu:~$ microk8s.enable
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user sanju to the 'microk8s' group:

    sudo usermod -a -G microk8s sanju
The user is already added to group microk8s as seen below
sanju@buntu:~$ getent group microk8s 
microk8s:x:998:sanju

Can you please guide me if anything is incorrect?

Thanks 
Sanjay

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
