### ISSUE TITLE
[Install and Configure Apache] <please add a title>

### ISSUE THREAD

**Issue by dwarkab** [canonical-web-and-design/tutorials.ubuntu.com#1055]
Hello i follow steps as per given but my webpage is open with example.com. i also want to know that in which file i want to configure different domains in a single file. means i have 2 domains but port number is different in which file this setting is available. If u have full guide about apache please give

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
