### ISSUE TITLE
The Site Cannot be reach

### ISSUE THREAD

**Issue by dwarkab** [canonical-web-and-design/tutorials.ubuntu.com#1056]
Hello,
I configure as per your steps https://tutorials.ubuntu.com/tutorial/install-and-configure-apache#4 
but showing error.

![Screenshot from 2019-09-24 16-50-28](https://user-images.githubusercontent.com/53464253/65507382-71d55d00-deeb-11e9-916f-6f68be45c0ff.png)

**Comment by evilnick** [comment]
hmm. It may help to include the contents of `/var/log/apache2/error.log`

**Comment by dwarkab** [comment]
[Wed Sep 25 09:52:54.516541 2019] [mpm_prefork:notice] [pid 1190] AH00163: Apache/2.4.38 (Ubuntu) configured -- resuming normal operations
[Wed Sep 25 09:52:54.516624 2019] [core:notice] [pid 1190] AH00094: Command line: '/usr/sbin/apache2'
[Wed Sep 25 10:42:52.218587 2019] [mpm_prefork:notice] [pid 1190] AH00169: caught SIGTERM, shutting down

**Comment by evilnick** [comment]
Hmm. that seems as expected. 

Do you have a DNS entry for the site?
https://httpd.apache.org/docs/2.4/vhosts/examples.html

I think this should be called out in the tutorial actually, but the setup only covers the server config - if the address doesn't actually resolve to your local machine, it won't be found.

You need to add an entry to /etc/hosts to resolve the site on the local machine for testing:

```
127.0.0.1       simpleenrgytech.com
```

**Comment by dwarkab** [comment]
Do you have a DNS entry for the site?
Yes I can.
Now i Installed Odoo with my domain name it will work on Local, but need to enter port number like this
www.simpleenergytech.com:8069, now my requirement is do not need to enter port number with domain. I made changes in apache2.conf but not work. Also i refer a video for this installation in which without odoo config file Odoo is running on browser.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
