### ISSUE TITLE
Configuring Samba

### ISSUE THREAD

**Issue by timpa82** [canonical-web-and-design/tutorials.ubuntu.com#1059]
I followed the guide which is easy to follow and ended up viewing the directory I wanted, but am unable to save/create/update the files in the directory.

Using Windows 10 and file explorer.
I added the following to the smb.conf file:
[hass]
  comment = hass
  path = /srv/docker/hass-config
  read only = no
  browsable = yes

**Comment by timpa82** [comment]
I added writable = yes

And tried the "sudo service smdb restart" but got message: "Failed to restart smdb.service: Unit smdb.service not found."

**Comment by ysl682** [comment]
There is a typo in the description. The last line should be:
browseable = yes
I suppose that's the reason for the problem.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
