### ISSUE TITLE
Terminal halt

### ISSUE THREAD

**Issue by AstutTiwari** [canonical-web-and-design/tutorials.ubuntu.com#1060]
issue:-
wl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-32-generic/updates/dkms/

depmod....

DKMS: install completed.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
