### ISSUE TITLE
[Install and Configure Apache] Couldn't open example site

### ISSUE THREAD

**Issue by Delta-43** [canonical-web-and-design/tutorials.ubuntu.com#1062]
I followed all the steps upto enabling the site and restarting the apache service, but I couldn't open the example page we created following the tutorial. I'm completely new to this so I have no idea how to troubleshoot

This is the error I get when I try to access the page:

The following error was encountered while trying to retrieve the URL: http://gci.example.com/

    Unable to determine IP address from host name "gci.example.com"

The DNS server returned:

    Name Error: The domain name does not exist.

This means that the cache was not able to resolve the hostname presented in the URL. Check if the address is correct.

Your cache administrator is root.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
