### ISSUE TITLE
Link on this Page is 404 - so dead end trying to get Linux Container

### ISSUE THREAD

**Issue by markind69** [canonical-web-and-design/tutorials.ubuntu.com#1064]
On this page:

https://tutorials.ubuntu.com/tutorial/tutorial-windows-ubuntu-hyperv-containers#3

The link provided is bad:

https://partner-images.canonical.com/hyper-v/linux-containers/xenial/current/?_ga=2.1225524.427104480.1570588161-1984919681.1570588161

So of course, me, a beginner, is totally stuck...

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
