### ISSUE TITLE
Is it possible to use snap names themselves as snap ids

### ISSUE THREAD

**Issue by MansionsDave** [canonical-web-and-design/tutorials.ubuntu.com#1065]
In the Terminal , Snaps use a numerical and indefinite ID system where every Snap "Transaction" is logged , I am not under the assumption that this is necessary .

If this system * is * to take place , there should at least be a very simple option to clear logs like "sudo snap clear-logs" listed in the "snap help" menu .

It's a little unnerving to find out that hundreds of Snap Transactions have taken place in just a few months even though I only use a handful of Snaps .

You can use the snap names themselves to install and remove snaps "sudo snap install shotcut" , "sudo snap remove shotcut" .

The entire process of using Snaps from the Terminal should just involve the names .

Let's say I'm trying to install the Shotcut Snap but the connection keeps bugging out , I should be able to go to "snap tasks" , not "snap changes" to see all the ongoing Transactions .

If Shotcut is being installed it should show up as "shotcut-install" , there is no requirement for keeping record of Transactions that have concluded in one way or another .

I should then be able to abort the faulty connection with "sudo snap abort shotcut-install" .

As for GUI , the Snap Version of the Snap Store still bugs out when you install something and then leave that page , there should also be the option to monitor all ongoing transactions without using a numerical and indefinite id system within the Snap Store App .

**Comment by MansionsDave** [comment]
In the Terminal , Snaps use a numerical and indefinite ID system where every Snap "Transaction" is logged , I am not under the assumption that this is necessary .

If this system is to take place , there should at least be a very simple option to clear logs like "sudo snap clear-logs" listed in the "snap help" menu .

It's a little unnerving to find out that hundreds of Snap Transactions have taken place in just a few months even though I only use a handful of Snaps .

You can use the snap names themselves to install and remove snaps "sudo snap install shotcut" , "sudo snap remove shotcut" .

The entire process of using Snaps from the Terminal should just involve the names .

Let's say I'm trying to install the Shotcut Snap but the connection keeps bugging out , I should be able to go to "snap tasks" , not "snap changes" to see all the ongoing Transactions .

If Shotcut is being installed it should show up as "shotcut-install" , there is no requirement for a numerical and indefinite id system , or even an id system from what I can tell .

As for GUI , the Snap Version of the Snap Store still bugs out when you install something and then leave that page , there should also be the option to monitor all ongoing transactions without using a numerical and indefinite id system within the Snap Store App .

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
