### ISSUE TITLE
[Install a local Kubernetes with MicroK8s] Incorrect UFW rule targest wrong interface name

### ISSUE THREAD

**Issue by chrisber** [canonical-web-and-design/tutorials.ubuntu.com#1066]
The example shows an incrrect network interface in the UFW rule.

```sh
sudo ufw allow in on cbr0 && sudo ufw allow out on cbr0
```    
should be replace with
```sh
sudo ufw allow in on cni0 && sudo ufw allow out on cni0
```
Pull-Request: https://github.com/canonical-web-and-design/tutorials.ubuntu.com/pull/1067
Refs: https://github.com/ubuntu/microk8s/issues/513#issuecomment-537067493

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
