### ISSUE TITLE
Tutorial Wanted How to resize an encrypted partition

### ISSUE THREAD

**Issue by hk1ll3r** [canonical-web-and-design/tutorials.ubuntu.com#1073]
I'm trying to resize a partition to install windows side by side with my Ubuntu. Disks utility on Ubuntu sees the encrypted partition but does not allow resizing it.

As far as I can tell you'd need to boot into a live CD / USB and resize the partitions there.
https://help.ubuntu.com/community/ResizeEncryptedPartitions

Would be nice if there was a more authoritative source on how to do it.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
