### ISSUE TITLE
[Install and Configure Samba] <please add a title>

### ISSUE THREAD

**Issue by dmacqueen** [canonical-web-and-design/tutorials.ubuntu.com#1074]
Connecting to the sambashare directory from macOS 10.14 (Mojave) is simpler if you just click on the Network icon in the left column of a Finder window.  The samba server appears there and your can sign in and then access the sambashare.  This avoids having to use the ip-address of the Samba server.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
