### ISSUE TITLE
[Install Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by BashZia** [canonical-web-and-design/tutorials.ubuntu.com#1075]
<describe the issue> I have installed the Ubuntu using bootable USB drive. But Ubuntu is not starting. It looks like it is loading but it is not going forward from the loading window.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
