### ISSUE TITLE
Microstack Tutorial ??

### ISSUE THREAD

**Issue by autonux** [canonical-web-and-design/tutorials.ubuntu.com#1076]
linked to `https://tutorials.ubuntu.com/tutorial/microstack-get-started?&_ga=2.101599938.2100640651.1572046269-1672971077.1572046269#0`
from `https://microstack.run/`
**404: Page not found**
**Coming Soon** would be a better message perhaps?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
