### ISSUE TITLE
[How to Install ONLYOFFICE on Ubuntu 18.04] <please add a title>

### ISSUE THREAD

**Issue by ampermsn** [canonical-web-and-design/tutorials.ubuntu.com#1077]
<describe the issue>I installed the onlyoffice community server and received docker errors: "could not find docker. I know that docker was installed as I chose the docker server on the Ubuntu 18.04 LTS installation. I also got : "Docker image onlyoffice/documentserver: 5.4.1.39 not found. My docker installation also gave me a location of: DockerO: 172.17.0.1? What did I do wrong?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
