### ISSUE TITLE
[install and configure apache] Missing some steps

### ISSUE THREAD

**Issue by zaphodikus** [canonical-web-and-design/tutorials.ubuntu.com#1080]
https://tutorials.ubuntu.com/tutorial/install-and-configure-apache
==================
the steps on page 2 read
cd /var/www/gci/
nano index.html
that last command must be elevated/sudo to work

===================
After Apache install, the server is not actually activated:
sudo systemctl status apache2
sudo ufw enable
sudo ufw default deny
sudo ufw allow 'Apache'

got me a bit farthur.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
