### ISSUE TITLE
[Install and Configure Apache] 'This site can’t be reached' in Google Chrome

### ISSUE THREAD

**Issue by tomelam** [canonical-web-and-design/tutorials.ubuntu.com#1086]
Trying to copy the procedure in the tutorial exactly (except changing gci to dev wherever gci appeared), I get This site can’t be reached' in Google Chrome when I try to reach the website by typing dev.example.com into Chrome's address bar. I do, however, get the Apache2 default page when I type localhost into the address bar.

**Comment by Mang506** [comment]
I'm getting the same result following the tutorial. Likewise with Firefox and Edge, at least for my situation. My setup is using WSL Ubuntu which might be the issue with mine.

**Comment by anthonydillon** [comment]
@joserick would you have time to looking this issue and provide guidance please.

**Comment by shubhamranjan12** [comment]
I am getting the same issue.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
