### ISSUE TITLE
[Create a bootable USB stick on Ubuntu] Can't find live image, or even 32 bit image

### ISSUE THREAD

**Issue by zargulthewizard** [canonical-web-and-design/tutorials.ubuntu.com#1089]
I'm trying to find a 32 bit, live Ubuntu disk image to burn, but the download site keeps trying to give me 64 bit (which is correct for the machine I'm using for the download but not the one I want to install Ubuntu on), and I can't tell if it's live or not.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
