### ISSUE TITLE
Typo in command line tutorial 

### ISSUE THREAD

**Issue by marialani** [canonical-web-and-design/tutorials.ubuntu.com#1091]
Typo can be found on this page - [Command line tutorial](https://tutorials.ubuntu.com/tutorial/command-line-for-beginners#2)

"Let's run our first command. **Cick** the mouse into the window to make sure..."

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
