### ISSUE TITLE
how do you freeze a version and disable updates?

### ISSUE THREAD

**Issue by inquiribus** [canonical-web-and-design/tutorials.ubuntu.com#1092]
My system has been hosed by snap overeager updates.  Some people DO NOT want the latest and greatest at all times.  How do you prevent happy snapping?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
