### ISSUE TITLE
Ubuntu Server tutorial is lacking in some steps

### ISSUE THREAD

**Issue by KenChenRyan** [canonical-web-and-design/tutorials.ubuntu.com#1094]
As of Ubuntu Server 18.04.3 LTS the installation configurations have 13 steps. The [tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-server) to install Ubuntu Server, is outdated and only contains 6 steps.

**Comment by KenChenRyan** [comment]
Further more several pages themselves are probably outdated. For example the Filesystem Setup page is lacking  the option to Partition an entire disk and setting up LVM.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
