### ISSUE TITLE
[Install Ubuntu on a Chromebook] Desktop only no 'open terminal' option

### ISSUE THREAD

**Issue by kubicki14** [canonical-web-and-design/tutorials.ubuntu.com#1096]
https://askubuntu.com/questions/760356/ubuntu-16-04-unity-no-desktop-just-background-wallpaper

Tried to follow that fix after trying to follow this guide:
https://tutorials.ubuntu.com/tutorial/install-ubuntu-on-chromebook#0

While following the guide I have no options except New folder and new document when right-clicking, and /usr/bin/gnome-terminal doesnt exist. Also /bin/bash would not run. Help?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
