### ISSUE TITLE
Apache install failure

### ISSUE THREAD

**Issue by pezaodc** [canonical-web-and-design/tutorials.ubuntu.com#1097]
In trying to install apache2 on Ubuntu 18.04 (fresh install and fully updated) I quickly get an install failure.  The full readout is as follows:

user@server:~$ sudo apt-get install apache2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.2-0
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.2-0
0 upgraded, 9 newly installed, 0 to remove and 223 not upgraded.
Need to get 1,071 kB/1,713 kB of archives.
After this operation, 6,917 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Ign:1 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-bin amd64 2.4.29-1ubuntu4.11
Err:1 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 apache2-bin amd64 2.4.29-1ubuntu4.11
  Connection failed [IP: 91.189.91.26 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-bin_2.4.29-1ubuntu4.11_amd64.deb  Connection failed [IP: 91.189.91.26 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

After trying the suggested --fix-missing the result is the same with the last line replaced with this:
E: Aborting install.

I find nothing online to get around this.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
