### ISSUE TITLE
Create your first snap is out of date

### ISSUE THREAD

**Issue by anonymouse64** [canonical-web-and-design/tutorials.ubuntu.com#1098]
The Create your first snap tutorial page at https://tutorials.ubuntu.com/tutorial/create-your-first-snap#4 mentions using `snapcraft` and then `snap try prime`, however with recent versions of snapcraft by default snapcraft will install and use multipass, and the prime folder does not exist outside of the build VM, so the next step to run `snap try prime` fails. 

I recommend this tutorial be updated to have folks run `snapcraft try` which will mount the `prime` folder from the build VM to the host so that the user can run `snap try prime` successfully. 

Originally reported on https://forum.snapcraft.io/t/solved-error-on-walkthrough-tutorial/14133

**Comment by sinusoid** [comment]
A problem with all the tutorials is that they don't have dates on them at all within the tutorial. It's impossible to tell if something was written 2 hours ago or 2 years ago.

If you select a tutorial from the main https://tutorials.ubuntu.com page then there are dates on that main page. If you found the tutorials from google or other links then you land directly inside the tutorial where there are no dates.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
