### ISSUE TITLE
Tutorial Wanted: How to update the Linux Kernel in Ubuntu

### ISSUE THREAD

**Issue by derPoltergeist-python** [canonical-web-and-design/tutorials.ubuntu.com#1099]
Hello!
Thank you for the amazing Ubuntu operating System!
I am not able to find a proper tutorial to update the Linux Kernel in Ubuntu.

I request a tutorial on this, please!

Maybe this tutorial could be using the command line or a kernel update utility (which i am not aware of, if already present).

Thank you and have a great ay ahead!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
