### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by apigban** [canonical-web-and-design/tutorials.ubuntu.com#1100]
**LINE 51:** "If you are using other Linux distribution, you have to install snapd **firt**. Refer to Snapd documentation for more information on installing snapd on your Linux distribution."

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
