### ISSUE TITLE
[Install Ubuntu 19.10 desktop] Can't use downloader ISO 

### ISSUE THREAD

**Issue by MARIAMOS2002** [canonical-web-and-design/tutorials.ubuntu.com#1102]
Hey!
I downloaded the Ubuntu 19.10 ISO and burned it on an USB stick. Then I tried to boot on the stick but it keeped booting on Windows.
I tried to boot on legacy mode, then it told me that no OS was find on the stick.
I want to know if I am the only one who get this problem or if the problem is the ISO.

Thanks!

**Comment by RobertChilewskiGit** [comment]
Did you move it in the boot sequence in Bios?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
