### ISSUE TITLE
Ubuntu Core 18 running Mir uses Wayland or Xorg?

### ISSUE THREAD

**Issue by jibberjabberish** [canonical-web-and-design/tutorials.ubuntu.com#1110]
The tutorial (https://tutorials.ubuntu.com/tutorial/x11-kiosk#1) currently says "We use Wayland as the primary display interface. "... but I thought Ubuntu reverted back to Xorg? So is there no reason to use Xwayland anymore in snaps for Ubuntu Core 18? or is it Mir that still uses Wayland, so we need to use Xwayland? Is there an alternative to Mir so we don't have to bridge this gap? Or is it necessary to do it this way for a secure windowing environment inside Ubuntu Core 18?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
