### ISSUE TITLE
Cannot write DVD image from Catalina

### ISSUE THREAD

**Issue by pecsy** [canonical-web-and-design/tutorials.ubuntu.com#1114]
Hi,

I have downloaded ubuntu-18.04.3-desktop-amd64.iso and tried to follow the instructions at https://tutorials.ubuntu.com/tutorial/tutorial-burn-a-dvd-on-macos
However, at step 2 when I select "Burn Disk image..." I get an error message:
"Could not burn "ubuntu-18.04.3-desktop-amd64.iso". The disk image is invalid."

I also tried to mount the image, it gave "no mountable file system" result.

I verified the MD5 hash of the image, it is correct.
I need to create this bootable DVD from my Mac to fix another computer that cannot boot anymore due to a failed system update and the system doesn't support booting from a USB.

Please advise!

Thanks,
Gabor

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
