### ISSUE TITLE
[Basic snap usage] bash: hello: command not found

### ISSUE THREAD

**Issue by lemn8** [canonical-web-and-design/tutorials.ubuntu.com#1115]
After succesfully installing hello.

The command "hello" only gives me: bash: "hello: command not found"
The command "snap hello" gives me the same result.
I did not reboot after installing snapd because it's not written anywere. So if you don't hear from me again, then you need to reboot!.

**Comment by lemn8** [comment]
export PATH=$PATH:/snap/bin

The above i had to put in my terminal then it worked. Hope i helped

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
