### ISSUE TITLE
[Create a bootable USB stick on macOS] <please add a title>

### ISSUE THREAD

**Issue by libertinephotography** [canonical-web-and-design/tutorials.ubuntu.com#1118]
in Catalina (OS X 10.15.2), I'm not being offered a scheme choice when I step to ease the thumb drive . . . - step 3 of "create a bottle USB stick on macOS - https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#2
methinks I'm sunk with out defining such ---

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
