### ISSUE TITLE
Macbook Pro 2019 Keyoard and Trackpad not working on Ubuntu

### ISSUE THREAD

**Issue by abhisek176** [canonical-web-and-design/tutorials.ubuntu.com#1119]
I am trying to boot ubuntu from an external SSD in my Macbook pro-2019 model. I find the keyboard and trackpad are not working. Similarly, If I use a flash drive with bootable Ubuntu 18.04, I see the same thing. Can anybody please tell me a workaround for this?

**Comment by timClicks** [comment]
A good place to ask this question is at https://askubuntu.com/. This issue tracker is purely for tutorials.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
