### ISSUE TITLE
[Getting started with Charmed OSM] <please add a title>

### ISSUE THREAD

**Issue by elgamal2020** [canonical-web-and-design/tutorials.ubuntu.com#1120]
The OSM version is not mentioned giving an indication it is the latest upstream many commands not found

**Comment by tytus-kurek** [comment]
@elgamal2020 could you please indicate the commands that are not found?

**Comment by elgamal2020** [comment]
cluster list . I discover later that it was release 6 which dosn't have it 
I think the charm OSM can be good product but it is still lacking of documentation 

For the tutorial , I didn't get the last NS to be working , it should be mentioned how external connectivity can be enabled by microstack to its instasiated VMs

**Comment by tytus-kurek** [comment]
@elgamal2020 Charmed OSM is still using the images from release 6, so some commands may not work - right.

With regards to the NS problem you mention, do you by chance have logs showing what exactly is failing? Such feedback would be much appreciated.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
