### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by hhelmbold** [canonical-web-and-design/tutorials.ubuntu.com#1126]
Unfortunately this just doesn't work and it just highlights why Ubuntu will never work. It is just too difficult for the average user, not even speaking of the basic user. Older versions worked perfectly booting from CD - newer versions I just cannot get to boot from USB. Always some or other error. Tried this on a dual Xeon machine just so I can try and copy some windows files off the PC... cannot get it to work. Sorry but Ubuntu will never be mainstraim

**Comment by RobertChilewskiGit** [comment]
Heya To make a USB boot work make sure you mount the iso copy the direct files form the iso to your USB the bios will not recocnize an ISO format to boot from unless its through a CD/DVD rom.

**Comment by hhelmbold** [comment]
I appreciate the feedback but the USB boots, it just doesn't boot properly
and gives errors and then hangs on the Ubuntu logo. I love the idea of
Ubuntu, but unless it is simple to install and troubleshoot, I cannot see
how the general public will ever move over. Upgrading graphics drivers,
installing new software should be a click of an icon... Ubuntu relies way
too much on an understanding of Linux. I am not fighting against Ubuntu -
just highlighting the obstacles.

**Comment by RobertChilewskiGit** [comment]
I see Thanks for the Reply, Your using 18 or 19? i am about to give it a shot myself/ But in this case i am going to make UBUNTU 14 backup you may want to give that a shot i had no boot load install problems with it from a single boot install a few years back, So im going to Give the latest versions a try first 18/19 if they have same errors as you ill go 14ish and try to update through UBUNTU to 19 form there. Thanks.

**Comment by hhelmbold** [comment]
I found the older versions of Ubuntu booted without any problems, it seems
like it's the newer versions giving more problems. I used version 18. After
rebooting a couple of times it did eventually boot, so no idea why this is
such a hassle.

**Comment by RobertChilewskiGit** [comment]
Got 19 installed no probs i think the main issue is with HDD conversion from NTFS to FAT32, my install screen glitched for a few secs during install other then that flawless victory going to report this glitch its something with HDD conversion or main install file

**Comment by RobertChilewskiGit** [comment]
Ah Also there was an option in install that just downloaded all my updated drivers as per other Evil OS might do sure you noticed but thought id throw it out there

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
