### ISSUE TITLE
[Create a bootable USB stick on Windows] rufus doesn't work anymore

### ISSUE THREAD

**Issue by dextar1** [canonical-web-and-design/tutorials.ubuntu.com#1132]
It says that can't extract ISO

**Comment by RobertChilewskiGit** [comment]
I had no problems with Rufus try a newer version the default one in the Tutorial is a bit outdated try downloading from the main rufus site.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
