### ISSUE TITLE
[Upgrade Ubuntu desktop] Upgrade Ubuntu 18.10 to 19.10

### ISSUE THREAD

**Issue by MaryAlex** [canonical-web-and-design/tutorials.ubuntu.com#1134]
Can not update ubuntu with update-manager. Seeing "An upgrade from 'cosmic' to 'eoan' is not supported with this tool.". What to do in this case?

**Comment by RobertChilewskiGit** [comment]
you have to unload your current kernel and replace it with the ubuntu 19 kernel. Not easy to do Best of luck :)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
