### ISSUE TITLE
[Install the Arduino IDE] not /dev/ttyACM* devices listed

### ISSUE THREAD

**Issue by oztigertim** [canonical-web-and-design/tutorials.ubuntu.com#1135]
There are no /dev/ttyACM* devices shown just tty0 to 63 and ttys0 to 31 and ttyprintk

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
