### ISSUE TITLE
[Install Ubuntu Desktop] missing steps

### ISSUE THREAD

**Issue by francescolosterzo** [canonical-web-and-design/tutorials.ubuntu.com#1136]
Hello!

I am installing Ubuntu 18.04.3 desktop on my Dell laptop following [this](https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop#5) tutorial and using a USB drive.

My problem is that after the step "Prepare to install Ubuntu" I do not get to anything equivalent to the following step (i.e. "Allocate drive space"), but instead I get to a step in which I have to select the device/partition where to install it, but I can only select what looks like the USB drive itself :thinking:   

Please take a look a the attached screenshot.

What am I doing wrong? How do I install Ubuntu erasing Windows?

![Screenshot from 2020-01-27 18-39-46](https://user-images.githubusercontent.com/43170591/73203890-db81a400-4135-11ea-9207-84ed1fd3d001.png)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
