### ISSUE TITLE
Revisit codelabs.json

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/tutorials.ubuntu.com#114]
The main tutorial data appears to exist in `/api/codelabs.json`, which sits in the main repo.

#112 consume `codelabs.json` to create a more nicely structured API files, that sit in an ignored `/api/tutorials` directory. But I'm thinking that stuff should really sit at `/api`, and the `codelabs.json` should live elsewhere. It would be nice to remove that data from this APP and put it somewhere else.

I'm not sure what the ideal solution is right now.

**Comment by WillMoggridge** [comment]
I would like to remove the distinction between our internal and external APIs, as they could easily serve the same purpose in a tidier way.

I think I like the APIs sitting in a `tutorials` folder, matching with the `tutorial` subfolder they sit in. Then if we have other sections on the site, they could follow a similar pattern.

**Comment by nottrobin** [comment]
That's a good point, it really should just use the same API. So the original build tool should create the API in the nicer structure.

But I feel it's implied that "https://tutorials.ubuntu.com/api/recent" provides recent tutorials. You don't need an extra "/tutorials" just to make double sure, do you?

**Comment by WillMoggridge** [comment]
Yeah, it does indeed make sense, it is just if we wanted to be more explicit. We could find it is beneficial to have the file as an aggregate of subfolders. For example if we add video pages, aggregating videos and tutorials.

This may not be the best approach and can be weighed up against alternatives.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
