### ISSUE TITLE
Tutorial Request - Django App

### ISSUE THREAD

**Issue by darthlukan** [canonical-web-and-design/tutorials.ubuntu.com#115]
The concept of "parts" is really interesting, if I understand it correctly, you could setup a webserver and database as parts which would run alongside your Django application similarly to the way a docker user would configure a database container, webserver container, and app container. This would enable some pretty cool deployment possibilities but there is currently no tutorial describing how to take a complete Django app and put together a snap which runs all of the necessary components.

I'll be experimenting with the snapcraft.yml file and parts in order to try and figure it out based on current documentation, but a tutorial would go a long way toward assisting people (like me) who are interested in this.

**Comment by WillMoggridge** [comment]
This would be interesting to me, ways to use snaps for that process.

Thanks for the request, I'll pass it along to our Tutorials team.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
