### ISSUE TITLE
Please revive the "resume" functionality

### ISSUE THREAD

**Issue by didrocks** [canonical-web-and-design/tutorials.ubuntu.com#118]
I did patched and fixed the resume functionality of codelabs. It seems it's not working anymore. Please revive it. I did send on the 16th february the patch to @WillMoggridge.

**Comment by WillMoggridge** [comment]
I don't think I received this patch, where did you send it to me?

If possible, could you include the patch here?

**Comment by didrocks** [comment]
I did send it to you through email, but you can find it from the place you copied my code from: https://github.com/ubuntu/codelabs/blob/master/tools/codelab-component.patch.

**Comment by frankiegranato** [comment]
@WillMoggridge what is the status of this issue? Is it fixed now?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
