### ISSUE TITLE
Add instructions for building the snap for offline usage

### ISSUE THREAD

**Issue by didrocks** [canonical-web-and-design/tutorials.ubuntu.com#119]
I need the instructions for building the tutorial snap for offline usage.

The usage is:
- build the snap including all tutorials
- build the snap for a specific set of topics: like snap and snapcraft

The snap should work offline, without any network access (including ubuntu css)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
