### ISSUE TITLE
Configure multiple Polymer builds

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-web-and-design/tutorials.ubuntu.com#122]
In an upcoming `polymer-cli` release allows multiple builds to be configured.
This allow overriding the `build/bundled` and `build/unbundled` options and adding more builds.

Documentation:
https://github.com/Polymer/docs/blob/ff74953fa93ad41d659a6f5a14c5f7072368edbd/app/2.0/docs/tools/polymer-json.md#builds

We can use this to tweak our builds and alto look at using it to create builds with filtered tutorial content. Such as containing tutorials for a certain category.

**Comment by WillMoggridge** [comment]
I believe this is a requirement for updating to Polymer 2 #338

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
