### ISSUE TITLE
Tutorials on developing for the Ubuntu Desktop

### ISSUE THREAD

**Issue by ryanleesipes** [canonical-web-and-design/tutorials.ubuntu.com#134]
The Developer portal seems out of date on providing good tutorials for targeting the Ubuntu desktop (more focused on Personal/Touch). I know these things are intended to converge, but there should be a better developer story that has up-to-date examples.

**Comment by WillMoggridge** [comment]
Thanks ryanleesipes. We are working on the next iteration of the developer site over the next few weeks and we want the two websites to be better inline. This should be a step in this direction and I will flag up the interest in these tutorials.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
