### ISSUE TITLE
snap an electron app

### ISSUE THREAD

**Issue by elopio** [canonical-web-and-design/tutorials.ubuntu.com#135]
With, and without electron-builder.

**Comment by ryanleesipes** [comment]
Agreed, this is a great idea.

**Comment by WillMoggridge** [comment]
Thanks for the suggestion!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
