### ISSUE TITLE
Reference to "account page" in "Create your own Core image" tutorial difficult to follow

### ISSUE THREAD

**Issue by OddBloke** [canonical-web-and-design/tutorials.ubuntu.com#137]
As someone who isn't snapping every day and has never produced a phone app, I'm not that familiar with the Ubuntu store web interface. When https://tutorials.ubuntu.com/tutorial/create-your-own-core-image#4 tells me to use "the account ID that you will find it on your account page (in the Account ID field)", it's not clear to me how to get to that account page.

I ended up Googling for Ubuntu Store and then clicking around for a while until I happened upon my account page. A direct link to https://myapps.developer.ubuntu.com/dev/account/ would be much more friendly.

**Comment by OddBloke** [comment]
(Other than that, this tutorial was great! Thanks!)

**Comment by didrocks** [comment]
Yeah, it's a good feedback. We are relying than people flashed ubuntu core on one device before creating one. In those steps, people have created an account on myapps. We need to rephrase that in the pre-requisite to ensure this is the case :)
Thanks for spotting this!

**Comment by OddBloke** [comment]
On 10/03/17 02:52, Didier Roche wrote:
> Yeah, it's a good feedback. We are relying than people flashed ubuntu
> core on one device before creating one. In those steps, people have
> created an account on myapps. We need to rephrase that in the
> pre-requisite to ensure this is the case :)
> Thanks for spotting this!

For clarity, I did have an account for doing snap stuff, but I've been
using snapcraft to do everything so I'd forgotten how the web interface
worked. :)

(Maybe it would be nice if snapcraft could just spit out this info for you?)

**Comment by didrocks** [comment]
+1, do you mind opening a bug on snapcraft itself?

**Comment by OddBloke** [comment]
I've filed https://bugs.launchpad.net/snappy/+bug/1671855.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
