### ISSUE TITLE
[Feature Request] Progress bar 

### ISSUE THREAD

**Issue by ksthiele** [canonical-web-and-design/tutorials.ubuntu.com#139]
Every tutorial get a progress bar when you start it to see on which page you are. an easy 
`<progress value="3" max="6"></progress>`
should do the job and allow the user to revisit where he left off and when you completed a tutorial it should show a check mark

**Comment by WillMoggridge** [comment]
This sounds like a really nice addition. I will need to look into the best way to tie into the codelabs component, though.

**Comment by matthewpaulthomas** [comment]
This is a nice idea, but a progress bar is the wrong control to use in this case. A progress bar is for reassuring the user about something they are having to wait for, not for showing the user’s own progress.

For example, [from the Mac interface guidelines](https://developer.apple.com/macos/human-interface-guidelines/indicators/progress-indicators/): “Use progress indicators to let people know your app isn’t stalled and to give them some idea of how long they’ll be waiting.”

And [from the Windows interface guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742475(v=vs.85).aspx): “Is an indeterminate progress bar used to wait for the user to complete a task? If so, don't use a progress bar. Progress bars are for computer progress, not user progress.” (“Indeterminate” here seems to be a mistaken copy-and-paste: it’s just as true for determinate progress bars.)

In 2004 [I proposed that HTML have a separate element](https://lists.w3.org/Archives/Public/public-whatwg-archive/2004Sep/0024.html) for visualizing fractional quantities in cases where a progress bar would not be appropriate. [That proposal was adopted](https://lists.w3.org/Archives/Public/public-whatwg-archive/2006Mar/0214.html) two years later as [the `<meter>` element](https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element). I think that’s the right element to use here.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
