### ISSUE TITLE
User type and Topic tutorial guidelines

### ISSUE THREAD

**Issue by Greggless** [canonical-web-and-design/tutorials.ubuntu.com#147]
**Recommendations for tutorial guidelines:**

- State what defines a user type: (developer, system admin etc) 
  - because testing revealed people thought that the difficulty level was our user type

- Include a suggested list of user types under each topic for authors to choose from

**Exporting data from tutorial markdown:**
- Category will be exported as 'topic'
- Additional meta-data item to be exported as 'user type'

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
