### ISSUE TITLE
ubuntu-image -o is deprecated

### ISSUE THREAD

**Issue by elopio** [canonical-web-and-design/tutorials.ubuntu.com#149]
In https://tutorials.ubuntu.com/tutorial/create-your-own-core-image#5 there's a step that asks to run:

    sudo ubuntu-image -o joule.img -c beta joule.model 

The -o flag in ubuntu-image is deprecated. It should be replaced with -O.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
