### ISSUE TITLE
munchkin tag isn't appearing in marketo on actual tutorials

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/tutorials.ubuntu.com#167]
the munchkin code is added via google tag manager, and it is firing on the page, but it doesn't make it to marketo... can you add it to the list of things to look at, I have a feeling it is similar to the google search issue.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
