### ISSUE TITLE
default filter order should be "least difficult first"

### ISSUE THREAD

**Issue by didrocks** [canonical-web-and-design/tutorials.ubuntu.com#168]
People new to the website doesn't care about latest updated tutorials. We want people to follow the logical order which is to start with the least difficult to progress further

**Comment by WillMoggridge** [comment]
Hey @Greggless, do you have any opinions on this change?
Otherwise it seems reasonable.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
