### ISSUE TITLE
Create your own Core image: missing mention of --extra-snaps

### ISSUE THREAD

**Issue by kyrofa** [canonical-web-and-design/tutorials.ubuntu.com#172]
[Page 5 of the "Create your own Core image" tutorial](https://tutorials.ubuntu.com/tutorial/create-your-own-core-image#4) is where one actually writes the model definition. The various fields of the definition are broken down and explained. There are two specific explanations I'd like to call out:

> - gadget: name of the gadget snap as published on the store. Note that this snap can be a file on disk.
> - kernel: name of the gadget snap as published on the store. Similarly to the gadget snap, it can be a file on disk.

"this snap can be a file on disk" leads me to believe that I can specify a file path here, but that's not the case. The model definition (and thus the assertion) _only_ contains the snap names. If one wants to use a file on disk, one doesn't change the definition or assertion at all: one must use the `--extra-snaps` option from `ubuntu-image`. This was difficult to learn, and a more explicit definition of these fields as well as a quick blurb about `--extra-snaps` would clear it all up.

**Comment by niemeyer** [comment]
Please don't put that option in the tutorial. This option is most likely going away at some point, because we cannot accept extra snaps in an image that are not in the model signed by the image publisher.

**Comment by niemeyer** [comment]
Issue being discussed here:

https://forum.snapcraft.io/t/issues-encountered-while-creating-custom-gadget-and-image/66

**Comment by caldav** [comment]
@niemeyer acked, please let us know when it goes away, as the option is referenced in other learning materials

**Comment by niemeyer** [comment]
Will do. Topic moved, updated link above.

**Comment by kyrofa** [comment]
Perhaps the tutorial should stop mentioning these could be a file on disk then. It's confusing as-is.

**Comment by didrocks** [comment]
So, we just removed that those could be a file on disk and call it a day, correct? How does that file in a tutorial when people create their own gadget snap and reuse it to build an image thus? This is what the tutorials emphasizes on and the upstream snapd documentation doesn't help at all understanding how this would work.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
