### ISSUE TITLE
Event page doesn't show up top banner anymore

### ISSUE THREAD

**Issue by didrocks** [canonical-web-and-design/tutorials.ubuntu.com#174]
The event page has been broken recently (it was still working a couple of weeks ago): https://tutorials.ubuntu.com/events/idf-2016 doesn't render the top banner nor the description.

**Comment by WillMoggridge** [comment]
This happened from a restyle of the header. As we did not have designs for the events at the time and they are not in use, we removed them for the time being.

We want to add them back along with a nice user flow for events in the near future.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
