### ISSUE TITLE
Intel Joule Tutorial: Create a bootable Ubuntu Core 16 SD card has no instructions for Windows

### ISSUE THREAD

**Issue by flexiondotorg** [canonical-web-and-design/tutorials.ubuntu.com#177]
On the first page of the tutorial, in the what you need section, it says you will need an Ubuntu 16.04 desktop or Windows. Step 3 of the tutorial, [Create a bootable Ubuntu Core 16 SD card](https://tutorials.ubuntu.com/tutorial/setup-ubuntu-core-intel-joule#2), only describes how to create an image using Ubuntu and has no instructions for Windows users.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
