### ISSUE TITLE
Intel Joule Tutorial: Create a bootable Ubuntu Core 16 SD card uses dd only

### ISSUE THREAD

**Issue by flexiondotorg** [canonical-web-and-design/tutorials.ubuntu.com#178]
Disks, `gnome-disks` is installed by default on Ubuntu Desktop 16.04. It is capable to copying the Intel Joule image to an SD card using a simple GUI and even works with xz compressed images. Perhaps using the *Restore Disk Image...* feature should be documented to simplify the process and limit the scope of user error with `dd`.

**Comment by didrocks** [comment]
The rest of the tutorial is ran from a command line, it doesn't sound to match to have some steps in a GUI and others from the CLI. We decided that the bare minimum for snap tutorials was to be familiar with the CLI, which sounds for to create an IoT device which is going to be command line only.

Note that this is aligned with the instructions on getting started.
Making sense?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
