### ISSUE TITLE
[Snap a python application] git is not installed by default

### ISSUE THREAD

**Issue by flexiondotorg** [canonical-web-and-design/tutorials.ubuntu.com#179]
On [2. Getting familiar with the project](https://tutorials.ubuntu.com/tutorial/snap-python-app#1) `git` is used to branch `httpstat`. Git is not installed by default on Ubuntu and the documentation should include `sudo apt install git` before `git` is used.

**Comment by jlosito** [comment]
Can this ticket be closed? I see the git install step has been added and is live now.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
