### ISSUE TITLE
On boarding for Windows devs

### ISSUE THREAD

**Issue by mikehans** [canonical-web-and-design/tutorials.ubuntu.com#184]
I'm a pro Windows dev (C#, Node, JavaScript with a little Python) looking to adopt Linux and Linux dev and would appreciate some tutorials that would serve as a on-ramp to Linux development.

**Comment by WillMoggridge** [comment]
Hey, thanks for the request. I will forward this to the tutorials team.
This is possibly related to #134

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
