### ISSUE TITLE
cVim bindings are blocked in turorials

### ISSUE THREAD

**Issue by vpetersson** [canonical-web-and-design/tutorials.ubuntu.com#189]
This is certainly not a major bug, but still, something that bothered me. I use [cVim](https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh?hl=en) for `vim`-style navigation in Chrome. In does, however, seem like both *j* and *k* are being blocked by the tutorial framework.

**Comment by WillMoggridge** [comment]
Ah, I have had similar issues before on websites (I used a similar plugin before). I will look into this and see what the best solution is.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
