### ISSUE TITLE
juju charming

### ISSUE THREAD

**Issue by aym-frikha** [canonical-web-and-design/tutorials.ubuntu.com#193]
I think it would be nice to have tutorial to create juju charms (basic and advanced). Documentation for charming are dispersed like (traditional / reactive/ layered/ charm helpers .....)

**Comment by WillMoggridge** [comment]
Thanks for this recommendation. This sounds like a great idea for tutorials.

**Comment by pmatulis** [comment]
This is now available:

https://tutorials.ubuntu.com/tutorial/tutorial-charm-development-part1

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
