### ISSUE TITLE
Quite a few grammar mistakes in the "Create your own Core image" tutorial

### ISSUE THREAD

**Issue by jhodapp** [canonical-web-and-design/tutorials.ubuntu.com#195]
There's quite a few grammar mistakes in the "Create your own Core image" tutorial, including right on the very first page. Some examples include:

>You can't do this on an Ubuntu Core device directly as creating your image can take quite _some disk spaces_.

and:

>Some very basic knowledge of command line use _, know how to edit files_.

This tutorial could use another round of complete grammar review.

**Comment by WillMoggridge** [comment]
Thanks for flagging this up. I am pushing those points across and we will set some time aside to review the documents.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
