### ISSUE TITLE
[Chrome] Fix zoom in 'difficulty level' bug 

### ISSUE THREAD

**Issue by joanasa89** [canonical-web-and-design/tutorials.ubuntu.com#204]
'Difficulty level' pictogram is not masked correctly

<img width="423" alt="screen shot 2017-05-16 at 17 13 23" src="https://cloud.githubusercontent.com/assets/21334617/26116423/ff085a0c-3a5a-11e7-94f4-9473a3b43448.png">

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
