### ISSUE TITLE
Creating first snap tutorial: sudo snap try requires not being in "classic" mode.

### ISSUE THREAD

**Issue by fad0** [canonical-web-and-design/tutorials.ubuntu.com#210]
I am running Ubuntu Core 16 (GNU/Linux 4.4.0-1030-raspi2 armv7l) on a RPI3.  The tutorial is https://tutorials.ubuntu.com/tutorial/create-first-snap#0

Everything seems to be working up to the "sudo snap try" step:

>(classic)fad0@localhost:\~/hello$ snapcraft prime
>Skipping pull gnu-hello (already ran)
>Skipping build gnu-hello (already ran)
>Skipping stage gnu-hello (already ran)
>Skipping prime gnu-hello (already ran)
>(classic)fad0@localhost:\~/hello$ sudo snap try --devmode prime/
>error: cannot get data for "hello": [0x34b36d00 0x34b36ea0 0x34b36f70 0x34b37040 0x34b37110]
>(classic)fad0@localhost:\~/hello$ hello
>-bash: hello: command not found

However, if I exit "classic" mode and run "sudo snap try --devmode prime/", hello is properly installed and I can run it.  But the tutorial does not say to exit classic mode before running "sudo snap try...":

>fad0@localhost:\~/hello$ sudo snap try --devmode prime/
>hello 2.10 mounted from /home/fad0/hello/prime
>fad0@localhost:\~/hello$ which hello
>/snap/bin/hello
>fad0@localhost:\~/hello$ hello
>Hello, world!

If exiting "classic" mode to run "sudo snap try" is necessary (which is the case for me), the documentation should mention it.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
