### ISSUE TITLE
End of create-first-snap tutorial ends at tutorials.ubuntu.com instead of snapcraft.io

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/tutorials.ubuntu.com#223]
Chances are you arrived at the create-first-snap tutorial from https://snapcraft.io. However, finishing it lands you at https://tutorials.ubuntu.com.

Steps to reproduce:
- Start create-first-snap tutorial by clicking on the snapcraft.io front page link
- Complete tutorial

What happens:
- You're sent to https://tutorials.ubuntu.com
- You have no way back to snapcraft.io

What should happen:
- You are immediately sent back to snapcraft.io upon completing the create-first-snap tutorial

**Comment by didrocks** [comment]
This support was in my afternoon prototype on which this website is based, but was removed when the web team took it over to host it.
I guess resurecting it will be easy if they want to (we have "previous" button support for internal like events pages which have been removed) and external sites.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
