### ISSUE TITLE
Build your first snap tutorial assumes you're running Ubuntu Core

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/tutorials.ubuntu.com#224]
<img width="813" alt="screen shot 2017-06-13 at 14 23 37" src="https://user-images.githubusercontent.com/1523179/27084467-f041090c-5043-11e7-8444-0207637a81de.png">

Developers are currently far more likely to be running Ubuntu or other distributions than Ubuntu Core. The create-first-snap tutorial however walks you through installing snapcraft on Ubuntu Core, and does so using apt instead of snap (preferred).

Can we please update this tutorial to match the distribution-neutral (no assumption of snapd being installed) [snapcraft install instructions](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.xd4fat9opl48)?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
