### ISSUE TITLE
Drop references to uploading via the Snap Store

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/tutorials.ubuntu.com#225]
<img width="811" alt="screen shot 2017-06-13 at 14 48 55" src="https://user-images.githubusercontent.com/1523179/27085540-7ac78008-5047-11e7-959e-9fd458ba5ae5.png">

On the create-first-snap tutorial, "Apps can easily be uploaded to the store via \<a>My Apps\</a>."

It was decided at the Product sprint that we will drop the snap upload form on developer.snapcraft.io and instead guide people to the CLI. We should update this tutorial to match that decision.

**Comment by nottrobin** [comment]
Are we officially recommending people upload snaps via the web interface? I thought the official recommendation for now was that you only push snaps from the CLI with snapcraft (given that you will have had to build it with snapcraft anyway).

**Comment by evandandrea** [comment]
Correct. This tutorial predates that decision. I'm rewording this accordingly now.

**Comment by frankiegranato** [comment]
@caldav are you able to pick this up please? Let me know if you need our assistance :-)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
