### ISSUE TITLE
Consider moving contributor info to wiki?

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#231]
I think it may make more sense to include the contributor information in the built-in github wiki rather than link to an external site, if not as a document in the repo itself

**Comment by WillMoggridge** [comment]
I don't have objections to this. The wiki sounds like a nice place to put it.

**Comment by caldav** [comment]
I would be more in favor of publishing it to prod, since it's now a tutorial. Although, it needs to be tweaked for this, as it currently invites the user to read it along the md source.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
