### ISSUE TITLE
Tutorial content should display a license

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#232]
There doesn't seem to be a displayed license for the content of the tutorials. I would recommend a CC-BY-SA-NC (the same as digitalocean's)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
