### ISSUE TITLE
tutorials.snapcraft.io domain and branding

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/tutorials.ubuntu.com#233]
Snapcraft is a distribution-neutral platform for delivering software. Because it was readily available, snapcraft-specific tutorials were created on tutorials.ubuntu.com, but this jump from Snapcraft to Ubuntu is confusing.

Let's create tutorials.snapcraft.io. It can back onto the same infrastructure as tutorials.ubuntu.com, but should have its own branding and should only show snapcraft-specific content.

**Comment by evandandrea** [comment]
See also https://github.com/canonical-websites/snapcraft.io/issues/268, https://github.com/canonical-websites/snapcraft.io/issues/320, and https://github.com/canonical-websites/snapcraft.io/issues/341.

**Comment by WillMoggridge** [comment]
This is something we really want to do.

I think the best way for us to achieve this it to abstract the site into an importable web component, which we can take advantage of CSS variables and mixins to tweak the site as needed.
Then we could have a separate build step but it may be easier to keep a separate repository while sharing the central web component.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
