### ISSUE TITLE
Tutorial needed - ZFS for LXD

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#241]
A tutorial on enhancing the ZFS pool for LXD - the default setup uses file-backed storage which is not really recommended for serious use. this tutorial would show how to update it and make the pool bigger/better/faster

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
