### ISSUE TITLE
Install Ubuntu on a computer without any OS

### ISSUE THREAD

**Issue by nimaragbar** [canonical-web-and-design/tutorials.ubuntu.com#257]
Hello
 
Many peoples have trouble with **installing Ubuntu as the first system OS**!!  (on a system that has any operation system)
like _grub issue_, _bootloader errors_, _EFI  boot loader_ and etc.
Please cover this important issue.

Best regards

**Comment by nimaragbar** [comment]
I can write this manual for Ubuntu users, 
are you really want it?

manual about: 
create a **bootloader** partition with **GParted**
and configure the device.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
