### ISSUE TITLE
Style issue with nested lists

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#289]
![real1](https://user-images.githubusercontent.com/115290/28323870-e53f99ca-6bd1-11e7-8f4b-28ba9a2a79dd.png)

There is way too much space between paragraph text in a list item and subsequent nested list items, as can be seen here under the second heading

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
