### ISSUE TITLE
Use OpenGraph to improve social sharing of tutorials

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/tutorials.ubuntu.com#293]
Currently, sharing a tutorial on a social network is a rather poor experience. Most social networks use their own means to get page metadata when sharing a link and our page titles, images, description, are wrong in most cases. This is probably caused by our lack of content visibility without Javascript.

[OpenGraph](http://ogp.me/) is a widely enough supported protocol to enforce the right metadata to be shared.

 OpenGraph metadata we should have on each page:
## Required by OpenGraph
* og:title : title of the tutorial
* og:type : "article"
* og:url : tutorial url
* og:image : default tutorials image or custom
## Optional
* og:description
* og:site_name
* article:tag
* ...

**Comment by WillMoggridge** [comment]
#339 will help set this up

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
