### ISSUE TITLE
required-snaps is now properly implemented

### ISSUE THREAD

**Issue by lool** [canonical-web-and-design/tutorials.ubuntu.com#315]
Hi,

In:
https://tutorials.ubuntu.com/tutorial/create-your-own-core-image#4
there's this statement:
> Despite the "required" name, a known bug make it possible to remove those snaps after booting on the final image. This is known with current version of snapd (2.16) and will get fixed in the future.

However, this feature is now implemented and snaps can't be removed after installation, so the statement should be removed from the tutorial  :-)

Thanks,
- Loïc Minier

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
