### ISSUE TITLE
Rufus warn about additional download

### ISSUE THREAD

**Issue by Webysther** [canonical-web-and-design/tutorials.ubuntu.com#322]
Maybe include additional step before (or inside) here:

https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#4

And more about warning:

https://github.com/pbatard/rufus/wiki/FAQ#rufus-says-that-the-download-files-for-syslinuxgrub-are-missing-on-the-server

![sj4gzm9](https://user-images.githubusercontent.com/750007/30093800-31a532be-929e-11e7-8350-09cb6aef5a85.png)

**Comment by WillMoggridge** [comment]
Thanks for pointing this out to us, Webysther.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
