### ISSUE TITLE
Ubuntu Server 16.04.3 LTS -installation failed

### ISSUE THREAD

**Issue by gyekyeJ** [canonical-web-and-design/tutorials.ubuntu.com#326]
installation keep failing @ procedure number 11

**Comment by deadlight** [comment]
Thank you for the report, we will look into potential issues with this tutorial.

Please respond with more details if you experienced and behaviours or error messages that could help us.

Thanks,
Karl

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
