### ISSUE TITLE
macOS instructions to boot from external usb hdd  with ubuntu already installed (from bootable usb).

### ISSUE THREAD

**Issue by johndpope** [canonical-web-and-design/tutorials.ubuntu.com#327]
while all these steps are great (and accurate)
https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#6

if you are targeting an external usb drive for install
once you power off / on the computer and hit option on mac
there's no way to get into the newly installed hdd.

there's been attempts to solve this / but it's no longer updated. 
https://askubuntu.com/questions/525845/how-to-boot-ubuntu-on-a-mac-from-external-usb-storage

**Comment by WillMoggridge** [comment]
Thanks for flagging this up johndpope, this looks like good information to add.

**Comment by johndpope** [comment]
One critical thing to add / that crossed my mind after this / if you follow prompts / by default it will render Mac OS unusable because it updates the boot loader with grub. (It’s dependent on which drop down is selected.) I managed to get it back without a hitch (installing refindthen uninstallling )  / but if somehow Ubuntu could work out that the hdd it’s targeting to install boot loader is OS X and throw prompt that would help noobs.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
