### ISSUE TITLE
Advanced snap tutorial does not feature install/remove hook

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/tutorials.ubuntu.com#329]
https://tutorials.ubuntu.com/tutorial/advanced-snap-usage

Is missing the install hook

**Comment by WillMoggridge** [comment]
Thanks for flagging this up sparkiegeek

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
