### ISSUE TITLE
Step 3 (Verify release screenshot) includes non-working instructions for OS X

### ISSUE THREAD

**Issue by jim-kukla** [canonical-web-and-design/tutorials.ubuntu.com#336]
https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu?_ga=2.53919659.265699136.1505613246-1906034191.1505613246#2

It includes spaces in the key spec information in the command which must be removed on OS X before the keys can be imported.

See this askubuntu answer for more details:  https://askubuntu.com/a/796638

**Comment by WillMoggridge** [comment]
Thanks for flagging this up jim-kukla

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
