### ISSUE TITLE
Update to Polymer 2

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-web-and-design/tutorials.ubuntu.com#338]
Tutorials should be updated to Polymer 2.

The official migration document can be found at:
https://www.polymer-project.org/1.0/docs/migration.html

**Comment by tbille** [comment]
The Polymer version is `1.4.0` the upgrade guide is wrong it should be this one:
https://www.polymer-project.org/2.0/docs/upgrade

**Comment by WillMoggridge** [comment]
#339 is updating Polymer to 1.11.

This update to Polymer 2 is currently blocked by the codelab-components dependency (and a load of its dependencies), which need to be updated for compatibility.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
