### ISSUE TITLE
The browser back button is not working as expected

### ISSUE THREAD

**Issue by iatrou** [canonical-web-and-design/tutorials.ubuntu.com#348]
When browsing a tutorial, the "Back" button of the browser does not behave as expected.
Example:
1. Go to https://tutorials.ubuntu.com/
2. Select any tutorial (you will be taken to the first step of the tutorial, typically named "Overview"
3. From the list of steps, click on the last step.
4. Click the browser back button
- Expected behavior: go back to the first step of the tutorial
- Observed behavior: remain on the last step

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
