### ISSUE TITLE
Search, filter, and sort choices aren’t linkable

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/tutorials.ubuntu.com#357]
1\. Go to https://tutorials.ubuntu.com/
2\. Enter search text, and/or filter by topic, and/or sort the results.
3\. Copy the URL.
4\. Open a new window and load the URL.

What you see: The default list of tutorials.
What you should see: The search text, filter, and sort order that you specified.

This is inconsistent with the search functions on most Web sites. And it makes [snapcraft.io-static-pages#393](https://github.com/canonical-websites/snapcraft.io-static-pages/issues/393) impractical to fix.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
