### ISSUE TITLE
"autonomous drone development", using intel aero

### ISSUE THREAD

**Issue by guermonprez** [canonical-web-and-design/tutorials.ubuntu.com#365]
I'm a software architect for Intel Aero, the open development platform.
I propose to write a tutorial showing the basic of autonomous drone development
using Intel Aero Drone and Ubuntu.

thanks

**Comment by caldav** [comment]
Hi, I'd love to read that! Do you need any help getting started?

Here is what I recommend to people new to the platform:

1) Clone this repo and run the site locally (`./run`). If it's the first time you run it, it will download a docker image and deps. With a local instance, you'll see exactly how your tutorial renders before submitting it for review.
2) Please read the guidelines tutorial served on your local instance (http://localhost:8016). It also doubles as a template for you to use.
3) Create your tutorial as a markdown file and use `./run serve [file or folder]` to render it locally.
4) Commit your content to /tutorials/\<category\>/ and create a pull request

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
