### ISSUE TITLE
Upgrading Ubuntu desktop tutorial incorrect

### ISSUE THREAD

**Issue by murraybd** [canonical-web-and-design/tutorials.ubuntu.com#371]
https://tutorials.ubuntu.com/tutorial/tutorial-upgrading-ubuntu-desktop#2

There is no tab called "Updates" in update-manager, if you want to change the "Notify me of a new Ubuntu version" setting you need to either launch Software Properties (software-properties-gtk) or click the "Settings..." button in update-manager.

**Comment by evilnick** [comment]
Hi, yes, there are some issues with this tutorials - the primary one being there is only one tutorial, but the experience/instructions vary slightly between distros

I think the best solution is to have per-release upgrade instructions, unless someone has a better idea?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
