### ISSUE TITLE
SHA256SUMS verify: localisation 

### ISSUE THREAD

**Issue by kralisec** [canonical-web-and-design/tutorials.ubuntu.com#376]
https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#4

sha256sum -c SHA256SUMS 2>&1 | grep OK

sha256sum output is different from "OK" with localized ubuntu version
the test gives the impression that the download failed

**Comment by evilnick** [comment]
good point. we should address this - thanks!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
