### ISSUE TITLE
Bad link on Basic Snap Usage

### ISSUE THREAD

**Issue by SKelem** [canonical-web-and-design/tutorials.ubuntu.com#378]
The page, https://tutorials.ubuntu.com/tutorial/basic-snap-usage#5, has a link, https://tutorials.ubuntu.com/tutorial/create-first-snap, for creating your first link, but the link is bad. I get a 404 page not found error.

**Comment by m4sk1n** [comment]
fixed by #429…

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
