### ISSUE TITLE
The "Learn how to verify" link of 17.10's download page doesn't link to an exactly useful page

### ISSUE THREAD

**Issue by lflee** [canonical-web-and-design/tutorials.ubuntu.com#388]
At [https://www.ubuntu.com/download/desktop/thank-you?country=HK&version=17.10&architecture=amd64](url) (the page to download 17.10), the "Learn how to verify" link links to [https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu?_ga=2.235897089.1000975289.1509010684-326111988.1504766629#0](url) . But in Step 2, it doesn't link to sums and signature for 17.10.

I think it would be easier for the users if Step 2 links to sums and signature for 17.10 in this situation.

**Comment by evilnick** [comment]
Many people are still downloading and using the last LTS version (16.04), but we should have additional links for other versions, so we should add that rather than replace. Thanks for the feedback

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
