### ISSUE TITLE
[Install Ubuntu desktop] No instructions on upgrading from 16.04 LTS

### ISSUE THREAD

**Issue by kalicouk** [canonical-web-and-design/tutorials.ubuntu.com#390]
This might seem like 'too simple' an issue, but there are no instructions in this tutorial for upgrading from 16.04 LTS.  There is mention elsewhere on the site about upgrading to the latest version, but if you follow that route, Ubuntu only upgrades to 17.04, not the latest one with the GNOME desktop.

If you go to download the full 17.10, then it assumes you want to wipe your disk and install Ubuntu fresh.  Fine if you do, but there must be a lot of us on 16.04LTS who just want to move up and do not want a totally wiped disk, fresh install.

**Comment by caldav** [comment]
@kalicouk Hi, as far as I'm aware, there is no simple upgrade path from 16.04 to 17.10, you need to upgrade to 17.04 (it automatically skips 16.10 since it's no longer supported), then to 17.10. Or wait until you can upgrade from LTS to LTS 16.04 -> 18.04.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
