### ISSUE TITLE
[Project Organization] The 'fr' folder for translated tutorials is mixed with categories folders

### ISSUE THREAD

**Issue by Winael** [canonical-web-and-design/tutorials.ubuntu.com#391]
Hi

in tutorials folder, all originals tutorials are classified into catagories folder (Desktop, Cloud, IoT, Server, etc). But the folder `fr` with the translated tutorials  in in the same level.

To help translation, maybe we could use this kind of organization:

```
tutorials/
  |_ en/
  |    |_ server/
  |    |_ desktop/
  |    |_ ...
  |_ fr/
  |    |_ server/
  |    |_ desktop/
  |    |_ ...
  |_ ...  
```

Cheers,

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
