### ISSUE TITLE
[Create a bootable USB stick on Windows] <I want a tutorial on how to do it on Kubuntu/Ubuntu it self>

### ISSUE THREAD

**Issue by cykip** [canonical-web-and-design/tutorials.ubuntu.com#403]
I want a tutorial on how to do it on Kubuntu/Ubuntu it self

**Comment by caldav** [comment]
Hello, have you seen [Create a bootable USB stick on Ubuntu](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu)?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
