### ISSUE TITLE
Enable es6-unbundled build for deployment

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-web-and-design/tutorials.ubuntu.com#410]
We have disabled the `es6-unbundled` build profile as it was serving a 404 page in our Kubernetes deployment. The PR to disable this is https://github.com/canonical-websites/tutorials.ubuntu.com/pull/409

We should investigate why it is serving 404s and revert this change.

This can be seen when the build is enablid and you view the site with Chrome. Firefox will load the es6-bundled version.

---

Testing locally I was able to run prpl-server through Caddy for HTTP2, and correctly loaded the page.
Useful Caddy config for testing at https://localhost:8443 :
``` Caddyfile
localhost:8443
tls self_signed

# Serve build files directly
#root build/
#rewrite / /es6-unbundled/index.html

# Proxy requests to another server, such as prpl-server
proxy / http://localhost:8080
```

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
