### ISSUE TITLE
[How to verify your Ubuntu download] <please add a title>

### ISSUE THREAD

**Issue by jgrosmann** [canonical-web-and-design/tutorials.ubuntu.com#411]
much Much MUCH too difficult!

There should be a tool to do this.

**Comment by inuwa** [comment]
Possibly create a script to run from the terminal to automate the process.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
