### ISSUE TITLE
Content Translation Failure?

### ISSUE THREAD

**Issue by michaelb17** [canonical-web-and-design/tutorials.ubuntu.com#418]
When looking at the tutorial named 'Configuration de LXD sur Ubuntu 16.04' there is a translation failure with the feedback & sign up form at the end of the tutorial. 

Should it adopt the language of the tutorial content?

Link: https://tutorials.ubuntu.com/tutorial/tutorial-setting-up-lxd-1604-fr?backURL=%2F#4

<img width="881" alt="screen shot 2017-11-15 at 13 55 22" src="https://user-images.githubusercontent.com/32878117/32839535-ab6893d4-ca0c-11e7-8230-31d2b6b1a01b.png">

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
