### ISSUE TITLE
[Install Ubuntu desktop] But It didn't work.

### ISSUE THREAD

**Issue by robbiesmith79** [canonical-web-and-design/tutorials.ubuntu.com#420]
I need a section in this article that talks about the boot sequence instructions in the BIOS settings. Right now, when I restart, and the USB stick is not in, it says no bootable drives found. Am I suppose to use the efi's. I'm stuck. *This is after installing Ubuntu 17 following the 12 step instructions to the letter*

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
