### ISSUE TITLE
Ubuntu Tutorials Mobile Feedback & Sign-up Form CTA Spacing Error

### ISSUE THREAD

**Issue by michaelb17** [canonical-web-and-design/tutorials.ubuntu.com#421]
On the mobile view of the Ubuntu tutorials there is a spacial issue and error with the 'Subscribe' CTA and email field at the bottom of the 'Email sign-up & Feedback Form'.

Also shouldn't the buttons be 100% on mobile view?

<img width="390" alt="screen shot 2017-11-15 at 15 43 43" src="https://user-images.githubusercontent.com/32878117/32845205-15b71ecc-ca1c-11e7-9526-a6c26d689505.png">

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
