### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by Ydeep123** [canonical-web-and-design/tutorials.ubuntu.com#428]
<describe the issue>

**Comment by 3DJetengine** [comment]
perhaps [this link] could be included also - as 
opposed to filling out forms on [the wiki](https://www.reddit.com/r/Ubuntu/wiki/index) through the store.

**Comment by 3DJetengine** [comment]
Sorry for the brainstorming, and [archive.fo](http://archive.fo/Fv7rc) but this doesn't arrive until the 6th.

**Comment by anthonydillon** [comment]
Could you please provide more information on this issue.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
