### ISSUE TITLE
Tutorials - Mobile side menu covers stages on smaller screens

### ISSUE THREAD

**Issue by michaelb17** [canonical-web-and-design/tutorials.ubuntu.com#430]
On mobile breakpoints the side menu "Did you find a mistake? Please file a bug" link covers tutorials stage links on smaller device screens as shown in the screenshots below. This blocks users from selecting this tutorial stage from the side menu. 

Link: https://tutorials.ubuntu.com/tutorial/snap-a-website?backURL=%2F#0

Content covered by "Did you find a mistake? Please file a bug" message

<img width="395" alt="screen shot 2017-11-21 at 13 11 05" src="https://user-images.githubusercontent.com/32878117/33074324-a3b8f4ac-cebd-11e7-96ae-358e798439d6.png">

Larger Screens the issue is resolved

<img width="392" alt="screen shot 2017-11-21 at 13 11 19" src="https://user-images.githubusercontent.com/32878117/33074327-a4f9ecae-cebd-11e7-8d1c-43a563f0b0bf.png">

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
