### ISSUE TITLE
"Connect your laptop to a power source."

### ISSUE THREAD

**Issue by MSSProvenance** [canonical-web-and-design/tutorials.ubuntu.com#431]
Page 2 of the tutorial 
https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop#1
states "Connect your **laptop** to a power source."

This suggests it won't work with a desktop computer.

**Comment by AyahRamahi** [comment]
Hi , I am a beginner . How can I help ?

**Comment by snow8gaia** [comment]
If anyone is interested, find the page in the repo, create a pull request. Title - Fixes issue #431.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
