### ISSUE TITLE
Tutorial Wanted - using remote hosts in LXD

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#433]
This tutorial will cover using lxd/lxc commands to connect to a remote LXD host and run containers there.

It will assume the reader has a basic knowledge of LXD

There is a lot of source material in this blog
https://stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/

It may be best to base this tutorial around running LXD on the demo server - https://linuxcontainers.org/lxd/try-it/
which means you won't need two computers

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
