### ISSUE TITLE
Tutorial Wanted: Connecting to an iSCSI target

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#434]
This tutorial will cover mounting an iSCSI device under Ubuntu. iSCSI is a popular protocal used by NAS devices etc. It should be assumed that the reader has such a device.

There is already Ubuntu documentation for this topic here - https://help.ubuntu.com/lts/serverguide/iscsi-initiator.html

So this is really just about translating that information into a tutorial format

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
