### ISSUE TITLE
Tutorial Wanted: File recovery in ZFS

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#435]
This tutorial will explain to the user how to use ZFS tools to recover files in the event of a data loss.

For reference, there is an example toward the bottom of the page here: https://wiki.ubuntu.com/Kernel/Reference/ZFS

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
