### ISSUE TITLE
Tutorial Wanted - set up PGP encryption from the desktop

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#437]
This tutorial will cover installing GnuPG, creating your keys, file encryption, decryption and signing from the desktop.

It will assume the reader has a basic knowledge of cryptography, but it's worth explaining how public and private key encryption works and why you might use a key server.

The following document may be useful:
https://help.ubuntu.com/community/GnuPrivacyGuardHowto

Another tutorial has been requested to create the same tutorial using the command line:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/436

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
