### ISSUE TITLE
Tutorial Wanted: Connect Samba to Active Directory

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#438]
This tutorial will tell users how to integrate Samba into an existing Active Directory domain.

There is some useful info on this topic here: https://help.ubuntu.com/lts/serverguide/samba-ad-integration.html

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
