### ISSUE TITLE
Tutorial Wanted - managing the uncomplicated firewall (ufw)

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#439]
This tutorial will cover using and configuring the uncomplicated firewall (ufw).

It will assume the reader has a basic knowledge of networking, but it's worth explaining how ports are used, which ports may be open by default, and how they're exposed to the internet using NAT and a router.

Background info could include when your machine may be at risk - such as over an open Wifi network or insecure LAN, and how a firewall can be used to mitigate risk.

The following document may be useful:
https://help.ubuntu.com/community/UFW

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
