### ISSUE TITLE
Tutorial Wanted: Enable Livepatch kernel updates

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#440]
This tutorial will explain to users how they can enable zero downtime kernel patching on their system with the Livepatch service.

A lot of this is already covered in the website: https://auth.livepatch.canonical.com/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
