### ISSUE TITLE
Tutorial Wanted - adding software sources

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#442]
This tutorial will cover why you may want to add a software source, how they're added, how packages from those sources are installed, and how the sources are removed. This should be done from the desktop with a GUI, but it would also be useful to cover the command line instructions.

It's also worth mentioning alternatives, such as https://snapcraft.io/

The following document may be useful:
https://help.ubuntu.com/community/Repositories/Ubuntu

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
