### ISSUE TITLE
Tutorial Wanted - Making custom LXD images

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#443]
This tutorial will tell the user how to make custom LXD images. It should take them through starting a default image, adding or editing it (by changing the installed software) and then snapshotting this as a new image. Finish by explaining how to publish or share this image, as well as re-use it locally.

Most of the information for this can be found in this blog post:
https://stgraber.org/2016/03/30/lxd-2-0-image-management-512/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
