### ISSUE TITLE
Tutorial Wanted - compiling software from source

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#444]
This tutorial will cover the basics of building and installing software from source. Ideally, using a poplar  project as an example.

Possible steps might include:
- install the required dev tools
- identify dependencies
- install `-dev` dependencies as required  (`sudo apt-get build-dep` may help)
- clone project's repository, or download the tarball.
- use either './configure' or cmake as required
- build
- install

A section on troubleshooting would also be helpful: how to read build output to identify missing dependencies or version mismatches. 

The following document may be useful:
https://help.ubuntu.com/community/CompilingEasyHowTo

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
