### ISSUE TITLE
Tutorial Wanted - install Java Runtime Environment

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#445]
This tutorial will cover installing the Java Runtime Environment, still used by many applications.

It will assume the reader has a basic knowledge of package management, but for any discussion on software sources, it may be easier to refer the reader to another tutorial:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/442

The following documents may be useful:
https://help.ubuntu.com/community/Java#Installation_of_Java_Runtime_Environment

**Comment by aden-chrome** [comment]
Pull request submitted: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/523

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
