### ISSUE TITLE
Tutorial Wanted - LXD networking

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#446]
This tutorial will explain the default networking setup of LXD, before going on to provide commands and examples of other types of network configuration.

This blog post contains most of the relevant information https://insights.ubuntu.com/2017/02/14/network-management-with-lxd-2-3/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
