### ISSUE TITLE
Tutorial Wanted - how to close misbehaving apps

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#447]
This tutorial will cover the most common methods of identifying and closing misbehaving applications, from both the desktop and the command line.

Assume the reader has basic desktop knowledge and make sure the risks of closing a process are also explained (data loss, instability).

We've also requested a tutorial on monitoring your system:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/492

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
