### ISSUE TITLE
Tutorial Wanted - install additional desktop environments

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#448]
This tutorial will cover installing one or more additional desktop environments (MATE, XFCE, KDE?) and how they're activated at login.

Assume the reader has basic desktop knowledge and also that the reader may be from a Windows or macOS background where having a choice of desktop is an alien concept.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
