### ISSUE TITLE
Tutorial Wanted - Running Docker containers inside LXD

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#449]
This tutorial will provide all the steps for a user to run a docker container within an LXD instance.

The tutorial can assume the user has already installed LXD (and link to this tutorial - https://tutorials.ubuntu.com/tutorial/tutorial-setting-up-lxd-1604)

There is more info here:
https://stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/
And a potential pitfall here:
https://discuss.linuxcontainers.org/t/docker-installation-inside-lxd-failing/254/4

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
