### ISSUE TITLE
Tutorial Wanted - customise keyboard and keybindings

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#450]
This tutorial will cover how to customise keyboard shortcuts and keybindings.

It will assume the reader has only basic desktop Linux knowledge, and will cover the process at two levels:
- at the desktop level, using Gnome as an example
- at the system level, using something like `xmodmap` and `xev` (the author can choose their preferred tools)

The following document may be useful:
https://askubuntu.com/questions/749660/how-persistently-remap-keys-in-ubuntu-16-04

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
