### ISSUE TITLE
Tutorial Wanted - install additional fonts

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#451]
This tutorial will cover how to install additional fonts:
- via a package
- manually with a downloaded 'otf` or '.ttf' file (either with a GUI or the command line, or both)

It will assume the reader has only basic desktop Linux knowledge. It may also be worth covering locally installed fonts (in a user's home directory) versus system-wide installed fonts.

The following document may be useful:
https://wiki.ubuntu.com/Fonts

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
