### ISSUE TITLE
Tutorial Wanted - Using USB devices within LXD

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#452]
This tutorial will explain how to attach a USB device to a specific LXD container.
Much of this is described in detail already in this blog post:
https://insights.ubuntu.com/2017/03/29/usb-hotplug-with-lxd-containers/

The tutorial will assume that the user has already installed LXD (you can link to this tutorial - https://tutorials.ubuntu.com/tutorial/tutorial-setting-up-lxd-1604)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
