### ISSUE TITLE
Tutorial Wanted - Install ZFS and set up a storage pool

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#454]
This tutorial will cover:

Installing the zfs software
Choosing a device to use
Using the zpool command to create a pool

**Comment by aden-chrome** [comment]
A pull request has been submitted: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/529

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
