### ISSUE TITLE
Tutorials Wanted - Set up an IRC server

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#456]
The Inspircd (http://www.inspircd.org/) is immensely popular. This tutorial would provide instructions for installing and configuring this service.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
