### ISSUE TITLE
Running an Ubuntu desktop on GCE

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#458]
This tutorial will show the user how to run a full desktop version of Ubuntu on The Google Compute Engine (https://cloud.google.com/)

The tutorial should assume the reader already has a GCE account.

It should include installing the desktop packages, setting up a vnc or remote desktop server, and configuring access for that with the GCE firewall, and finally connecting to the instance via another desktop.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
