### ISSUE TITLE
Tutorial Wanted  - allow privileged commands to run without admin password

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#459]
This tutorial will explain how to stop Ubuntu asking for your admin password when running commands that require it.

Assume the reader has basic desktop knowledge and  cover why the admin password is important, and what some of the risks may be for removing it as a requirement for certain commands.

The following document may be useful:
https://askubuntu.com/questions/159007/how-do-i-run-specific-sudo-commands-without-a-password

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
