### ISSUE TITLE
Can we add back button on mobile on tutorial page?

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#46]
google codelabs doesn't have it either but it would be really helpful to have it somewhere in navigation. If possible please discuss design with Joana

**Comment by grahambancroft** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add back button on mobile on tutorial page](https://trello.com/c/Bg2SrBCq/2447-add-back-button-on-mobile-on-tutorial-page)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
