### ISSUE TITLE
Tutorial Wanted - configure a VPN server

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#460]
This tutorial will cover the installation and configuration of a VPN server, ideally OpenVPN as this tutorial will be paired with another to configure the client.

Assume the reader has moderate Linux experience from an installation and configuration perspective, and understands what a VPN does, but may not understand the networking specifics of how a VPN works.

The following document may be useful:
https://help.ubuntu.com/lts/serverguide/openvpn.html

Here is the issue for the corresponding VPN client configuration tutorial:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/461

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
