### ISSUE TITLE
Tutorial Wanted - configure a VPN client

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#461]
This tutorial will cover the installation and configuration of a VPN client, ideally OpenVPN, as this tutorial will be paired with another to configure the server.

Configuration should be done via the desktop.

Assume the reader has moderate Linux experience from an installation and configuration perspective, and understands what a VPN does, but may not understand the networking specifics of how a VPN works.

The following documents may be useful:
https://askubuntu.com/questions/460871/how-to-setup-openvpn-client
https://help.ubuntu.com/lts/serverguide/openvpn.html

Here is the issue for the corresponding VPN client configuration tutorial:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/460

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
