### ISSUE TITLE
Tutorial Wanted - manage services with servicectl

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#462]
This tutorial will cover starting and stopping services with `servicectl` as well as adding new services, how they fit into the system configuration, and how they're removed.

Assume the user has moderate Linux experience, but no specific knowledge about _systemd_ and the breadth of its influence over modern Linux. It may be worth covering some of the differences between systemd and the old system, _Upstart_.

The following document may be useful:
https://wiki.ubuntu.com/SystemdForUpstartUsers

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
