### ISSUE TITLE
Tutorial Wanted - install a git server

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#463]
This tutorial will cover the installation and configuration of a _git_ server, as well as how clients can access the server.

Assume the reader has moderate Linux experience and needs a git server to host a few projects private on a local network. 

The following document may be useful:
https://help.ubuntu.com/lts/serverguide/git.html

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
