### ISSUE TITLE
Tutorial Wanted - setup an email server with Postfix and Dovecot (IMAP)

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#464]
This tutorial will cover the installation and configuration of an email server using Postfix as a mail transfer agent and Dovecot to provide IMAP.

As this will be a fairly advanced tutorial, it's safe to assume the reader will have good Linux server and systems experience and will understand the security and privacy ramifications of running a private email server. As such, covering domain names and MX records shouldn't be necessary although perhaps worth a mention.

The following documentation may be helpful:
https://help.ubuntu.com/community/Postfix
https://help.ubuntu.com/lts/serverguide/dovecot-server.html

Another tutorial for configuring Spamassassin has been requested:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/465

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
