### ISSUE TITLE
Tutorial Wanted - add spam filtering to an email server

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#465]
This tutorial will cover the installation and configuration of _Spamassassin_ (or perhaps _rspamd_) within a Postfix MTA environment.

As this will be a fairly advanced tutorial, it's safe to assume the reader will have good Linux server and systems experience and will understand the security and privacy ramifications of running a private email server. 

The following documentation may help:
https://help.ubuntu.com/lts/serverguide/mail-filtering.html

Extra bonus points if _Sieve_ is covered for server-side mail filtering, although this may be out of the scope of the tutorial.

A tutorial on installing and configuring Postfix has also been requested:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/464

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
