### ISSUE TITLE
Tutorial Wanted - install HTTPS/SSL with LetsEncrypt

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#466]
This tutorial will cover the installation and configuration of LetsEncrypt to provide an Ubuntu server with SSL certificates.

The reader will be a moderately experienced Linux user who may be installing and configuring web-based services for their Ubuntu server for the first time.

The following document may be useful:
https://letsencrypt.org/getting-started/

**Comment by aden-chrome** [comment]
A pull request has been submitted: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/510

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
