### ISSUE TITLE
Tutorial Wanted - configure a caching proxy

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#467]
This tutorial will cover the installation and configuration of a caching proxy, such as _Squid_, but the choice of server it up to the author.

As this will be a fairly advanced tutorial, it's safe to assume the reader will have good Linux server, networks and systems experience. It would be useful to show the before and after performance of a network request with and without the proxy.

The following documentation my be useful:
https://help.ubuntu.com/lts/serverguide/squid.html

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
