### ISSUE TITLE
Tutorials Wanted - install single-server Kubernetes with conjure-up

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#468]
This tutorial will show the user how to deploy Kubernetes on a single (well-specced!) machine, using the conjure-up spell.

The following document may be useful, although it could also be a little out of date:
https://insights.ubuntu.com/2016/11/21/conjure-up-canonical-kubernetes-under-lxd-today/

The following video also outlines Kubernetes deployment with conjure-up:
https://youtu.be/sKeHt6jgQ9g?t=1636

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
