### ISSUE TITLE
Tutorials Wanted - monitor systems using Nagios

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#469]
This tutorial will cover the installation and configuration Nagios as well as a brief overview of its capabilities.

As this will be a moderately advanced tutorial, it's safe to assume the reader will have good Linux server, networking and systems experience and will want to monitor a machines on small network perhaps for the first time.

The following document may be useful:
https://help.ubuntu.com/lts/serverguide/nagios.html

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
