### ISSUE TITLE
Tutorial Wanted - configure a Samba file server

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#470]
This tutorial will cover the installation and configuration of the Samba file server for that it can be used to share files across a LAN.

Even though Samba is often used within a corporate environment, this tutorial may be better suited to Linux-beginners who find themselves with a need to access local files from Linux, macOS and Windows machines on the same network. As such, the author shouldn't assume too much Linux or networking knowledge.

The following documentation may be useful:
https://help.ubuntu.com/lts/serverguide/samba-fileserver.html
https://help.ubuntu.com/community/Samba/SambaServerGuide

An associated tutorial as been requested on sharing a printer with Samba:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/471

**Comment by aden-chrome** [comment]
Pull request has been submitted: https://github.com/canonical-websites/tutorials.ubuntu.com/pull/519

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
