### ISSUE TITLE
Tutorial Wanted - share a printer on the network

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#471]
This tutorial will cover the process of sharing of a locally connected printer.

Assume the reader has little Linux experience and uses the desktop. The tutorial should also cover how to access the printer from other Linux machines on the network, and if feasible, macOS and Windows machines too.

The following documentation may be useful:
https://help.ubuntu.com/community/NetworkPrintingWithUbuntu
https://help.ubuntu.com/lts/serverguide/samba-printserver.html

An associated tutorial as been requested on file sharing with Samba:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/470

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
