### ISSUE TITLE
Tutorial Wanted - managing timed tasks with cron

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#472]
This tutorial will teach the reader about cron and will detail how to set up tasks which repeat at intervals.
This should include details of how the crontab file works, the format of timings, and also cover runing userlevel cron jobs (not just root).

There is some useful information on this topic here:
https://help.ubuntu.com/community/CronHowto

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
