### ISSUE TITLE
Tutorial Wanted - Setting up a Wifi Access Point

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#473]
This tutorial explains how to use Ubuntu to operate a WiFi access point.

This will cover - 
 * Checking the Wifi hardware can operate in AP mode
 * configuring the AP to share another network (e.g. Wired network)

The following references may be useful:

https://help.ubuntu.com/community/WifiDocs/WirelessAccessPoint
https://askubuntu.com/questions/762846/how-to-create-wifi-hotspot-in-ubuntu-16-04-since-ap-hotspot-is-no-longer-working
https://askubuntu.com/questions/180733/how-to-setup-an-access-point-mode-wi-fi-hotspot

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
