### ISSUE TITLE
Tutorial Wanted - Configuring Thunderbird for IMAP

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#474]
This tutorial will take the user through the process of configuring Thunderbird to fetch mail as an IMAP client. It may be useful to base this around some popular email services (e.g. hotmail or gmail), to indicate where the relevant account information can be retrieved.

The Mozilla docs on Thunderbird have some very useful detail on this:
https://support.mozilla.org/en-US/kb/imap-synchronization

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
