### ISSUE TITLE
Tutorial Wanted - install and configure LDAP

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#475]
This tutorial will cover the installation and configuration of an OpenLDAP server.

As this will be a fairly advanced tutorial, it's safe to assume the reader will have good Linux server and systems experience and will understand the security and authentication requirements of running OpenLDAP.

The following documentation may be helpful:
https://help.ubuntu.com/lts/serverguide/openldap-server.html

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
