### ISSUE TITLE
Tutorial Wanted - decoding log files

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#476]
This tutorial will cover how Linux services typically log their activities, where those logs can be found and how you might view and monitor those logs. The command line is a good default environment, but it may also be worth considering a GUI alternative for desktop users. Some details on how _systemd_ has changed things may also be useful.

It will assume the reader has only basic desktop Linux knowledge and needs to troubleshoot some hardware (such as a USB device not mounting), or understand more about how their system works.

The following documentation may be useful:
https://help.ubuntu.com/community/LinuxLogFiles

We've requested the following tutorial on monitoring your system from the desktop and the command line:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/492

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
