### ISSUE TITLE
Tutorial Wanted - install and configure Nginx

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#477]
This tutorial will cover the installation and configuration of Nginx, concluding with a basic site the reader can build upon or swap-out.

The reader will be a moderately experienced Linux user who may be installing and configuring web-based services for their Ubuntu server for the first time. Terms such as 'Virtual Hosts' should be explained.

The following document may be useful:
https://help.ubuntu.com/community/Nginx

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
