### ISSUE TITLE
Tutorial Wanted - Save, edit and Deploy Juju bundles

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#478]
This tutorial is intended to show the user how to use *bundles* with Juju (https://jujucharms.com)

The Tutorial should cover 
 - deploying a bundle from the charm store  (https://jujucharms.com/q/?type=bundle)
 - viewing the bundle using the Juju GUI      (https://jujucharms.com/docs/stable/controllers-gui)
 - Saving the bundle locally                           (https://jujucharms.com/docs/stable/charms-bundles#exporting-and-importing-bundles-with-the-gui)
 - editing the bundle file                                 (https://jujucharms.com/docs/stable/charms-bundles#creating-a-bundle)
 - redeploying the bundle. (https://jujucharms.com/docs/stable/charms-bundles#exporting-and-importing-bundles-with-the-gui)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
