### ISSUE TITLE
Tutorial Wanted - generate a Netplan configuration to use a static IP

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#479]
This tutorial will cover the process of re-configuring an Ubuntu 17.10 default Netplan DHCP configuration to use a static IP.

Assume the reader has little Linux experience and uses the desktop. As Netplan is likely to be new to the average Ubuntu user, it might be worth looking into how it differs from the previous networking configuration mechanism.

The following documentation may be useful:
https://insights.ubuntu.com/2017/07/10/netplan-by-default-in-17-10/
https://askubuntu.com/questions/972955/ubuntu-17-10-server-static-ip-netplan-how-to-set-netmask

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
