### ISSUE TITLE
[Win 8.1, ie 11] Arrows in tutorial are not clickable

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#48]
same issue on google codelabs, not sure if it can be fixed. please investigate

**Comment by WillMoggridge** [comment]
I can confirm this is still an issue.

Hopefully setting up prpl-server will help this #339

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
