### ISSUE TITLE
Tutorial Wanted - Run a script/task at startup

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#481]
It is common for users to want specific tasks or software to run at startup - though sometimes they need help deciding whether this is what they really mean! This tutorial can cover two scenarios:

 - for tasks which do need to run on system startup - adding a task to the crontab with `@reboot`
 - for task started on user login, using the `Startup Applications` helper ( https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
