### ISSUE TITLE
Tutorial Wanted - enable SSH two factor authentication

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#482]
This tutorial will cover the installation and configuration of PAM, mostly likely with the _libpam-google-authenticator_ module and associated app, to enable two factor authentication with services such as SSH login.

The reader will be a moderately experienced Linux user who understands the implications stolen passwords on an SSH-enabled server, but may not understand how two factor authentication works and safeguards against this scenario.

The following documentation may be useful:
https://askubuntu.com/questions/609117/how-to-setup-two-factor-authentication-in-ubuntu-for-ubuntu-users-using-google-a

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
