### ISSUE TITLE
Tutorial Wanted  - install and configure Nextcloud

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#483]
This tutorial will cover the installation and configuration of Nextcloud, concluding with an overview of the desktop client and its file synchronisation. Bonus points for mentioning the Android app.

The reader will be a moderately experienced Linux user who may be installing and configuring web-based services for their Ubuntu server for the first time. The reader already has Apache up and running.

We have requested a related tutorial on installing Apache which should be referenced:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/484

The following may be useful documentation:
https://nextcloud.com/install/

It may also be useful to reference the tutorial requested to install LetsEncrypt:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/466

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
