### ISSUE TITLE
Tutorial Wanted - Build a project for ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/tutorials.ubuntu.com#485]
This tutorial will take the user through the process of creating a fun or useful hardware project using a Raspberry Pi. It could be a smart mirror, it could be a media center or a local file server, the goal is to end up with something you can showcase, whether it's very useful or just fun!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
