### ISSUE TITLE
Tutorial Wanted - install and configure Roundcube

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#486]
This tutorial will cover the installation and configuration of Roundcube, concluding with an overview of the web client used to send and receive email.

The reader will be a moderately experienced Linux user who may be installing and configuring web-based services for their Ubuntu server for the first time. The reader already has Apache or Nginx installed and running, as well as Postfix and Dovecot.

We have also requested a tutorial on installing Postfix and Dovecot, which should be referenced:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/464

We have requested a related tutorial on installing Apache which should be referenced:
#484

We have requested a related tutorial on installing Nginx which can also be referenced:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/477

Finally, spam filtering is handled by another tutorial we've requested:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/465

The following may be useful documentation:
https://help.ubuntu.com/community/Roundcube

It may also be useful to reference the tutorial requested to install LetsEncrypt:
#466

**Comment by coverme76** [comment]
@degville know nothing about r-cube here, but I would [like to](https://liliputing.com/2014/06/ezeecube-small-modular-media-center-media-hub-crowdfunding.html).

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
