### ISSUE TITLE
Tutorial Wanted - install and configure WordPress

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#488]
This tutorial will cover the installation and configuration of WordPress, concluding with creating a short blog post.

The reader will be a moderately experienced Linux user who may be installing and configuring web-based services for their Ubuntu server for the first time. The reader already has Apache up and running but they'll need some help with the database

We have requested a related tutorial on installing Apache which should be referenced:
#484

The following may be useful documentation:
https://help.ubuntu.com/lts/serverguide/wordpress.html

It may also be useful to reference the tutorial requested to install LetsEncrypt:
#466

**Comment by coverme76** [comment]
also Squarespace :-)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
