### ISSUE TITLE
Tutorial Wanted - find and install some new software 

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#489]
This tutorial will cover searching for and installing one or more additional desktop applications.

Assume the reader has basic desktop knowledge and also that the reader may be from a Windows or macOS background. They may not know what packages or dependencies are.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
