### ISSUE TITLE
Tutorial Wanted - install Firefox web developer tools

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#490]
This tutorial will cover the process of installing Firefox developer tools.

Assume the reader has little Linux experience and uses the desktop but they're obviously technical enough to require web development tools.

The following documentation may be useful:
https://www.mozilla.org/en-GB/firefox/developer/
https://support.mozilla.org/en-US/questions/1166544

**Comment by Peppertop** [comment]
This tutorial is now available at https://tutorials.ubuntu.com/tutorial/firefox-for-web-developers

This issue can probably be closed now.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
