### ISSUE TITLE
Tutorial Wanted - reset your session to default

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#491]
This tutorial will cover the process of re-configuring the Ubuntu environment to its default state.

Assume the reader has little Linux experience and uses the desktop. Make sure any old configuration and data files are safely backed up if the process involves deleting or removing them (by copying their `/home` directory, for example). 

One option may be to use the `dconf reset -f /` command.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
