### ISSUE TITLE
Tutorial Wanted - monitor your system

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#492]
This tutorial will cover the process of monitoring your system, both from the desktop and from the command line.

Assume the reader has little Linux experience and uses the desktop. They may want to see which processes are using CPU, RAM and storage resources, but they won't know about Linux scheduling or process IDs.

Consider the standard System Monitor application for the desktop and a tool such as `top/htop` on the command line.

We've also requested a tutorial on closing misbehaving applications:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/447

And a tutorial on monitoring log files:
https://github.com/canonical-websites/tutorials.ubuntu.com/issues/476

The above tutorials may be good background references. The following document may also be useful:
https://askubuntu.com/questions/293426/system-monitoring-tools-for-ubuntu

**Comment by coverme76** [comment]
Like [this one](https://imgur.com/hjoROti)?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
