### ISSUE TITLE
Tutorial Wanted - backup and restore your computer

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#493]
This tutorial will cover the process of backing up and restoring the data on your system.

It will assume the reader has only basic desktop Linux knowledge, and will cover the process at two levels:

- manual backup and restoration of `/home/<username>` to external storage using _tar_
- a full system backup and restoration using a tool such as _Duplicity_

The following documentation may be useful:
https://help.ubuntu.com/community/DuplicityBackupHowto

**Comment by huertanix** [comment]
I would also like to see a similar guide using the stock backup tools available on the latest Ubuntu release.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
