### ISSUE TITLE
Tutorial Wanted - how to publish a snap

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#494]
Snaps are Linux packages you can install on a wide range of Linux distributions. They are installed from a centralized store and run in a confined sandbox.

This tutorial will take readers through the steps required to publish your own snap.

The following document may be useful:
https://docs.snapcraft.io/build-snaps/publish

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
