### ISSUE TITLE
Tutorial Wanted - Access a remote desktop

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/tutorials.ubuntu.com#495]
This tutorial will show how to use software (Remmina is the default app) to connect to a remote desktop. This should cover installing the software and using it to connect to a remote client. Two protocols are widely used, VNC and RDP
Some useful info here : https://www.remmina.org/wp/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
