### ISSUE TITLE
Tutorial Wanted - run Ubuntu desktop on Rackspace

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#496]
This tutorial will show the user how to run a full desktop version of Ubuntu on the Rackspace cloud (https://www.rackspace.com/en-gb/cloud)

The tutorial should assume the reader already has a Rackspace account and is familiar with cloud infrastructure.

It should include installing the desktop packages, setting up a vnc or remote desktop server, configuring access, and finally connecting to the instance via another desktop.

The following documentation may be useful:
https://community.rackspace.com/products/f/54/t/5784

**Comment by coverme76** [comment]
Also cachefly

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
