### ISSUE TITLE
Tutorial Wanted - partition storage with LVM and add a new drive

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#497]
This tutorial will cover:

- storage partitioning with LVM via the Ubuntu desktop installer
- briefly installing the remainder of the system
- adding a new drive

The above can be done within a virtual machine using VirtualBox or _libvirt_/_KVM_:
https://help.ubuntu.com/community/VirtualBox
https://help.ubuntu.com/community/KVM/Installation

Assume the reader has moderate Linux experience and uses the desktop. This will be their first experience with LVM and they'll need to be told its terms and concepts.

The following documentation may help:
https://askubuntu.com/questions/458476/adding-disks-with-lvm
https://wiki.ubuntu.com/Lvm

**Comment by gabefair** [comment]
I would like this as well! Thanks for opening a ticket

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
