### ISSUE TITLE
Tutorial Wanted - how to use LibreOffice

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/tutorials.ubuntu.com#498]
This tutorial will cover installing and accessing the various components of the LibreOffice suite.

It may be useful to outline the procedure for opening a Word document, making changes, and exporting the file as a Word document that can be shared with users of Microsoft's software.

Assume the reader has basic desktop knowledge and also that the reader may be from a Windows or macOS background looking for a free alternative to proprietary software.

The following documentation may be useful:
https://wiki.ubuntu.com/LibreOffice

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
