### ISSUE TITLE
Tutorial Wanted - APT caching/proxy server

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/tutorials.ubuntu.com#499]
How to set up an APT caching/proxy server (e.g. apt-cacher-ng) in the context of an internet-deprived network. The main objective is to give clients the ability to install Ubuntu packages when the internet is not available. Allowing just the proxy server to access the internet can be an option but should not be necessary if properly prepared.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
