### ISSUE TITLE
Implementation of a language switcher

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/tutorials.ubuntu.com#509]
There has been an increase of interest in having localized versions of tutorials. Currently, the website doesn't support language-based filtering, but design proposals and implementation of a language switcher would be a welcome addition.

Until we have such a site-wide switcher or filter, localized tutorials should have a `hidden` tag (which will effectively hide them from the default view) and links to them may be surfaced to users through an admonition, box or note (this issue will be updated with a proposal for the design of this component) in their respective 'en' tutorials.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
