### ISSUE TITLE
Tutorial Wanted - Using pulseaudio/alsamixer etc

### ISSUE THREAD

**Issue by xSkyeX** [canonical-web-and-design/tutorials.ubuntu.com#520]
I think that tutorial for configuration sound devices etc. can be helpful for users.

Something helpful: https://wiki.archlinux.org/index.php/PulseAudio/Configuration

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
