### ISSUE TITLE
Tutorial Wanted - Crontab usage.

### ISSUE THREAD

**Issue by xSkyeX** [canonical-web-and-design/tutorials.ubuntu.com#521]
It will be good to see how to use crontab in official tutorials of ubuntu, now it's only in community tutorials.

Helpful link: https://help.ubuntu.com/community/CronHowto

**Comment by mridubhatnagar** [comment]
Hi, 
I recently explored crontab. Would love to contribute to this.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
