### ISSUE TITLE
Tutorial Wanted-Encrypting files and folders

### ISSUE THREAD

**Issue by Tanesh1701** [canonical-web-and-design/tutorials.ubuntu.com#524]
How to encrypt files and folders. The main objective is that the user needs to be able to protect his files and folders with a password.

It will be useful to outline any software that needs to be downloaded from the terminal.

You  may assume that the user has basic desktop knowledge.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
