### ISSUE TITLE
Tutorials only in English?

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#525]
Tutorials must be created only in English?

**Comment by caldav** [comment]
Yes, for two reasons: 

1. we don't fully have the infrastructure to help people filter tutorials in their own language
1. we require a certain level of review and QA before a tutorial gets published and we don't have the resources to handle reviewing many languages

But we are considering some options to make this possible.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
