### ISSUE TITLE
Language Setup Tutorial Might be a Really Good Idea... #GoogleCodeIn

### ISSUE THREAD

**Issue by jpoly1219** [canonical-web-and-design/tutorials.ubuntu.com#526]
Hey guys, I am a participant of the Google Code-In Contest. This task was about submitting a tutorial recommendation.
I think one of the most important tutorials is the language setup. Sure, there is already a language/keyboard setup in the installation process, but this is something different:

I type in English mainly, but I also type very frequently in Chinese, Korean, and Japanese. The problem is that I need to go through extensive setup process to be able to use these languages, because they require support for special characters. Seasoned Ubuntu users would have no problem installing ibus-hangul or sunpinyin, but I remember as a beginner, I had very big trouble trying to figure out how to install the languages, because the default setup during the installation process wouldn't do. I am a Korean myself, and I know a lot of Ubuntu users who are Chinese and Japanese. I think adding a tutorial on how to add support for languages with special characters on tutorials.ubuntu.com would not only make the lives of people like me much easier, but also increase some market share in countries around Asia. 

The tutorial might include how to use different key input systems such as fcitx or ibus (I personally favor fcitx more due to its ease of installing languages). Then maybe a terminal command for installing language packs and logging in/out. I use Ubuntu MATE for this reason, because they have the option to install Chinese, Korean, and Japanese input with a single click. But for Ubuntu, I think a good tutorial would do.

Just a suggestion! :D

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
