### ISSUE TITLE
[Create a bootable USB stick on Windows] Installing to one partition

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#530]
In the tutorial, you use Rufus. However, Rufus can't install onto a single partition, which is required for some people (including what I'm doing).

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
