### ISSUE TITLE
Tutorial Wanted – Run Android apps with Anbox

### ISSUE THREAD

**Issue by mkljczk** [canonical-web-and-design/tutorials.ubuntu.com#531]
Tutorial for using [Anbox](https://anbox.io) would be very useful.
Anbox is distributed as snap package.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
