### ISSUE TITLE
Tutorial Wanted – Configure lightweight Xorg/Wayland session for maximizing performance

### ISSUE THREAD

**Issue by mkljczk** [canonical-web-and-design/tutorials.ubuntu.com#532]
Running lightweight environment from session manager is great way to save some memory and making OS faster. It is useful especially for gaming and other performance-heavy tasks.
The tutorial should explain how to create session file running lightweight window manager (openbox or xfwm4) and something like task switcher (rofi allows both to run applications and switch between tasks). It should explain what background professes would be important for users (power managers etc.) and how to automatically start them.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
