### ISSUE TITLE
Tutorial Wanted – Configure Wine and run Windows applications

### ISSUE THREAD

**Issue by mkljczk** [canonical-web-and-design/tutorials.ubuntu.com#533]
There should be tutorial about configuring WineHQ to run Windows applications.
It should explain the differences between using VM and Wine, differences between wine-staging and wine, how to create 32-bit prefix, change wine settings, use winetricks and troubleshoot the most common problems.

**Comment by coverme76** [comment]
I have that, in my "Install and remove Software app."

https://imgur.com/iZ5eZuI
https://imgur.com/xSeEhGV
https://imgur.com/I2TLIsN
https://imgur.com/KfMUMv9

**Comment by m4sk1n** [comment]
@coverme76 I haven't asked you about it… -_-

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
