### ISSUE TITLE
Tutorial Wanted – Secure against brute Force attacks with fail2ban

### ISSUE THREAD

**Issue by mkljczk** [canonical-web-and-design/tutorials.ubuntu.com#545]
Title is self-explanatory, this tutorial should cover installation and configuration of `fail2ban` to secure server/SSH connection from brute-force attacks.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
