### ISSUE TITLE
Tutorial Wanted – Configure VNC server

### ISSUE THREAD

**Issue by mkljczk** [canonical-web-and-design/tutorials.ubuntu.com#546]
This tutorial should cover installation and configuration of VNC server (tight, tiger, vnc4server…), it should include paragraph about differences between VNC and RDP.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
