### ISSUE TITLE
Tutorial Wanted – Terminal usage and most common commands

### ISSUE THREAD

**Issue by mkljczk** [canonical-web-and-design/tutorials.ubuntu.com#547]
This tutorial should cover most useful shortcuts in shell, most useful commands, pipes and other basics of terminal usage. It shouldn't assume that person reading it already has some experience in terminal usage.
Some tutorials assumes that (s)he already has some terminal experience.

**Comment by Peppertop** [comment]
I'm currently working on this tutorial, and hope to have something available soon.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
