### ISSUE TITLE
Tutorial Wanted – Basics of Bash scripting

### ISSUE THREAD

**Issue by mkljczk** [canonical-web-and-design/tutorials.ubuntu.com#548]
This tutorial should cover basics of Bash scripting, it should assume knowledge of Bash from #547, it would cover loops, functions, parameters, variables and if statements, maybe switch statements too.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
