### ISSUE TITLE
[Install Kubernetes with conjure-up] <please add a title>

### ISSUE THREAD

**Issue by katariganeshkumar** [canonical-web-and-design/tutorials.ubuntu.com#549]
<error: cannot communicate with server: Post http://localhost/v2/snaps/conjure-up: dial unix /run/snapd.socket: connect: no such file or directory>

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
