### ISSUE TITLE
[Snap a Python application] Add solution to GLIBC problem on 17.10

### ISSUE THREAD

**Issue by daniellimws** [canonical-web-and-design/tutorials.ubuntu.com#550]
Currently due to difference in GLIBC versions on Xenial and Artful, the following error will be given when trying to create snaps in Artful.

```
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by python3)
```

Known solutions to this are to either do `snapcraft cleanbuild` or use [per project containers](https://forum.snapcraft.io/t/per-project-containers/388).

Ideally this should be added for Artful users to prevent confusion.

**Comment by michaldev** [comment]
+1

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
