### ISSUE TITLE
Build a nodejs service snap, section 4, subtitle Debugging denials tools

### ISSUE THREAD

**Issue by rpcme** [canonical-web-and-design/tutorials.ubuntu.com#552]
https://tutorials.ubuntu.com/tutorial/build-a-nodejs-service#3

The second command works fine, does not throw error. It is a copy/paste error between the second and third commands.

**Comment by Oglomuntonido** [comment]
On page: https://tutorials.ubuntu.com/tutorial/build-a-nodejs-service#2

This sentence is confusing:
_Before exposing your server as a service, we strongly recommend you to declare it as a simple snap application._
The tutorial doesn't give any clue how to do that.

Following on that page the rebuilding process does generate errors (Ubuntu Core) that aren't described in tutorial: **FileNotFoundError: [Errno 2] No such file or directory: '/home/mb5r5/snap-src/chuck-norris-webserver/prime/bin/chuck-norris-app'**
Seems like there is a missing step in the tutorial.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
