### ISSUE TITLE
Tutorial Wanted - Asking for help

### ISSUE THREAD

**Issue by mon23c** [canonical-web-and-design/tutorials.ubuntu.com#553]
As we know,when we use ubuntu,sometimes there's some problems that can't be solved by reading tutorial.
Then it would be nice to create new tutorial about how to ask for help in Ubuntu community and how to speak properly in order to avoid miscommunication between new and old users.

**Comment by coverme76** [comment]
hav you tried Google+ ?

https://wiki.ubuntu.com/Social

**Comment by mon23c** [comment]
Nope.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
