### ISSUE TITLE
error: cannot find snap "nethack": snap not found

### ISSUE THREAD

**Issue by fad0** [canonical-web-and-design/tutorials.ubuntu.com#562]
I am trying to do the "Advance snap usage" tutorial and when I run "snap download nethack" I get the error shown in the title.  I tried to "snap find" "tutor" and "net" and didn't see anything that could be a replacement.

**Comment by caldav** [comment]
Hi and thanks for the report, what's your architecture? AFAICT, the [nethack](https://uappexplorer.com/snap/ubuntu/nethack) snap has only been released for 64-bit machines, which could be why you are not finding it.

The tutorial should definitely be fixed to use a snap supported on - at least - i386 and armhf too.

**Comment by fad0** [comment]
Thanks for the quick reply.  I am using ubuntu core on RaspberryPi 2 and 3 - armhf.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
