### ISSUE TITLE
Tutorial Wanted:-How to add Own made programs in Ubuntu

### ISSUE THREAD

**Issue by anuag** [canonical-web-and-design/tutorials.ubuntu.com#566]
Hey guys, I am a participant of the Google Code-In Contest. This task was about submitting a tutorial recommendation.
I think one of the most important tutorials is how to add programs in our Ubuntu System.
As we know that Ubuntu is an Open Source Operating System, so therefore we can add some programs to it or make some changes in it, to make it work as per our will. At last Ubuntu is a version of Lunix Operating System, an Open Kernel Operating System.

**Comment by m4sk1n** [comment]
Do you mean just packaging apps and creating entries for them in applications menu? Ubuntu has [great resource explaining packaging software](http://packaging.ubuntu.com).

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
