### ISSUE TITLE
Update page descriptions

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/tutorials.ubuntu.com#57]
The homepage description is "Ubuntu tutorials!" and there is none on the tutorial pages. We should do a better job of describing the page.

**Comment by WillMoggridge** [comment]
The functionality has been added to manage this but this needs some improvement on the homepage.

The code can currently update it with:
``` javascript
this.fire('app-metadata', {
  title: 'Ubuntu tutorials',
  description: '...',
});
```

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
