### ISSUE TITLE
Create your first snap - highlight Ubuntu Core specific steps

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/tutorials.ubuntu.com#573]
[This tutorial](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#1) recommends installing the `classic` snap on Ubuntu Core to develop snaps on target. While this is accurate, a better distinction should be made between Ubuntu Core and Ubuntu classic content to avoid confusion (eg. #377). 

The Ubuntu Core section should either be moved to a dedicated step or highlighted as an admonition.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
