### ISSUE TITLE
installation and installation media creation tutorials to not mention verification

### ISSUE THREAD

**Issue by wxl** [canonical-web-and-design/tutorials.ubuntu.com#575]
There's a lovely [verification][1] tutorial that ensures the integrity of the download. As the [installation tutorial][2] suggests an http download, it would only make sense that it would refer to this, at the least through the various installation media creation tutorials (e.g. the [one for Ubuntu][3]).

[1]: https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu
[2]: https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop
[3]: https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
