### ISSUE TITLE
verification of installation media needed

### ISSUE THREAD

**Issue by wxl** [canonical-web-and-design/tutorials.ubuntu.com#576]
The two biggest problems that occur when installing media are:
 1. Download errors, which the [verification tutorial][1] solves
 1. Copy errors, which can be verified one of two ways:
     1. pre-boot with the likes of `dd` (see useful script [here][2])
     1. post-boot at the GRUB menu ("check disc for defects")

However, neither of these are mentioned anywhere in either the various installation media creation tutorials, nor in the installation tutorial. 

[1]: https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu
[2]: https://help.ubuntu.com/community/HowToMD5SUM#Check_the_CD

**Comment by evilnick** [comment]
That's a good point and we'll address it in #702 when we update the tutorial. Thanks!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
