### ISSUE TITLE
[Create a bootable USB stick on macOS] <please add a title>

### ISSUE THREAD

**Issue by Perke17** [canonical-web-and-design/tutorials.ubuntu.com#605]
This just creates the installer USB. Is there an easy way to install this to a USB so that I can just run Ubuntu from a USB, other than installing it to the ol' USB?????????????   ??? ?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
