### ISSUE TITLE
[Install Ubuntu on Windows 10] Does Ubuntu share the Windows Command Prompt Shell Window always?

### ISSUE THREAD

**Issue by osregal** [canonical-web-and-design/tutorials.ubuntu.com#606]
Since the Windows Command Prompt shell is now an Ubuntu Linux shell, how do I exit from Ubuntu and get back to the Windows Command Prompt shell? Thanks!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
