### ISSUE TITLE
[Create a bootable USB stick on Ubuntu] startup disk creator does not create bootable usb stick

### ISSUE THREAD

**Issue by 111mo89** [canonical-web-and-design/tutorials.ubuntu.com#620]
concerning the tutorial https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu#0

tested under ubuntu 16.04 lts 64bit:
creation of bootable startup medium via startup disk creator failed. could not boot with resulting usb stick.

used iso file:
ubuntu-gnome-16.04.3-desktop-amd64.iso

it worked fine by using LinuxLive USB Creator for windows

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
