### ISSUE TITLE
using "sudo" before commands

### ISSUE THREAD

**Issue by nexiun** [canonical-web-and-design/tutorials.ubuntu.com#625]
In this tutorial: https://tutorials.ubuntu.com/tutorial/basic-snap-usage  some examples use "sudo" before a command and some don't. While this is explained in the first two lines when running the terminal, I think it is pretty easy to just run a command and miss that(I missed it), so adding a short note in the tutorial explaining the "sudo" before a command and perhaps when to use it would be a good idea.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
