### ISSUE TITLE
Upgrade Ubuntu desktop updat package broken?

### ISSUE THREAD

**Issue by Linas08** [canonical-web-and-design/tutorials.ubuntu.com#628]
<describe the issue>

**Comment by Linas08** [comment]
trying to upgrade ubuntu i see Update software is available so i click install and i get "The package system is broken"
i also downloaded the ISO but how to run i mounted the iso i dont find any executable?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
