### ISSUE TITLE
LXD tutorial for ubuntu

### ISSUE THREAD

**Issue by Aayush890** [canonical-web-and-design/tutorials.ubuntu.com#630]
![screenshot from 2018-01-15 13-19-51](https://user-images.githubusercontent.com/34772342/34944337-16994ae4-f9f7-11e7-986e-4a28a6b8c7d1.png)

in the whole tutorial it doesn't mention LCX and suddenly it tells to use LCX and the outcome was "permission denied, are you in the LXD group?"

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
