### ISSUE TITLE
Setting up LXD on Ubuntu Tutorial- Issue

### ISSUE THREAD

**Issue by tel0** [canonical-web-and-design/tutorials.ubuntu.com#633]
An issue I came across while completing the LXD Ubuntu Tutorial was when adding your user to the lxd group using the "newgrp lxd" command. There is little explanation as to why this command is necessary to the proper installation of lxd. Adding a brief description of the significance of the "newgrp lxd" command and how it will be used/what it will create for the user would be beneficial in further comprehending this tutorial.
![image](https://user-images.githubusercontent.com/35534703/35055545-73913892-fb7d-11e7-97c2-e9a4e1090013.png)

-Harry21 (Google Code-in)

**Comment by tel0** [comment]
Another issue I've come across:
While setting up lxd (after command "sudo lxd init"), directions as to choose yes/no on the first question displayed "Do you want to configure a new storage pool? (y/n)" are not provided within the tutorial. Img is attached below showing this discrepancy.
![image](https://user-images.githubusercontent.com/35534703/35056747-b770f8b0-fb80-11e7-8c41-cce9156b1d20.png)

**Comment by thizmo** [comment]
The main problem, at least with 16.04.4 was that lxd ist already installed. With version 2.0.11.
```bash
lxd --version / lxc --version
```

I had to "switch" upfront from ppa lxd to snap lxd. 
This helpfull article explained it: https://blog.simos.info/how-to-migrate-lxd-from-deb-ppa-package-to-snap-package/
So there is the line missing, how to switch from lxd ppa to lxd snap:
```bash
lxd.migrate 
(after snap installed).
```
 
And then the documetation is totally right. 
Please fix it in the tutorial, as it has cost me some time to figure that out.

Thx,

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
