### ISSUE TITLE
[How to burn a DVD on Windows] <please add a title>

### ISSUE THREAD

**Issue by arminfeb** [canonical-web-and-design/tutorials.ubuntu.com#635]
hi ! i have problem with dvd 
after i burned it and restart my computer nothing hapening 
my windows just running normal and ubuntu instalation doesnt running.

**Comment by m4sk1n** [comment]
Hello, have you configured BIOS/UEFI to boot from DVD?

**Comment by arminfeb** [comment]
Yes i did

**Comment by evilnick** [comment]
does your BIOS give you a boot menu? It varies according to manufacturer, but usually holding down f10 when booting will give you a list of boot devices you can choose between

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
