### ISSUE TITLE
Tutorial fails due to missing resolv.conf

### ISSUE THREAD

**Issue by ChrisOfBristol** [canonical-web-and-design/tutorials.ubuntu.com#640]
chris@Dell-DXP051:~$ sudo classic
Creating classic environment
Parallel unsquashfs: Using 2 processors
12189 inodes (13511 blocks) to write

[========================================================================/] 13511/13511 100%

created 9635 files
created 1469 directories
created 2465 symlinks
created 79 devices
created 0 fifos
cp: cannot stat '/run/resolvconf/resolv.conf': No such file or directory
chris@Dell-DXP051:~$

**Comment by popey** [comment]
As discussed https://forum.snapcraft.io/t/tutorial-fails-due-to-missing-file/3717 it would probably make sense to split the first tutorial into two. One for people on Ubuntu Core and one for people on Ubuntu Classic systems.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
