### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by ericdunbar** [canonical-web-and-design/tutorials.ubuntu.com#641]
The instructions work, however, it would be nice to have persistence be an easy-to-access option. For example, UNetBootin can create a persistent live USB. It may not be as fast as rufus but at least the persistence is an option.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
