### ISSUE TITLE
Can't build tutorials

### ISSUE THREAD

**Issue by viktorrobin** [canonical-web-and-design/tutorials.ubuntu.com#644]
Hi,

I've been trying to run the following command to generate static version of the tutorials locally unsuccessfully.

I've tried with docker (`./run` file) and without Docker directly with yarn but keep getting the same result.

In both case it creates a `build/` directory but `index.html` has no content apart from the background picture.

Am I missing something?

**Comment by caldav** [comment]
Any sign of an error in the `./run` output?

Try `./run serve tutorials`.

It should end on a line similar to this one: "2018/01/30 15:30:13 Serving on http://localhost:8016"

Then, go to http://localhost:8016 to see if tutorials are present.

**Comment by viktorrobin** [comment]
This part works just fine. The issue is when I want to generate a static version.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
