### ISSUE TITLE
Add /r/crouton to Chromebook tutorial Next Steps

### ISSUE THREAD

**Issue by andmalc** [canonical-web-and-design/tutorials.ubuntu.com#648]
I suggest adding this sub under Next Steps on the last page of the Chromebook tutorial:

https://www.reddit.com/r/Crouton/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
