### ISSUE TITLE
Create the Raspberry Pi starter kit

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/tutorials.ubuntu.com#649]
The Raspberry Pi starter kit is a suite of tutorials matching the following criteria:

* Are for beginners or are accessible to beginners willing to write some code
* Are no longer than 1h
* Take the reader through an engaging project with a usable output
* Run on Raspberry Pi 2 or 3
* Do not require expensive sensors or components
* Run on Ubuntu Core

## Suggestions

* Cheap smart display/mirror
* WiFi access point (#473)
* Motion sensing camera
* ...

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
