### ISSUE TITLE
add warning "bootable usb stick looses files previously in usb" (if there are any)

### ISSUE THREAD

**Issue by spinagiu** [canonical-web-and-design/tutorials.ubuntu.com#652]
Hello, this may seem obvious... but obvious things are the most difficult to know when you are completely unfamiliar with a topic.
Since not all programs for burning iso files warn that burning an iso file on usb stick will completely reset it, it would be useful to specify in the tutorial that the USB stick needs to be empty, otherwise previously existing files will be removed. 
it is stated in the tutorial that previous partitions will be erased, but "previous files erased"... is a much more alarming and understandable warning for an inexperienced user :)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
