### ISSUE TITLE
Tutorial wanted - How to create a snap of a basic bash script + information about permissioning bash scripts to run

### ISSUE THREAD

**Issue by thanders** [canonical-web-and-design/tutorials.ubuntu.com#653]
Please write a tutorial to package a basic bash script using snapcraft. This should include:
-  Creating a basic bash script (eg. hello world or whatever)
- Package it using snapcraft.io
-  Basic information about configuring snapcraft and bash scripts in general so that they can be run by an end-user once they have been packaged

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
