### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by hisecu** [canonical-web-and-design/tutorials.ubuntu.com#655]
Much is based on the assumption that rufus is working fine. Mentioning the fact that there are alternatives if one has issues with rufus might be helpful for beginners, e.g. mentioning one specific alternative or referring to https://alternativeto.net/software/rufus/?platform=windows

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
