### ISSUE TITLE
Some system require instalation USB to use GPT for UEFI partition scheme

### ISSUE THREAD

**Issue by adamnilsson** [canonical-web-and-design/tutorials.ubuntu.com#656]
The tutorial gives specific options for partition scheme. At least for some systems such as my Lenovo T470s with Windows pre installed with GPT scheme, I was not able to install or boot from the USB until I came across an advice that the schemes between USB and HDD must match and then recreated the USB stick with GPT for UEFI.  

> For best compatibility with newer hardware, keep the Partition scheme and target system type set as MBR partition scheme for UEFI. However, if you need to use the USB stick with older hardware, change this to MBR Partition Scheme for BIOS or UEFI.

Should also mention that some systems installed on GPT disks may require the USB to use GPT.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
