### ISSUE TITLE
[Install Ubuntu desktop] Unable to boot after installation

### ISSUE THREAD

**Issue by HammerHead83** [canonical-web-and-design/tutorials.ubuntu.com#657]
When installation ended, installer ask to eject installation media and reboot system. After rebooting installed system doesn't start. GRUB rescue load.
P.S. I have 4 OS's installed on my computer and don't want to use "Automatic (erase) partitioning". Partitions comes from Debian 9 OS, which I dropped before.
Thanks.

**Comment by MrDiamond123** [comment]
Sorry, this is the wrong place to report problems. This is for problems with the TUTORIALS themselves.

Sorry about your problem. Try https://askubuntu.com or https://ubuntuforums.org/ to see if they can help fix it

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
