### ISSUE TITLE
[Upgrade Ubuntu desktop] The steps are incomplete

### ISSUE THREAD

**Issue by segova** [canonical-web-and-design/tutorials.ubuntu.com#659]
I have Ubuntu 12.04, I want to upgrade the distribution: I follow the steps but it does not work, because there are some packages unavailable.

**Comment by MrDiamond123** [comment]
You have such a old Ubuntu that upgrading might be hard, so backup your data and reinstall Ubuntu.

It might let you install the upgrade but some parts of the older upgrade system might break the new version (The tutorial assumes you been keeping up to date)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
