### ISSUE TITLE
[Install Ubuntu Desktop] Images need to be updated

### ISSUE THREAD

**Issue by MrDiamond123** [canonical-web-and-design/tutorials.ubuntu.com#661]
The images are of the older version of Ubuntu (which uses Unity) instead of the current Ubuntu w/ GNOME

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
