### ISSUE TITLE
Etcher cannot be run on every macosX

### ISSUE THREAD

**Issue by ccciolll** [canonical-web-and-design/tutorials.ubuntu.com#668]
at page https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#3 you say to use Etcher for creation a bnootable USB on a mac.
You must knoxw Etcher is not compatible on some not-so-old macosX version (as Snow leo or lion) and there is no alternative (and no alert about that) on Etcher website.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
