### ISSUE TITLE
If you are blocked on a tutorial, there is no obvious place for support

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/tutorials.ubuntu.com#67]
One solution would be a link in the left pane, to https://developer.ubuntu.com/core/troubleshooting
Other ideas?

**Comment by magdalena-mirowicz** [comment]
@pmahnke please advise

**Comment by pmahnke** [comment]
What kind of blocked are you?  The troubleshooting page is for everything.

I noticed that conjure-up.io has something about 'Chat with conjure-up devs on freenode' ... but if you are just generally blocked, then troubleshooting is fine, perhaps with a link like [Having problems?](/core/troubleshooting)

**Comment by nottrobin** [comment]
I love the idea of sending people to Freenode (https://webchat.freenode.net/) when there's an appropriate channel. It's a massively helpful & under-used resource for devs. Or Slack, I believe that's what the cool kids are using these days.

**Comment by caldav** [comment]
* @pmahnke I like the idea of having two links, one to chat, one for troubleshooting. 
* @nottrobin I was about to say #snappy on freenode, but that wouldn't been relevant for all tutorials and as far as I know, we don't have a place with enough people, that would be generalist enough to point all readers to. Maybe we could use tutorials metadata (from the docs) to let authors provide a "support_channel" entry, that would be used when present, maybe with a fallback to something reasonable like #ubuntu-app-devel ?

**Comment by nottrobin** [comment]
Yep that sounds like a good solution to me.

**Comment by evilnick** [comment]
Can we just add this to the metadata for now, so people can add even if it isn't currently shown?

**Comment by nottrobin** [comment]
@evilnick So do you think a `support_url` metadata key makes sense? If @caldav and @WillMoggridge agree then I would say we could go ahead and start including that in metadata. Thoughts @WillMoggridge?

**Comment by caldav** [comment]
+1

**Comment by evilnick** [comment]
I think we might also want to think about the format of that, maybe supporting pairs of values or a list (e.g. so we can specify the display text for a link)
what about :

      support_url: irc://freenode.ned/snappy

and 

      support_url: 'Join us on irc':'irc://freenode.net/snappy'

and

      support_url: 'Join us on irc':'irc://freenode.net/snappy'
                   'Ask a question':'https://askubuntu.com/questions/ask'

(n.b. not sure if the metadata format used in tutorials supports lists)

**Comment by caldav** [comment]
Since it's supposedly YAML, it should: (eg. https://middlemanapp.com/basics/frontmatter/)

**Comment by WillMoggridge** [comment]
I believe we talked about this but I didn't reply here, sorry.

To confirm, this sounds good to me. And it does indeed support lists.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
