### ISSUE TITLE
[Basic snap usage] Couple issues

### ISSUE THREAD

**Issue by chartre** [canonical-web-and-design/tutorials.ubuntu.com#670]
Running Ubuntu 14.04.1 here, but not up-to-date (kernel 4.4.0-116)
1º Step 3rd, section "Install and execution"
When first installed the "hello" snap, it didn't run. Instead, a suggestion of "in which packages can be find" appeared (of course, none of the options is the snap).
It worked after a reboot. So, maybe, you can put a note for the case that happens to the people.
2º Step 4th, section "Snap can also host services"
The snap "shout" can't be installed because seems to not be available so, this feature, cannot be tested.
3º Step 5th, section "Switching channel for installed apps"
I'd suggest to put the last codeblock into a "note-block". Because seems that is a note.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
