### ISSUE TITLE
[Create a bootable USB stick on Ubuntu] <please add a title>

### ISSUE THREAD

**Issue by monomente** [canonical-web-and-design/tutorials.ubuntu.com#677]
The bootable USB only allows for install not recovery. How is it used for system recovery?  Nice to know this.

**Comment by coverme76** [comment]
Secondly, as a non-monarchist I _cannot_ install ANY operating system using this method,

until the [offending image](https://tutorials.ubuntu.com/es6-bundled/src/codelabs/tutorial-create-a-usb-stick-on-ubuntu/img/efddbd492b5c85c2.png) is removed.

**Comment by osergioabreu** [comment]
They should say "A clean (unformatted) USB stick"

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
