### ISSUE TITLE
Update needed for "Create KVM Pods with MAAS" networking section

### ISSUE THREAD

**Issue by burnbrigther** [canonical-web-and-design/tutorials.ubuntu.com#679]
On this page:
https://tutorials.ubuntu.com/tutorial/create-kvm-pods-with-maas#6

This section mentions:
Return to the "Subnets" tab, select the "untagged" VLAN next to the 192.168.30.0/24 subnet and from the "Take action" drop down menu on the top right, choose "Provide DHCP". Confirm that the autodetected info is correct ("Rack controller" name, "Gateway IP" and "Subnet") and accept the configuration.

The problem is, more specific information should be given to the "Gateway IP" as it defaults to a specific value which does not follow the format of the tutorial (192.168.30.254).  This cost me many hours of troubleshooting.  Since the networking section suggests 192.168.30.1 as the Maas region controller, that too should be the default gateway.  I suggest the following amendments:

Return to the "Subnets" tab, select the "untagged" VLAN next to the 192.168.30.0/24 subnet and from the "Take action" drop down menu on the top right, choose "Provide DHCP". Confirm that the autodetected info is correct.  In many cases, it may require updating: "Rack controller" name (default DNS allocation name is usually suitable), "Gateway IP" (192.168.30.1), "Subnet" (192.168.30.0/24) and accept the configuration.

Thanks for your attention on this.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
