### ISSUE TITLE
"Run Linux containers on Windows" uncler and outdated 

### ISSUE THREAD

**Issue by AndisGrossteins** [canonical-web-and-design/tutorials.ubuntu.com#685]
1) Link for downloading Docker on step 2 now redirects to https://mobyproject.org/, which is not where Docker for windows can be downloaded.
2) Instructions on step 4 about downloading Ubuntu docker image are a bit confusing. Doesn't `docker pull ubuntu` download the needed image?
3) Suggestion to install containers under C:\Program Files\ should not be recommended. There is a good reason users are not allowed to modify that directory. The created directory is not even used in the latter parts of the tutorial.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
