### ISSUE TITLE
Tutorial for a mono GTK application

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#687]
Pleas make a tutorial to generate a snap for a  compiled mono C#  GTK GUI application.

**Comment by evilnick** [comment]
sounds good! Thanks for the suggestion

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
