### ISSUE TITLE
Tutorial request - Install Ubuntu as a dual boot

### ISSUE THREAD

**Issue by Complainer** [canonical-web-and-design/tutorials.ubuntu.com#689]
I have just looked through your tutorial called "Install Ubuntu desktop."  It is well-intentioned but so oversimplified as to be misleading, even dangerous. It would be of interest mainly to new users of Ubuntu. They will in most cases want to install Ubuntu ALONGSIDE  Windows. Following the steps of this tutorial, however, will, if it works, WIPE OUT AND UTTERLY DESTROY WINDOWS!
 
What is needed is a tutorial on how to install Ubuntu ALONGSIDE Windows. That is significantly more complicated. The procedure is explained (for Ubuntu 16.04 alongside Windows 10) at https://help.ubuntu.com/community/installation .  There you will see that some of the matters that need to be dealt with before starting the Ubuntu installation program are:
Making a bootable Ubuntu DVD, also called a LiveDVD
Editing the computer's UEFI to change the boot order
Deciding how to shrink the Windows C drive to make room for Ubuntu.
Possibly using Windows disk management to shrink the C drive or turning off Windows updates.

Within the Ubuntu installation program one must either:
Create a new drive, if Windows disk management has been used,
or
Use GParted to divide the disk.

All of this needs to be carefully explained in the tutorial. The present tutorial explains none of it and just wipes out Windows with little warning. I think it is a hazard, will only create ill will towards Ubuntu, and should be removed immediately. I hope it will then be replaced by a safe and comprehensive tutorial. But I am not the person to write it.

**Comment by sonoro1234** [comment]
>Tutorial request - simply how to run ubuntu on a pc from a flash drive (and choose unity desktop if possible)

This would be another topic, I am most interested in installing as dual boot

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
