### ISSUE TITLE
Keyboard accessibility - preserve scroll position on page transitions

### ISSUE THREAD

**Issue by abitrolly** [canonical-web-and-design/tutorials.ubuntu.com#693]
When moving from page to page with left/right keys. scroll position jumps back to the beginning of the page. For user experience preserving position on each page is better until tutorial closes. This allows to conveniently switch back and forth for reference.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
