### ISSUE TITLE
[How to verify your Ubuntu download] The pages need to point to the appropriate version

### ISSUE THREAD

**Issue by lukeswr** [canonical-web-and-design/tutorials.ubuntu.com#694]
When I downloaded the 17.10.1 server, the second page of the instructions (namely the sha256sums) were pointed to the 16.04 LTS sums. I did a google search and found a mirror site to check the sums.

The instructions need to point to the relevant version of the ISO download.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
