### ISSUE TITLE
Issues With Tutorial: Create a bootable USB stick on macOS

### ISSUE THREAD

**Issue by ClosetCoder** [canonical-web-and-design/tutorials.ubuntu.com#695]
**Issues:**

- Under section '(2) Requirements', there is no mention of the application Etcher. Yet, the only option for creating a bootable USB on macOS per this specific tutorial, is with this piece of software, therefore making it a requirement.
- Under section '(4) Install and run Etcher', it should be noted that if you are running an application firewall, a hole should be burned in said firewall to compensate for Etcher's rather obtrusive, and unquenchable thirst to reach out to about half a dozen internet sites upon simply starting. For blocking any one of those requests, will produce errors within the application.
- Under section '(5) Etcher configuration', a 'Warning' should be added at the bottom of the page similar in style to that of section (3), to once again iterate that Etcher will produce errors unless it is allowed uninhibited access to the internet, OR unless it is used on an entirely offline system.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
