### ISSUE TITLE
[Install single-server OpenStack with conjure-up] Tutorial not working

### ISSUE THREAD

**Issue by buzanits** [canonical-web-and-design/tutorials.ubuntu.com#698]
If you exactly follow the tutorial at https://tutorials.ubuntu.com/tutorial/install-openstack-with-conjure-up#2 in a fresh Ubuntu 16.04 VM, all the options in screenshot 2 incluing "localhost" are disabled and cannot be selected.

Can it be a problem running that inside a Virtualbox VM? Does this only work on iron?

[conjure-up.log](https://github.com/canonical-websites/tutorials.ubuntu.com/files/1879845/conjure-up.log)

**Comment by fabouya** [comment]
Ubuntu 16.04 comes with an already installed lxd, it's better to remove it first:
sudo apt-get remove --purge lxd lxd-client
Then install lxd with snap : sudo snap install lxd
and then sudo lxd init
After that, conjure-up is ok with localhost

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
