### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by GMK2605** [canonical-web-and-design/tutorials.ubuntu.com#699]
I've created the bootable USB and am trying to load Ubuntu onto my laptop.  It fails every time I get to the location screen.  Message "Failed to create a swap space.  Does anyone have any advice to get this to progress ?

**Comment by evilnick** [comment]
Is this with the 16.04 installer? Did you specify custom partitioning? Usually this happens when the disk has an unusual setup, or you used manual mode and didn't set a swap space

This may help:
https://ubuntuforums.org/showthread.php?t=2314476

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
