### ISSUE TITLE
Installing Unbuntu Dual boot with MACOS X

### ISSUE THREAD

**Issue by Chrissy4605** [canonical-web-and-design/tutorials.ubuntu.com#700]
I have a Mac Mini early 2014 that I want a dual boot with Unbutu. I have a bootable USB ready, and I have a pre partitioned 380GB MSDos formatted hard drive. I am in the progress of down loading Unbuntu 17.10.1. I will be making a dvd disk to aid in this installation!!!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
