### ISSUE TITLE
[Install Ubuntu on Windows 10] <please add a title>

### ISSUE THREAD

**Issue by pday2** [canonical-web-and-design/tutorials.ubuntu.com#710]
<describe the issue>
So I got Ubuntu on my windows machine and I want to verify my iso, however, my iso sits in a windows folder and I can't figure out how to locate it in the Ubuntu window, can just find linux stuff.  ACKKKK this day is going terribly, nothing working, going to live in cave!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
