### ISSUE TITLE
[Basic snap usage] Where the HECK do you find available snaps??????

### ISSUE THREAD

**Issue by mem0uni** [canonical-web-and-design/tutorials.ubuntu.com#719]
We all get it. SNAPS are very very cool. It's an awesome way forward for applications.

Where the freak do you go to find available snaps???

How about this:

$ sudo snap list-available-apps  
[A list of snaps is presented that can be installed, in alphabetical order...]

/MM

**Comment by Lukewh** [comment]
@mem0uni for a curated list and search, you can use https://snapcraft.io/store
If you want a big long list, try https://uappexplorer.com/snaps

If you have feedback for https://snapcraft.io/store please file issues on https://github.com/canonical-websites/snapcraft.io/issues

You can also visit https://forum.snapcraft.io to make suggestions for snapd (like your `list-available-apps` command :wink: )

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
