### ISSUE TITLE
[Create a bootable USB Stick on macOS] Step 3 "Prepare the USB Stick" misses necessary click

### ISSUE THREAD

**Issue by thraizz** [canonical-web-and-design/tutorials.ubuntu.com#723]
After step 1, *Launch Disk Utility from[...]*, the user needs to make sure that he checked "Show all devices" and not the default, "Show only volumes". The hotkey for this would be CMD+2.
If the default is checked, the user will select his USB Stick on the right but will miss some options in the "Erase" tool; for example the option to choose a scheme.

**Comment by thraizz** [comment]
[https://apple.stackexchange.com/questions/304131/no-partition-scheme-option-when-erasing-a-usb-disk-in-macos-high-sierra](This) is the matching stackexchange discussion.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
