### ISSUE TITLE
Verify Ubuntu Download > 6. Check the ISO (failed because of the system language)

### ISSUE THREAD

**Issue by felippehddev** [canonical-web-and-design/tutorials.ubuntu.com#725]
On the page: https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#5
When you run the command:
`sha256sum -c SHA256SUMS 2> & 1 | grep OK`
You will get any results if your system is not in English, even if the ISO integrity is OK.
In my case, my system is in Portuguese (Brazil), if I execute the command changing "OK" by "SUCESSO", it will work:
`sha256sum -c SHA256SUMS 2> & 1 | grep SUCESSO`
But, I suggest that you change to something like:
`sha256sum --ignore-missing -c SHA256SUMS`
Because it will work regardless of the system language.
*Speaking about languages, sorry for my bad English.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
