### ISSUE TITLE
[Create a bootable USB stick on Windows] <Not showing up>

### ISSUE THREAD

**Issue by Friemeltjes** [canonical-web-and-design/tutorials.ubuntu.com#726]
<I did all the steps however the usb doesnt show up in the boot menu...>

**Comment by whobiggs** [comment]
I have the same problem, it wants me to create a DVD but my device does not have one and there is no alternative ie USB stick, I've tried Solus, Rufus Linux mint and Ubunto with the same result every time. Do I have to be a total computer nerd to work this?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
