### ISSUE TITLE
[Setup a ZFS storage pool] - don't specify devices /dev/sda etc, instead use their UUID

### ISSUE THREAD

**Issue by ColinIanKing** [canonical-web-and-design/tutorials.ubuntu.com#729]
It's bad practice to specify the device path by /dev/sda /dev/sdb etc as these can change order on boot with some devices.  Instead, use the device UUID, e.g.:

ls -l /dev/disk/by-uuid/ 
total 0
lrwxrwxrwx 1 root root 10 May  2 00:23 11925467592151204233 -> ../../sdb1
lrwxrwxrwx 1 root root 10 May  2 00:23 13970590-5063-4e93-afec-dbf50c31b2b3 -> ../../dm-0
lrwxrwxrwx 1 root root 10 May  2 00:23 c1315748-b7b7-4829-8447-0e3765cf24e4 -> ../../sda3
lrwxrwxrwx 1 root root 10 May  2 00:23 c67a5104-c2bc-4877-af98-08930af86cf3 -> ../../sda1
lrwxrwxrwx 1 root root 10 May  2 00:23 ccccf314-72cf-4f97-a5c4-5ba83b05ed35 -> ../../sda2

..so for /dev/sda1 I'd use:
and use /dev/disk/by-uuid/ c67a5104-c2bc-4877-af98-08930af86cf3

**Comment by evilnick** [comment]
Yes, I agree. We will edit this accordingly

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
