### ISSUE TITLE
[Upgrade Ubuntu desktop] <please add a title>i like having acces to ubuntu, but i needed the gui desktop, and it's been more than a week tryin

### ISSUE THREAD

**Issue by 4bdjc2U** [canonical-web-and-design/tutorials.ubuntu.com#732]
<describe the issue>I like having access to ubuntu, but i needed the gui desktop for a ravencoin wallet, and it's been more than a week trying to get it now from terminal commands and updates etc..., and the whole experience seems a bit fatuous

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
