### ISSUE TITLE
Ubuntu 18.04 installation issue

### ISSUE THREAD

**Issue by siddmukherjee** [canonical-web-and-design/tutorials.ubuntu.com#733]
On the final screen of the Ubuntu 16.04 and 18.04 installation process on my Dell laptop, I see a prompt "Please remove the installation medium, then reboot". There is no way to reboot other than holding down the power button. Once I do that and again boot up the laptop, everything works normally. Never faced this issue with my desktop, there, is says "Please remove the installation medium, then press enter". So most probably, this is an issue with my Dell laptop

Make and model: Dell Inspiron 3567
Processor: i5 7th gen
RAM: 8 GB
Hard disk: 1 TB

**Comment by eusouorisada** [comment]
Having the same problem here on my HP Pavilion g4 while trying to install ubuntu on a new partition.

**Comment by corradoventu** [comment]
Same problem installing Ubuntu Bionic 18.04.1 on my HP 250 and on HP 620.

**Comment by corradoventu** [comment]
Also on my HP 250 with Cosmic from Ubuntu 18.10 "Cosmic Cuttlefish" - Alpha amd64 (20180813)
/var/log/installer/telemetry is:
{"Media": "Ubuntu 18.10 \"Cosmic Cuttlefish\" - Alpha amd64 (20180813)", "Type": "GTK", "OEM": false, "PartitionMethod": "manual", "DownloadUpdates": true, "Language": "en", "Minimal": false, "RestrictedAddons": true, "Stages": {"0": "language", "9": "prepare", "86": "partman", "103": "partman", "107": "partman", "131": "partman", "132": "partman", "145": "partman", "149": "start_install", "157": "timezone", "190": "usersetup", "240": "timezone", "253": "usersetup", "302": "user_done", "998": "done"}}

**Comment by sanja7s** [comment]
I have the same issue with an HP workstation

**Comment by cenybar** [comment]
Same problem using a Lenovo laptop

**Comment by garbadrom** [comment]
Same issue with an Acer laptop (Acer Aspire S3-391), for a fresh install over Ubuntu 16.04

**Comment by rocky-lq** [comment]
Ctrl + C;

**Comment by siddmukherjee** [comment]
I have, since the original post, performed several re-installations of Ubuntu18.04 and discovered that if I leave the final screen at "Please remove the installation medium, then reboot" for a long time (> 30 minutes), the computer restarts automatically without me having to do a hard reboot. Thought sharing this maybe little helpful.

**Comment by pmahnke** [comment]
@8none1 where should I send this lovely people for help and any suggestions for the tutorial?

**Comment by 8none1** [comment]
Having to manually power off the machine in order to reboot is expected and a known issue.  It's being tracked under this bug in Launchpad:

https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1820607

I think there is another, older, bug somewhere, but I can't find it, so I logged a new one.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
