### ISSUE TITLE
[How to verify your Ubuntu download] grep option in Command fails in other languages

### ISSUE THREAD

**Issue by guilloip** [canonical-web-and-design/tutorials.ubuntu.com#735]
In the last step, in order to probe that the Ubuntu ISO image is not corrupted, you suggest to use:

`sha256sum -c SHA256SUMS 2>&1 | grep OK`

But in some spanish translation of linux, the "OK" is translated as "La suma coincide".  It might happens in other languages arround the world too, so you should advise the user following the step, in order to avoid a bad interpretation of the result as I almost did. I tried again removing redirections and pipes, and I could verify my ubuntu was OK:

```
antofagasta ubuntu 18 04 lts # sha256sum -c SHA256SUMS 2>&1 | grep OK

antofagasta ubuntu 18 04 lts # sha256sum -c SHA256SUMS 
ubuntu-18.04-desktop-amd64.iso: La suma coincide
sha256sum: ubuntu-18.04-live-server-amd64.iso: No existe el fichero o el directorio
ubuntu-18.04-live-server-amd64.iso: FALLO al abrir o leer
sha256sum: ATENCIÓN: no se pudo leer 1 fichero listado

```

**Comment by evilnick** [comment]
That's a good point, we will make a change to the tutorial

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
