### ISSUE TITLE
how to Retrieve the correct signature key

### ISSUE THREAD

**Issue by m2k1981** [canonical-web-and-design/tutorials.ubuntu.com#736]
I'm new to this but when I tried to check signature key i was redirected to [] (http://releases.ubuntu.com/bionic/) where keys were available as simple text. So how to use them? By coping them and pasting them in text file and renaming the one to .gpg and another one is .txt as it was on webpage. But all gpg related command needs sudo privilege otherwise "gpg: can't open `/home/****/.gnupg/pubring.gpg' gpg: keydb_search_first failed: file open error" I get errors like this. On issuing command "gpg --verify SHA256SUMS.gpg SHA256SUMS" gets massage like gpg: Signature made Monday 30 April 2018 11:40:17 PM IST using DSA key ID FBB75451
gpg: BAD signature from "Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>"
gpg: Signature made Monday 30 April 2018 11:40:17 PM IST using RSA key ID EFE21092
gpg: BAD signature from "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>"

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
