### ISSUE TITLE
Missing information in, "Create a bootable USB stick on MscOS"

### ISSUE THREAD

**Issue by massonpj** [canonical-web-and-design/tutorials.ubuntu.com#737]
On page one, "1. Overview", of the tutorial, "Create a bootable USB stick on MscOS" 
([https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#0](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#0)), it states:

> Apple hardware considerations
> There are a few additional considerations when booting the USB stick on Apple hardware. This is because Apple's ‘Startup Manager', summoned by holding the Option/alt (⌥) key when booting, won't detect the USB stick without a specific partition table and layout. **We'll cover this in a later step.**

However, after completing the tutorial's seven pages, this information, about creating "a specific partition table and layout", is not provided. 

After creating the USB as instructed, inserting it into my MacBook Pro and restarting, the USB stick does  not appear as a bootable device. This missing information seems very relevant.

**Comment by Bielorusse** [comment]
Hi,

I am having the same issue. 
I noticed that I couldn't set the scheme to GUID partition map when erasing my USB stick in step 3.
Maybe that's what's causing the problem?

If that is the case, [this other topic](https://github.com/canonical-websites/tutorials.ubuntu.com/issues/765) is linked, but I couldn't use their solution ("show all devices" option not available in my Disk Utility)

**Comment by Bielorusse** [comment]
OK, I managed to set the USB scheme to GUID partition scheme using the "partition" tab of the Disk Utility.

I selected "1 partition" in the drop down menu under "partition scheme"
After that I chose "options" and finally "GUID partition map".

After using etcher, I noticed that the USB scheme was changed back to "Apple partition map". 

And the USB stick still does not appear as a bootable device when restarting the Macbook on which I want to install Ubuntu.

**Comment by massonpj** [comment]
Thanks for the updates @Bielorusse, perhaps the tutorials.ubuntu.com team will be able to provide some additional information both here and in the tutorial as well. 

I was unable to ever find a solution, and gave up... :-( I guess that's one less Ubuntu user in the world!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
