### ISSUE TITLE
app-routing broken on website

### ISSUE THREAD

**Issue by tpanetti** [canonical-web-and-design/tutorials.ubuntu.com#74]
For example if you open the first page, click the 2nd item so the website navigates to #2, then hit back, the page doesn't app-route back to the top

**Comment by WillMoggridge** [comment]
Thanks for pointing this out. 
It seems to also be a problem upstream with codelabs at https://codelabs.developers.google.com/.

Hopefully I will be able to look into this shortly.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
