### ISSUE TITLE
[Install single-server OpenStack with conjure-up] <please add a title>

### ISSUE THREAD

**Issue by tecnogestiones** [canonical-web-and-design/tutorials.ubuntu.com#742]
problemas al instalar openstack , me indica que desactive ipv6 y lo hice, pero no me recnoce lxc network, y lxc storage
CUEK!!! mALA MUY MALA!!!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
