### ISSUE TITLE
[snap-a-website] Snap a website with Electron

### ISSUE THREAD

**Issue by mehdibo** [canonical-web-and-design/tutorials.ubuntu.com#743]
In step 6 "Snap metadata (snapcraft.yaml)" there are some deprecated values:

> DEPRECATED: The 'build' keyword has been replaced by 'override-build'
> See http://snapcraft.io/docs/deprecation-notices/dn8 for more information.
> DEPRECATED: The 'install' keyword has been replaced by 'override-build'
> See http://snapcraft.io/docs/deprecation-notices/dn9 for more information.
>

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
