### ISSUE TITLE
[Basic snap usage] Storing snap application specific files

### ISSUE THREAD

**Issue by nulty** [canonical-web-and-design/tutorials.ubuntu.com#745]
It would be nice to add some information on where to store application specific files such as a password file for KeepassXC for example. Normally with apt it would be stored in the .local directory but with snap I'm not sure where is best to keep files like this.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
