### ISSUE TITLE
No such thing: "use the bottom left icon to open ‘Show Applications'"

### ISSUE THREAD

**Issue by zasran** [canonical-web-and-design/tutorials.ubuntu.com#749]
Text at https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu#2 says:

1. Insert your USB stick (select ‘Do nothing' if prompted by Ubuntu)
2. On Ubuntu 18.04 and later, use the bottom left icon to open ‘Show Applications'

However when I stick in the USB key in there is no bottom left icon anywhere. What appears is a small window/notification that only has text 'Windows USB'. When I mouse over it there is an 'x' to close it and pulldown with one item 'Open with Files'. That's all, no other options, no places to click, nothing.

There doesn't seem to be an obvious way to find the startup disk creator, using Alt-F2 or terminal doesn't work (typing start or Start and using tab doesn't come up with any suggestions).

Suggestion: add the name of the command that can be typed on command line.

**Comment by zasran** [comment]
For the record, seems like there are two programs that can create USB/SD card start disks for Gnome and KDE, packages are usb-creator-gtk (think this is installed by default by Ubuntu desktop) and usb-creator-kde.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
