### ISSUE TITLE
I would love a rust tutorial

### ISSUE THREAD

**Issue by plhowk** [canonical-web-and-design/tutorials.ubuntu.com#75]
Anything really.  Just rust based

**Comment by grahambancroft** [comment]
Hi plhowk,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
