### ISSUE TITLE
Suggestion: Add more information to Step 9 (Review Process)

### ISSUE THREAD

**Issue by hubvu** [canonical-web-and-design/tutorials.ubuntu.com#752]
* Whilst I was going through the review process, under the **Making a Pull Request** header, it would be handy to inform contributors that they should fork the project first, and then create a new branch that is parallel to the master branch.

![fork-issue](https://user-images.githubusercontent.com/33167870/40478246-756c7a74-5f40-11e8-81cf-f6b9294cf124.png)

* Does that make sense?

**Comment by hubvu** [comment]
[Link to Step 9 of the guidelines tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-guidelines#8)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
