### ISSUE TITLE
[Install Ubuntu desktop] <bootable USB>

### ISSUE THREAD

**Issue by Necrosnake** [canonical-web-and-design/tutorials.ubuntu.com#756]
I would include the link to rufus or any other software to create a bootable USB and not just saying that using a USB is the same as using a cd / dvd

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
