### ISSUE TITLE
[Create a bootable USB stick on Ubuntu] <please add a title>

### ISSUE THREAD

**Issue by LarryJoy** [canonical-web-and-design/tutorials.ubuntu.com#757]
For Nr 3 "Launch Startup Disk Creator", then Nr 2 "On Ubuntu 18.04 and later, use the bottom left icon to open 'Show Applications'". Bottom left icon is NOT "Show Applications", it is the USB stick (which is empty) that I have plugged in. My Ubuntu 18.04 LTS is not working properly, after about 5 s a small window opens and asks for my password. I enter it and the OS goes to the Ubuntu GUI screen and then in another 5 s it goes to the enter password screen again.
I can get to the "console" by entering "Ctrl+Alt+F2". What are the terminal commands to accomplish this?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
