### ISSUE TITLE
Setup a ZFS storage pool

### ISSUE THREAD

**Issue by jerryrondon** [canonical-web-and-design/tutorials.ubuntu.com#758]
>  A striped pool, where a copy of data is stored across all drives or a mirrored pool, where a single complete copy of data is stored on all drives.

The definitions of striped and mirrored pools are switched.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
