### ISSUE TITLE
joining an ubuntu machine into an AD environment

### ISSUE THREAD

**Issue by deknos** [canonical-web-and-design/tutorials.ubuntu.com#76]
It would be cool to have a tutorial how to join a ubuntu client into an AD environment. Or even build a simple AD environment with packages from the ubuntu repo itself.

**Comment by grahambancroft** [comment]
Hi deknos,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
