### ISSUE TITLE
Many tutorials still use Upstart in commandos instead of Systemd

### ISSUE THREAD

**Issue by MaxValue** [canonical-web-and-design/tutorials.ubuntu.com#761]
The current Ubuntu releases use Systemd as far as I know. Please correct me if I am wrong.

We should either change those commands or show both versions, depending on the Ubuntu version.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
