### ISSUE TITLE
[Install Ubuntu on Windows 10] <please add a title>

### ISSUE THREAD

**Issue by JonSmith111** [canonical-web-and-design/tutorials.ubuntu.com#762]
I tried that way going through the store but it kept saying that it failed to install.  So I turned on the Linux subsystem and restarted my computer and that didn't work so I'm posting this because I'm a Linux person using windows.

**Comment by shavs** [comment]
I would say - make sure that you are using the latest version of Windows (as of writing, Build 1803 - this can be checked by typing _About your PC_, in the Start menu). From there, make sure you have _not_ enabled Windows Subsystem for Linux in the Windows Features panel.

Then, search Ubuntu in the Microsoft Store, finding the first one, and clicking install. Make sure you have over 2GB of free space on your `C:` drive. It may ask you to reboot, but once the install has completed, you should be asked to enter your username and password into the terminal.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
