### ISSUE TITLE
https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#2

### ISSUE THREAD

**Issue by mikerieser** [canonical-web-and-design/tutorials.ubuntu.com#765]
On latest version of MacOs (High Sierra) you have to change the view on the Disk Utility to "Show All Devices" before you'll see the partition scheme to set it.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
