### ISSUE TITLE
[Create a bootable USB stick on Windows] /casper/vmlinuz not found

### ISSUE THREAD

**Issue by FilipeBerti** [canonical-web-and-design/tutorials.ubuntu.com#766]
when I try to boot using the Live USB created using Rufus and following all instructions, it doesn't boot properly.
I receive a message : "/casper/vmlinuz not present".

**Comment by ProfessorStrawberry** [comment]
me too. only solution is to create the usb stick with rufus and then copy the content of the iso one more time with explorer.

**Comment by ProfessorStrawberry** [comment]
I think I found the culprit. Do you have Bitdefender or Eset or Windows Defender active? Those scan your active processes and block file access for rufus. In Eset I set HIPS to Automatic and now it works. No more vmlinuz missing.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
