### ISSUE TITLE
[Install and Configure Samba]

### ISSUE THREAD

**Issue by maxall4** [canonical-web-and-design/tutorials.ubuntu.com#767]
my computer says it cant connect to the ip address of the server

**Comment by Bhlowe** [comment]
Missing a step on the instructions:

sudo ufw allow Samba

**Comment by pmahnke** [comment]
@maxall4 	did that work?
@Bhlowe 	could you provide a PR if it does?

**Comment by CodyBriscoe** [comment]
I still get a "Windows cannot access" error, even after allowing Samba through ufw

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
