### ISSUE TITLE
[Upgrade Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by Rodney6** [canonical-web-and-design/tutorials.ubuntu.com#772]
I am specifically asking for a download for ubuntu 16.04.  Like Micro$oft, you keep pushing the latest series of ubuntu.  I tried 18.04 but was disappointed with the change from Debian.  I am rather new to Linux and I can't get the gist of 16.04 yet.  I don't know what else to do, but I certainly don't want 18.04 yet, if ever.
Thank you for allowing me to let off some steam here, I appreciate it.
Rod.

**Comment by caldav** [comment]
Hi, I'm not aware of any "change from Debian", but Ubuntu 16.04 is supported until april 2021. You can find a download link for it, along all the other currently supported Ubuntu releases, at http://releases.ubuntu.com.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
