### ISSUE TITLE
snap find --section tutorial needs update

### ISSUE THREAD

**Issue by crajun** [canonical-web-and-design/tutorials.ubuntu.com#774]
https://tutorials.ubuntu.com/tutorial/advanced-snap-usage#6

In section "sections" it says to use ```snap find [TAB][TAB]``` and ```snap find --section internet-of-things```.

Neither work for me while using:
snap    2.33.1
snapd   2.33.1
series  16
ubuntu  18.04
kernel  4.15.0-23-generic

First, "internet-of-things" does not exist anymore:
```
$ snap find --section=internet-of-things
error: No matching section "internet-of-things", use --section to list existing sections
```
So we'll try existing 'games' section instead used documentation syntax:
```
$ snap find --section games
No section specified. Available sections:
 * developers
 * featured
 * finance
 * games
 * graphics
 * music
 * productivity
 * server
 * social-networking
 * utilities
 * video
Please try 'snap find --section=<selected section>'
```
The correct syntax
```
$ snap find --section=games
Name            Version         Developer           Notes  Summary
boa             c2-gzdoom3.3.2  njmcphail           -      WolfenDoom: Blade of Agony
pin-town        2.0.79          failsafegames       -      Help the Pin Pals in this physics puzzle game, inspired by Pachinko
scummvm         2.0.0           snapcrafters        -      ScummVM is a program which allows you to run certain classic graphical point-and-click adventure games
```

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
