### ISSUE TITLE
[Install Ubuntu desktop] <Failed to boot after installation complete>

### ISSUE THREAD

**Issue by delick** [canonical-web-and-design/tutorials.ubuntu.com#777]
I am trying to install Ubuntu 18.04 LTS. When I restart the computer after installation complete, error 1962 occured, saying no operating system found. If I try to reinstall Ubuntu from USB, it says I've already installed Ubuntu and have to unstall it first.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
