### ISSUE TITLE
[Install and Configure Apache] misleading use of /sites-enabled directory

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#778]
On page https://tutorials.ubuntu.com/tutorial/install-and-configure-apache#2 it's stated to edit "/etc/apache2/sites-enabled/000-default.conf", but the directory sites-enabled contains symlinks actually and shouldn't be edited manually. Even though it's possible to edit real file file from symlink, it shouldn't be used like that. It should state "/etc/apache2/sites-available/000-default.conf" file instead.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
