### ISSUE TITLE
Link for "Graphical Snaps: Using Xwayland" broken

### ISSUE THREAD

**Issue by appdog** [canonical-web-and-design/tutorials.ubuntu.com#780]
Url to page with borken link (bottom of page):
https://tutorials.ubuntu.com/tutorial/graphical-snaps#1

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
