### ISSUE TITLE
[How to verify your Ubuntu download] sha256sum not available on macOS

### ISSUE THREAD

**Issue by sebpiq** [canonical-web-and-design/tutorials.ubuntu.com#782]
https://github.com/canonical-websites/tutorials.ubuntu.com/blob/master/tutorials/desktop/how-to-verify-ubuntu/how-to-verify-ubuntu.md#check-the-iso

It is instructed to use the command line `sha256sum` to compare the checksums. However for me this is not installed by the brew commands given above in the tutorial (`coreutils` and `gnupg`). Instead I simply used `shasum` command

**Comment by evilnick** [comment]
Thanks for reporting this, we'll check into it

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
