### ISSUE TITLE
Fail to launch new container

### ISSUE THREAD

**Issue by danucalovj** [canonical-web-and-design/tutorials.ubuntu.com#784]
From documentation available at:  https://tutorials.ubuntu.com/tutorial/tutorial-setting-up-lxd-1604#3

Running "lxc launch ubuntu:16.04", per the documentation, fails with the following error:

```
Creating the container
error: Failed container creation:
 - https://cloud-images.ubuntu.com/releases: The requested image couldn't be found.
```

Running the following works:

`lxc launch ubuntu:xenial/amd64 base`

Documentation may be out of date or incorrect.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
