### ISSUE TITLE
[Install Ubuntu desktop] <please add a title>

### ISSUE THREAD

**Issue by elnazrahmati** [canonical-web-and-design/tutorials.ubuntu.com#786]
I installed ubuntu alongside windows and after restarting windows came up so I went to boot manager but ubuntu wasn't there... :(

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
