### ISSUE TITLE
Examples of all LXD config key/value pars

### ISSUE THREAD

**Issue by bmullan** [canonical-web-and-design/tutorials.ubuntu.com#79]
The github file is fairly terse and IMHO may be hard for beginner to intermediate LXD users to follow and use.?

https://github.com/lxc/lxd/blob/master/doc/configuration.md

**Comment by WillMoggridge** [comment]
Thanks for creating this issue, bmullan. We will forward the information on to our tutorials team.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
