### ISSUE TITLE
[How to verify your Ubuntu download] Article doesn't verify the keys

### ISSUE THREAD

**Issue by Ajedi32** [canonical-web-and-design/tutorials.ubuntu.com#790]
From: https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#4

This article is meant to walk users through verifying their Ubuntu download to ensure it hasn't been tampered with. Though it correctly informs users how to verify the Ubuntu ISO hash files with _a_ key, the method used provides absolutely no assurances that the key used in the verification actually belongs to Ubuntu.

An attacker could easily replace the hash GPG files with a malicious version signed with their own keys an the user would be none the wiser. (Especially since http://releases.ubuntu.com/ doesn't seem to even support HTTPS.)

The output from GPG in the article even calls this out explicitly:

```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

**Comment by wiktor-k** [comment]
Agreed. The fourth step should ask the user to verify last line: `Primary key fingerprint: 8439 38DF 228D 22F7 B374  2BC0 D94A A3F0 EFE2 1092`.

Additionally previous steps have a lot of edge cases w.r.t Ubuntu key being locally present or not but this can be simplified, e.g. `gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS` can be shortened to `gpg --keyid-format long --auto-key-retrieve --verify SHA256SUMS.gpg SHA256SUMS` and GnuPG will get the key if it's not locally present. That makes the ["4. Retrieve the correct signature key"](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#3) step obsolete.

**Comment by LuigiWriter** [comment]
This Article also assumes a user new to Ubuntu knows how to "fetch these files from the http://releases.ubuntu.com page for the relevant release."

The article needs an example of the command line needed. 
Is Fetch even a valid Linux command?
My search for "fetch files" led me to the "FTP" protocol [which I could not tease out just what was needed to "fetch" a file.

I suspect I have a bad ISO download on a good DVD disk or a good ISO on a bad DVD and am having to re-learn how to do check-sums.

I tried the above substitute command and got this  "verify signatures failed: file open error" which has been dogging my effort and brought me here after.

~$ `gpg --keyid-format long --auto-key-retrieve --verify SHA256SUMS.gpg SHA256SUMS`
gpg: WARNING: "--auto-key-retrieve" is a deprecated option
gpg: please use "--keyserver-options auto-key-retrieve" instead
gpg: can't open `SHA256SUMS.gpg'
gpg: verify signatures failed: file open error

gpg --keyid-format long --auto-key-retrieve --verify SHA256SUMS.gpg SHA256SUMS`
Changed to:
gpg --keyid-format long --keyserver-options auto-key-retrieve --verify SHA256SUMS.gpg SHA256SUMS
Result:
gpg --keyid-format long --keyserver-options auto-key-retrieve --verify SHA256SUMS.gpg SHA256SUMS
gpg: can't open `SHA256SUMS.gpg'
gpg: verify signatures failed: file open error

Going to go looking to see if someone else can tell me what I did wrong to get "verify signatures failed: file open error"

A Note: as you may have noticed above it is easy to pick up a almost invisible accent [`] at either end when copying a command to paste on terminal. This seems to be something new.  A caution may be in order.

**Comment by LuigiWriter** [comment]
how to download SHA256SUMS from http://releases.ubuntu.com/bionic/?
Seems the most simple question, however all I get at Ask.Ubuntu, stack exchange and gethub is theory others problems and complications.
 http://releases.ubuntu.com/bionic/  does not offer a copy or download option for the files. Other click on the file and all I get in Firefox is link choices. I have been warned in one of those sources that copying and pasting contents into a file I create will fowl up the process.

So
gpg --keyid-format long --keyserver-options auto-key-retrieve --verify SHA256SUMS.gpg
as corrected will not work if the gpg files are not properly downloaded.
And how to do that is the vital step for which I can find no instructions.
I hope you have found a way?

**Comment by wiktor-k** [comment]
> how to download SHA256SUMS from http://releases.ubuntu.com/bionic/?

Right click on the `SHA256SUMS` file at the bottom and click "Save Link As" in the context menu?

> gpg --keyid-format long --auto-key-retrieve --verify SHA256SUMS.gpg SHA256SUMS
> as corrected will not work if the gpg files are not properly downloaded.

Well, yeah, if you don't have these files it won't work, of course.

Maybe try this one?

> curl -O http://releases.ubuntu.com/bionic/SHA256SUMS

It will download the file to the current dir and name it correctly. You can right click on links on that page and select "Copy Link Location" if you want to copy URL from there. (`curl -O` <-- this is big "o", *not* zero).

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
