### ISSUE TITLE
Run Linux containers on Windows: no matching manifest for windows/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by EstebanSignorini** [canonical-web-and-design/tutorials.ubuntu.com#791]
In step 7, while running docker pull, I'm getting the following error:

PS C:\Users\nik> .\docker.exe pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
no matching manifest for windows/amd64 in the manifest list entries

Solution:
Change command "dockerd.exe -D --data-root C:\lcow" for ".\dockerd.exe -D --data-root C:\lcow --experimental"

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
