### ISSUE TITLE
[Create a bootable USB stick on macOS] Doesn't work on 2008 MacBook Pro

### ISSUE THREAD

**Issue by RobLewis** [canonical-web-and-design/tutorials.ubuntu.com#794]
Doesn't work on 2008 MacBook Pro. 

The write & verification of the ISO image to the 32GB USB stick appears to work. Then macOS says the disk can't be read. I click "Ignore". 

Rebooting the Mac with the Option key down brings up two identical-looking USB EFI drives. Attempting to boot either one produces a message "error: file '/boot/' not found". Then the Ubuntu boot menu appears, but booting fails with several error messages about being unable to find things. 

I tried both the FAT and ExFAT formats for the USB stick but got the same results.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
