### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by JMWeid** [canonical-web-and-design/tutorials.ubuntu.com#799]
Simple? Easy-to-follow? 
**WHO ARE YOU KIDDING?**
If the "set" of instructions require twenty steps, why do you only include five or six? Is this a guessing game? Do you _never_ wonder **why** you have so few adopters? Get **A CLUE!** You act like nothing more than microsift wannabes, ten different words/phrases to mean the same thing and one word to mean ten different things and fifty different things not mentioned at all.

Step-by-step **MEANS** step-by-step. It's nothing but a few electrons! How difficult is THAT? Spell it out instead of keeping it a mystery. Talk about being cultish!

As it is, your instructions are neither simple nor step-by-step. A bridge-troll has fewer mysteries answered to cross.

**Comment by caldav** [comment]
Could you clarify which tutorial you are frustrated with? Thanks.

**Comment by JMWeid** [comment]
As an example (of many dozens I've wasted many days trying to divine):

https://www.linuxtechi.com/dual-boot-ubuntu-18-04-lts-with-windows-10/

It's what I've been attempting for weeks, but no matter which "tutorial" I locate, they ALL assume the interested party can divine "hidden" clues, incantations, sacrificial offerings, tokens, or what are euphemistically termed "steps" unmentioned.

(Even one of the so-called "necessary ingredients" item called rufus 3.1 lacks some significant "steps" to say nothing of a lack of even remote similarity of the example given to what is actually produced. And that's from their OWN website!)

In the typical example given, from linuxtechi, do you notice something missing between steps 4, 5 & 6?

By definition (to anyone other that tech cultists) step-by-step means exactly that: STEP-BY-STEP. Most of what I've experienced are videos of "helpful folk" who act as though they are in some kind of race to see what they can prove in the shortest period of time. And like I posted above, "Do you (the linux community as a whole) never wonder why you have so few adopters?"

I can appreciate the efforts of some who try to "help" but they are to-a-one oblivious to all intervening steps they assume others know intuitively. (Don't get me wrong. It isn't only linux folks who do this. It took me years to figure out how to do cut, copy and paste with windows because their "instructions" always presumed it was already known. AND icons are NOT intuitive!)

You folks have NO idea how frustrated the last 15 years have been because of this very issue. I hate microsift, addle, gaggle and the rest, not just for their obtuseness and arrogance but their presumption they have the right to invade one's privacy, to usurp one's personal thoughts, creations, experiments and explorations of ideation itself. That's to say nothing of their indentured servitude to the national security state of the wealthy, those who answer to no one.

None of which is justifiable yet presumed to be here in the Land of the Home, Free of the Brave.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
