### ISSUE TITLE
[Create a bootable USB stick on Windows] Rufus version too old

### ISSUE THREAD

**Issue by Trumeet** [canonical-web-and-design/tutorials.ubuntu.com#800]
On page 4, I see that the tutorial is using version **2.15**, but the latest version of Rufus is **3.1**, **the most operation method was changed**, could you update the tutorial? Thanks!

**Comment by tuubuu** [comment]
The info they present is crap.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
