### ISSUE TITLE
Directions are incomplete. 

### ISSUE THREAD

**Issue by Wackyoneone** [canonical-web-and-design/tutorials.ubuntu.com#801]
No clue as to what to insert in the fields of the Disk Creator window. 
I know it's 18.04 but what source? Also my USB stick did not show up. What do I do now?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
