### ISSUE TITLE
Remove container/use_v1_api_client in Get started with Kubeflow tutorial

### ISSUE THREAD

**Issue by davecore82** [canonical-web-and-design/tutorials.ubuntu.com#802]
On page https://tutorials.ubuntu.com/tutorial/get-started-kubeflow#2

There is a mention about running "gcloud config set container/use_v1_api_client false"

The gcloud property container/use_v1_api and its alias container/use_v1_api_client have been removed from GKE: https://cloud.google.com/sdk/docs/release-notes#20800_2018-07-10

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
