### ISSUE TITLE
ks pkg install kubeflow/tf-job fails in Get started with Kubeflow tutorial

### ISSUE THREAD

**Issue by davecore82** [canonical-web-and-design/tutorials.ubuntu.com#803]
On page https://tutorials.ubuntu.com/tutorial/get-started-kubeflow#3

The command "ks pkg install kubeflow/tf-job" fails with:

ERROR resolve registry library: GET https://api.github.com/repositories/112647343/contents/kubeflow/tf-job?ref=753506b93c6cdb9900fd2a0b5a7967490a1ef00b: 404 Not Found []

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
