### ISSUE TITLE
Disabling auto update

### ISSUE THREAD

**Issue by wahoo68** [canonical-web-and-design/tutorials.ubuntu.com#804]
Request documentation addressing how to disable auto updating of snaps. If this is possible now, I haven't seen it documented.

**Comment by Lin-Buo-Ren** [comment]
It is by design not supported, that's why it isn't documented.  Refer [Disabling automatic refresh for snap from store - snapd - snapcraft.io](https://forum.snapcraft.io/t/disabling-automatic-refresh-for-snap-from-store/707) for more info.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
