### ISSUE TITLE
Problem Installing and configuring LXD

### ISSUE THREAD

**Issue by bensaction** [canonical-web-and-design/tutorials.ubuntu.com#807]
Tutorial Installing and configuring LXD does not work.
To install conjure-up you need to migrate lxd
My bad. i had created sudo lxd init instead of sudo /snap/bin/lxd init
lxd.migrate

~/.config/lxc to ~/snap/lxd/current/.config/lxc

lxc network list
lxc storage list

After doing migrate it works.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
