### ISSUE TITLE
beginners set up after installing Ubuntu

### ISSUE THREAD

**Issue by kmok1956** [canonical-web-and-design/tutorials.ubuntu.com#809]
I don't know what to do next. Your tutorials leave me asea.

**Comment by tuubuu** [comment]
I agree, utterly useless tutorials with incorrect info, or none where you need it. Who are the dummies who make this stuff up??

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
