### ISSUE TITLE
Tutorial requests for mail, FTP and LDAP servers

### ISSUE THREAD

**Issue by iomarian** [canonical-web-and-design/tutorials.ubuntu.com#81]
Hello. Could you make tutorials about how to setup a mail server, ftp server, ldap server ?

**Comment by grahambancroft** [comment]
Hi iomarian,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
