### ISSUE TITLE
[Create a bootable USB stick on macOS] USB stick does not appear as bootable device

### ISSUE THREAD

**Issue by Bielorusse** [canonical-web-and-design/tutorials.ubuntu.com#812]
I followed the instructions of [this tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#5), but my USB stick does not appear as bootable device in Apple's 'Startup Manager' on step 7.

I set the format to MS-DOS (FAT) and the scheme to GUID Partition Map when preparing my USB stick on step 3.

I am using a mid-2014 Macbook Pro to prepare the USB stick.
I want to install Ubuntu on a Macbook 6.1

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
