### ISSUE TITLE
[Upgrade Ubuntu desktop] No information on getting an .iso

### ISSUE THREAD

**Issue by cppljevans** [canonical-web-and-design/tutorials.ubuntu.com#813]
The URL:

https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu#1

suggests that by following the link, one can get an ISO file.  However, I was
never able to find anywhere to download an ISO file.

Please make the tutorial more idiot-proof.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
