### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by DominicLutherEarl** [canonical-web-and-design/tutorials.ubuntu.com#814]
<describe the issue>
My ass to the tutorial.
Rufus deleted all my high value data from one storage while showing another storage to flash the iso.
This is a very sick joke.
I'll be doing my best to get accountability here.
This is truly awful. At least, no mention of such things in the tutorial. Ubuntu could have done better. Really at a loss.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
