### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by seklund** [canonical-web-and-design/tutorials.ubuntu.com#816]
Tutorial describes Rufus v.2.  The current Rufus version is 3.1.1320, and a lot of what is described in the tutorial makes limited sense in the v.3 console.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
