### ISSUE TITLE
Setting up a home server

### ISSUE THREAD

**Issue by Eric38fr** [canonical-web-and-design/tutorials.ubuntu.com#82]
Hi ! at home, we have a bunch of computer and device, usign the same wifi box, but sharing stuff only by using "exterior" services (such as dropbox and others). I'ld like to go to the next step, which is having a home server (not necessarily on only one machine), which will play different roles : an intranet server for various purely local services, a mail server, a private calendar service and a few other small private services (short notes, picture repository, …). None of these services need to be critically operational, but they need to be really private, well secured. I think you catch the type of services I'ld like to have. However, I don't have the knowledge for. Therefore my specific need for tutorials ! Thanks in advance.

**Comment by grahambancroft** [comment]
Hi Eric38fr,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
