### ISSUE TITLE
Some problems found in snap-a-website tutorial 

### ISSUE THREAD

**Issue by apolitech** [canonical-web-and-design/tutorials.ubuntu.com#821]
Hey, how are you? I hope that you have a great day but let's dive into the problems.
The tutorial will not work as intended if you want to use the snapcraft.io builder:

1) Leaving or setting window.setMenuBarVisibility(true); will not work (https://tutorials.ubuntu.com/tutorial/snap-a-website?_ga=2.12355376.50077616.1536344768-478425408.1524735338#2)

2) build: node_modules/.bin/electron-builder will not work and you need to use  override-build: | (https://tutorials.ubuntu.com/tutorial/snap-a-website?_ga=2.12355376.50077616.1536344768-478425408.1524735338#5)

3) Failed to run 'override-build': Exit code was 1. in every build but not in amd64 where it does work as normal. In the forum, I did get this answer(https://forum.snapcraft.io/t/failed-to-run-override-build-exit-code-was-1/7268/3) 

This is my project page> https://github.com/apolitech/Ubuntu-Mate-launchpad-app

All the best and keep up the good work.
P.S using .yaml its pain in the $%$%# maybe you can find another way to do that in the feature.
P.S.S make a tutorial on how you can add the icon in the menu tab when the app is open.

**Comment by popey** [comment]
I'm of the opinion that this tutorial shouldn't actually exist. Making an entire snap just for a website isn't tremendously useful, although doing so will be a good primer for those just starting out. @flexiondotorg / @evandandrea / @caldav - opinions?

**Comment by apolitech** [comment]
For me this tutorial did help to build my first snap. It's easier to
understand to a new coder and it's giving him a satisfaction that he build
something and not just a simple "Hello world".

On Sep 10, 2018 12:56, "Alan Pope" <notifications@github.com> wrote:

I'm of the opinion that this tutorial shouldn't actually exist. Making an
entire snap just for a website isn't tremendously useful, although doing so
will be a good primer for those just starting out. @flexiondotorg
<https://github.com/flexiondotorg> / @evandandrea
<https://github.com/evandandrea> / @caldav <https://github.com/caldav> -
opinions?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/canonical-websites/tutorials.ubuntu.com/issues/821#issuecomment-419856771>,
or mute the thread

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
