### ISSUE TITLE
[Install Ubuntu desktop] <it wasn't install in

### ISSUE THREAD

**Issue by DanieLiran** [canonical-web-and-design/tutorials.ubuntu.com#822]
Hi
I want install ubuntu .i even buy another h.d.d for ubuntu.but always i have different problem.like you can't install ubuntu on this drive.
Copy file failed.
Or just stop and do nothing until I restart computer.
I downloaded iso of ubuntu 18.4 twice.
I created bootable USB with many programs    like poweriso .Rufus.universal ... 
What is wrong?
My config is 
Asrock 61m
Core i3 3220
8 gig Kingston 
160gig Samsung h.d.d

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
