### ISSUE TITLE
macOS 10.13 (High Sierra) Disk Utility (v17.0.3) step needs View->Show All Devices Step

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [canonical-web-and-design/tutorials.ubuntu.com#823]
On https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#2

Update the bullet points, for new version of Disk Utility
- Launch Disk Utility from Applications>Utilities or Spotlight search
- On macOS 10.13 and higher: From the Disk Utility menu, select View->Show All Devices
- Insert your USB stick and observe the new device added to Disk Utility
- Select the top of the USB stick device

Otherwise you might only see the partition on the USB stick, and erase will result in an error of:
```
Disk Erase failed with the error:
POSIX reports: The operation couldn’t be completed. Cannot allocate memory
```

See https://apple.stackexchange.com/questions/125965/unable-to-format-erase-hard-drive

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
