### ISSUE TITLE
[Create a bootable USB stick on Windows] <please add a title>

### ISSUE THREAD

**Issue by bfloyd4445** [canonical-web-and-design/tutorials.ubuntu.com#824]
<unable to install Ubuntu 18.04 lts with win 10 pro the installer did something to my new wd blue ssd 500gig solid state drive making it inoperable. I could not access windows or install Ubuntu I could run Ubuntu from the stick. I ended using the command prompt on a win 10 pro usb to format and partition the wd and reinstall win 10 pro. Re burned a new iso for Ubuntu 1804lts and tried to run but it runs with a double desktop. I'm downloading a new iso Ubuntu but thinking of trying the 16 version. 
bfloyd4445@aol.com

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
