### ISSUE TITLE
Instructions for Create a bootable USB stick on Mac OS

### ISSUE THREAD

**Issue by longsincelost** [canonical-web-and-design/tutorials.ubuntu.com#825]
Hello,
On step 3, 'Prepare the USB Stick', you might consider adding some additional information about pre-formatting the usb-stick to GUID partition table.  In High Sierra, 10.13, in disk utility, you need to go to 'View' > 'Show all Devices', then select the root of the volume, then erase.  Without doing this, you can only select MS-DOS format, not the partition table.
Thank you.

**Comment by longsincelost** [comment]
https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#2

**Comment by ryanmonro** [comment]
I had the same problem. Some details here about Disk Utility not showing all devices by default from High Sierra onwards:
https://www.macobserver.com/tips/quick-tip/how-to-format-drive-guid/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
