### ISSUE TITLE
Broken link on tutorial page

### ISSUE THREAD

**Issue by dadosutter** [canonical-web-and-design/tutorials.ubuntu.com#826]
The link 
https://tutorials.ubuntu.com/es6-bundled/tutorial/graphical-snaps

is broken (404), on the page
https://tutorials.ubuntu.com/tutorial/graphical-snaps-xwayland#0

1. Overview

This tutorial is a guide on how to use Xwayland to create graphical snaps for Ubuntu with a single GUI application running fullscreen on the display. This addresses situations like:

    Digital signage
    Web kiosk
    Industrial machine User Interface

The combination of Snap, the "mir-kiosk" Wayland server and Ubuntu Core ensures the reliability and security of any graphical embedded device application.

This tutorial assumes you are familiar with the material in **Graphical Snaps for Ubuntu Core**. In particular, techniques for debugging problems in your snap are not covered.
What you'll learn

How to create graphical snaps for Ubuntu Core using a toolkit that requires Xwayland to support Wayland.
What you'll need

    An Ubuntu desktop running any current release of Ubuntu
    A ‘Target Device' from one of the following:
        A device running Ubuntu Core.
        This guide shows you how to set up a supported device: https://developer.ubuntu.com/core/get-started/installation-medias. If there's no supported image that fits your needs you can create your own core image.
        Using a VM
        You don't have to have a physical "Target Device", you can follow the tutorial with Ubuntu Core in a VM. Install the ubuntu-core-vm snap:
        snap install --beta ubuntu-core-vm --devmode
        For the first run, create a VM running the latest Core image:
        sudo ubuntu-core-vm init edge
        From then on, you can spin it up with:
        sudo ubuntu-core-vm
        Using Ubuntu Classic
        You don't have to use Ubuntu Core, you can use also a "Target Device" with Ubuntu Classic. You just need to install an SSH server on the device.
        sudo apt install ssh
        For IoT use you will want to make other changes (e.g. uninstalling the desktop), but that is outside the scope of the current tutorial.

Graphical Snaps for Ubuntu IoT Devices: Using Xwayland

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
