### ISSUE TITLE
I'd like to see a good getting started with rust programming tutorial series

### ISSUE THREAD

**Issue by arunkumar413** [canonical-web-and-design/tutorials.ubuntu.com#827]
Rust is a bit difficult to master. So I'd like to have good introduction and getting started tutorial series for rust programming.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
