### ISSUE TITLE
[Create a bootable USB stick on Windows] Partition Scheme

### ISSUE THREAD

**Issue by ejolney** [canonical-web-and-design/tutorials.ubuntu.com#830]
Great and easy to follow.
At one time, my rig would have been considered modern hardware, but I'm sure it's not now. I think you should draw a line between "modern" hardware and "older" hardware for step 4.

Thank you!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
