### ISSUE TITLE
Fix a sentence in tutorials/packaging/snap-a-nodejs-app.md

### ISSUE THREAD

**Issue by Esgorhannoth** [canonical-web-and-design/tutorials.ubuntu.com#831]
In file [tutorials/packaging/snap-a-nodejs-app.md](https://github.com/canonical-websites/tutorials.ubuntu.com/blob/0502e61303819aef7b7ef257fdb918f084a43c00/tutorials/packaging/snap-a-nodejs-app.md)
Under ```Getting familiar with the project``` header, the second sentence says: "The backend code issue a REST request through through a web API,<...>".

Should be changed to "The backend code issues a REST request through a web API"
```issue -> issues```
```through through -> through```

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
