### ISSUE TITLE
Creating a new "pool" problem with how you show/do it.

### ISSUE THREAD

**Issue by Just-another-pleb** [canonical-web-and-design/tutorials.ubuntu.com#835]
In your example you say this:

**sudo zpool create new-pool /dev/sdb /dev/sdc**

I am trying to get zfs working on ubuntu 18.04 and enter that.
Taking into account I get the device names/paths right:   It won't work.

I have to include a -f option to FORCE zfs to use the specified USB sticks.

As is: zfs complains that the drive is either busy or it has a "non supported file system" on it.
I can't get the exact words, but digging around I was told the the -f option is needed.

It would be nice if that was declared in your instructions.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
