### ISSUE TITLE
[Create a bootable USB stick on Windows] tutorial is out of date

### ISSUE THREAD

**Issue by rfquickjr** [canonical-web-and-design/tutorials.ubuntu.com#839]
Surely someone has already noted this, but: The latest Rufus (3.3) doesn't have the same screens and options as shown.

**Comment by bjkowalski** [comment]
An updated tutorial to reflect the need for a larger USB stick when creating Ubuntu 18.04.1 boot-able drives, updated screenshots for the new Ubuntu WEB site, and reflect the use of updated Rufus 3 was merged on 10/1/2018.

**Comment by fitojb** [comment]
Yep, can confirm the issue is [fixed.](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#2)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
