### ISSUE TITLE
Ubuntu Security Team tutorials

### ISSUE THREAD

**Issue by hwpplayer1** [canonical-web-and-design/tutorials.ubuntu.com#84]
Ubuntu Security Team tutorials would be fine. Hardening , kernel configuration , unit tests etc.

**Comment by aggsol** [comment]
I would also add server security best practices for SSH, Apache and databases.

**Comment by grahambancroft** [comment]
Hi hwpplayer1 and aggsol,

Many thanks for your suggestions, I’ll pass them on to our tutorials team.

All the best,

Graham

**Comment by good2gitgone** [comment]
Would be nice if there were decent people on here, everyone is hungry to start injecting me with scripts, which makes it very difficult to learn how to do anything.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
