### ISSUE TITLE
https://tutorials.ubuntu.com/tutorial/tutorial-upgrading-ubuntu-desktop is confusing

### ISSUE THREAD

**Issue by keithbriggs** [canonical-web-and-design/tutorials.ubuntu.com#840]
The first step says "search for Update Manager", but the screen image shows "updater" being searched for.

What comes up is called something different again, "Software Updater".  Is this the same thing?   If so, how are we supposed to know?   If there's only one thing, then use only one name.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
