### ISSUE TITLE
Create a bootable USB stick on Windows - new option on Boot selection 

### ISSUE THREAD

**Issue by rc6484** [canonical-web-and-design/tutorials.ubuntu.com#847]
On the instructions to create a bootable USB stick on Windows using Rufus, there appears to be a third selection (at least with Rufus 3.3+) as shown below.

![image](https://user-images.githubusercontent.com/8209737/46943550-df231180-d03d-11e8-8eb7-353e5047fd73.png)

Instead of:
Now choose the Boot selection. Choices will be Non bootable and FreeDOS. Since you are creating a bootable Ubuntu device select FreeDOS.

should not the tutorial state:
Now choose the Boot selection. Choices will be Non bootable, FreeDOS, **Disk or ISO Image**. Since you are creating a bootable Ubuntu device select Disk or ISO Image.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
