### ISSUE TITLE
Unsecure http(only) access to image checksums

### ISSUE THREAD

**Issue by avolution** [canonical-web-and-design/tutorials.ubuntu.com#848]
There is only  http server  described on:

https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#2

where you can download the checksums:

http://releases.ubuntu.com
http://releases.ubuntu.com/bionic/

So for example in a Man in the Middle Attack somebody can intercept your request and show you modified  checksums.

So if you do not provide a secure https connection to the checksums, the verification is useless at all.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
