### ISSUE TITLE
[Install Ubuntu desktop] Installation Ubuntu when the previous OS was Ubuntu too

### ISSUE THREAD

**Issue by saidbakr** [canonical-web-and-design/tutorials.ubuntu.com#849]
Since the upgrade from 16.04 to 18.04 is a matter of **luck**, I need to install a fresh 18.04 installation. I could not able to find any clear and direct official documentation covers this topic on the installation guide. I need to keep the contents of my `/home` partition and any compatible previous programmes from the previous version with deleting any unused files or obsolete libraries.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
