### ISSUE TITLE
[How to verify your Ubuntu download] How to verify from Windows 10

### ISSUE THREAD

**Issue by JesusBretos** [canonical-web-and-design/tutorials.ubuntu.com#856]
#Tutorials  Content

About the tutorial "How to verify your Ubuntu download".

The step 2 of the tutorial say that you can perform the task from Windows by means of downloading and installing the Linux's Terminal on this S.O.. Once that's done, you simply should execute gpg from de command line. But you're in Windows and you have downloaded the Ubuntu ISO image and the files SHA256SUMS and SHA256SUMS.gpg in a Windows directory. So how can you move this files to your home directory in Ubuntu to get them available for the gpg program? It is possible to get the files directly through a bash command? How? With which program? These questions must be explained in the tutorial in order to make it fully useful.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
