### ISSUE TITLE
Request: How to create a .deb package

### ISSUE THREAD

**Issue by aggsol** [canonical-web-and-design/tutorials.ubuntu.com#86]
Creating a proper .deb, dependencie resolution and deployment options. I should be more generic and not be a follow up to an existing tutorial.

**Comment by grahambancroft** [comment]
Hi aggsol,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
