### ISSUE TITLE
[Install and Configure Apache] Update hosts file i necessary

### ISSUE THREAD

**Issue by robertbjarum** [canonical-web-and-design/tutorials.ubuntu.com#860]
I suggest adding a statement about updating the /etc/hosts file to point to the name chosen for ServerName if necessary.

**Comment by pmahnke** [comment]
Same as #936

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
