### ISSUE TITLE
[How to verify your Ubuntu download] <BAD Signature>

### ISSUE THREAD

**Issue by fera10** [canonical-web-and-design/tutorials.ubuntu.com#861]
<In step 5 the result from the command gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS was BAD signature, and there is not information on how to fix this>

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
