### ISSUE TITLE
[Install and Configure Apache] sample site not working

### ISSUE THREAD

**Issue by sku10** [canonical-web-and-design/tutorials.ubuntu.com#867]
the tutorial asks to set up sample site gci.example.com 
I don't think there is any default DNS set to point to my computer. 
So it would be useful to tell how to set fixed DNS to localhost to make example work.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
