### ISSUE TITLE
Tutorial Request - Configure PHP

### ISSUE THREAD

**Issue by jlHertel** [canonical-web-and-design/tutorials.ubuntu.com#87]
Hello,
It would be nice to have a tutorial explaining how to setup a PHP + nginx ubuntu server for production servers, with insights with the common mistakes.
Of course, a development machine with xdebug, composer and the like are welcome too.

**Comment by grahambancroft** [comment]
Hi jlHertel,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
