### ISSUE TITLE
[Install Ubuntu on Windows 10] <please add a title>

### ISSUE THREAD

**Issue by jurban1997** [canonical-web-and-design/tutorials.ubuntu.com#879]
There should be a link to support in adding a GUI to this basic install on Windows 10.  Or, call out that it is not supported.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
