### ISSUE TITLE
How to design&make HA and Fail-safe configurations

### ISSUE THREAD

**Issue by M0Rph3U56031769** [canonical-web-and-design/tutorials.ubuntu.com#88]

**Comment by grahambancroft** [comment]
Hi M0Rph3U56031769,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
