### ISSUE TITLE
Tutorial on create USB on Windows - Rufus compatibility

### ISSUE THREAD

**Issue by maciejs** [canonical-web-and-design/tutorials.ubuntu.com#880]
Tutorial says:

You will need:
Microsoft Windows XP or later
Rufus, a free and open source USB stick writing tool

Note that latest version of Rufus no longer supports Windows XP and Windows Vista 
Last version compatible with Windows XP and Windows Vista is 2.18, which still can be used
https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows

**Comment by byroniac** [comment]
Not a bug per se, but Rufus has changed its web address (though the old one still works by forwarding to the new one). https://rufus.ie/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
