### ISSUE TITLE
[Basic snap usage] <please add a title>

### ISSUE THREAD

**Issue by yusef-nexmo** [canonical-web-and-design/tutorials.ubuntu.com#883]
Would it not make sense to start with an overview describing what snaps are in the first place, instead of diving into the snap command syntax?
For example, why use snaps rather than Deb packages and apt?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
