### ISSUE TITLE
[Make a secure Ubuntu kiosk] Starts with black screen unable to configure

### ISSUE THREAD

**Issue by globeone** [canonical-web-and-design/tutorials.ubuntu.com#885]
Following the instructions I got to the point of the first ssh but the screen is black and I can't configure my SSO_USER inside the Virutal Machine.

I see grub starting and I see linux loading so I know the VM can display.

:~$ sudo ubuntu-core-vm
[sudo] wachtwoord voor kat: 
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
gl_version 31 - compat profile
*********************************************************
* You can now SSH into the VM with:
*     ssh -p 5555 $SSO_USER@localhost
* (but only after you configure it)
*********************************************************

![ubuntu-core-vm_grub](https://user-images.githubusercontent.com/10052587/48666251-5543e980-eabe-11e8-83f3-312748090aeb.png)

![ubuntu-core-vm_blackscreen](https://user-images.githubusercontent.com/10052587/48666230-08f8a980-eabe-11e8-809e-95f9a462a8b4.png)

**Comment by globeone** [comment]
Workaround is to add **nomodeset** to the grub setparams

At the grub screen press `e`
Then move the cursor to the end of the 5th line to now read
   

> linux (loop)/kernel.img $cmdline **nomodeset**

then press **Ctrl-x** or **F10** to boot

![ubuntu-core_needs_nomodeset](https://user-images.githubusercontent.com/10052587/48666320-8d97f780-eabf-11e8-8385-b5c4e59c8855.png)
![ubuntu-core-vm_pleaseentertoconfig](https://user-images.githubusercontent.com/10052587/48666321-8ffa5180-eabf-11e8-93bb-453c559edd0e.png)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
