### ISSUE TITLE
[Make a secure Ubuntu Kiosk] ssh instructions don't work

### ISSUE THREAD

**Issue by globeone** [canonical-web-and-design/tutorials.ubuntu.com#886]
The instructions to ssh into the machine don't work and just show the instructions on how to properly ssh.

> *********************************************************
> * You can now SSH into the VM with:
> *     ssh -p 5555 $SSO_USER@localhost
> * (but only after you configure it)
> *********************************************************

> :~$ ssh -p 5555 $SSO_USER@localhost
> usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
>            [-D [bind_address:]port] [-E log_file] [-e escape_char]
>            [-F configfile] [-I pkcs11] [-i identity_file]
>            [-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
>            [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
>            [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
>            [user@]hostname [command]

The answer is really simple the username and host string need to be single quoted like this:

> ssh -p 5555 '$SSO_USER@localhost'

Yet unfortunately one still can't connect into the machine. Even after configured.

**Comment by globeone** [comment]
![ubuntu-core-vm_sshfail](https://user-images.githubusercontent.com/10052587/48666460-cd141300-eac2-11e8-8b37-1531d213253c.png)

**Comment by globeone** [comment]
Maybe some instructions on how to configure the machine, and certainly some screenshots instead of only text would be much more helpful.

![ubuntu-core-vm_configed](https://user-images.githubusercontent.com/10052587/48666490-59263a80-eac3-11e8-9f2c-89f024a9e9de.png)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
