### ISSUE TITLE
Ubuntu 18.04 Server installation Manual Network IPv4 won't working

### ISSUE THREAD

**Issue by JahidurRahman** [canonical-web-and-design/tutorials.ubuntu.com#889]
![img_20181119_211023](https://user-images.githubusercontent.com/45174962/48716505-b6e09100-ec41-11e8-962a-2b8640e4e13f.jpg)

**Comment by JahidurRahman** [comment]
I think its a bug. the format caption 1st: subnet: 2nd: address, then Gaetway. But it should be address, subnet, gateway.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
