### ISSUE TITLE
ZFS tutorials

### ISSUE THREAD

**Issue by daveynet** [canonical-web-and-design/tutorials.ubuntu.com#89]
Hi, it would be great to see more self-paced training on ZFS.

Thanks.

**Comment by grahambancroft** [comment]
Hi daveynet,

Many thanks for taking the time to request this, we’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
