### ISSUE TITLE
[Tutorial Suggestion]  Basic Tor setup with minimal hassle. 

### ISSUE THREAD

**Issue by coverme76** [canonical-web-and-design/tutorials.ubuntu.com#892]

**Comment by pmahnke** [comment]
@coverme76 	thanks for the suggestion, I will see if I can get someone to write it... unless you want to give it a go?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
