### ISSUE TITLE
[Make a secure Ubuntu kiosk] Not working from 18.04LTS

### ISSUE THREAD

**Issue by zakkojo** [canonical-web-and-design/tutorials.ubuntu.com#896]
Installed Ubuntu Server 18.04LTS 
apt upgrade
snap install mir-kiosk  -> OK(black screen and arrow appears)
snap install --beta chromium-mir-kiosk -> KO (nothing happens)

I tried to connect chromium to mir using wayland: 
snap connect chromium-mir-kiosk:wayland mir-kiosk:wayland
snap restart chromium-mir-kiosk

but nothing...

Do you have any idea?

**Comment by zakkojo** [comment]
Ah I previously tried the same with ubuntu 14.04LTS and I had the same result....
maybe I'm missing something?

Thanks

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
