### ISSUE TITLE
[Install Ubuntu on a Chromebook] Chromebook requests password after typing in command

### ISSUE THREAD

**Issue by Gryphon827** [canonical-web-and-design/tutorials.ubuntu.com#901]
When trying to get Ubuntu on my chromebook, the following pops up;
`https://i.imgur.com/4uvO8EJ.png`
The password it's requesting is not the root password you can put in when enabling developer mode, nor is it the password to your google account; I tried both, and neither worked.  What should I be putting here?

**Comment by pmahnke** [comment]
@asaunders I think you wrote this tutorial, any thoughts?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
