### ISSUE TITLE
USB install instructions.

### ISSUE THREAD

**Issue by danshumaker** [canonical-web-and-design/tutorials.ubuntu.com#902]
https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop?_ga=2.72494867.1823692106.1545594528-1358858119.1545594528#3

On Step 4 "Boot from USB flash drive", there is the line "Simply insert the USB flash drive ", which is wrong, misleading, and a pet peeve of mine.  First off nothing is simple with computers (that's my pet peeve - anytime ANYONE says it's simple - its usually not. Second, there are no previous steps on USB setup.  The way the instructions read, the person (lets say my grandma) could insert a blank USB drive into their usb port and expect the rest of the steps to work.  The assumption on the documentation teams' part is that the USB drive has been setup properly with the latest ISO of the installer disk.  However, the docs don't say that and they should, in my opinion.

Is it enough to just have the iso on the usb flash drive? Does the drive need to be FAT32 or Extended Journaled, or NTFS, or which format?  

At the very least there should be a link to instructions on how to burn the DVD with the ISO installed in the boot sector and/or setup the USB before you proceed to step 5.

**Comment by pmahnke** [comment]
@danshumaker sorry if there is a bit of marketing speak in there.  When we update this, we will try to clean up this language.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
