### ISSUE TITLE
[Basic snap usage] I've read the tutorial but I don't know how to run the package I've installed

### ISSUE THREAD

**Issue by philip-bl** [canonical-web-and-design/tutorials.ubuntu.com#903]
I've read this tutorial in order to learn how to run https://snapcraft.io/mathpix-snipping-tool package. But the tutorial didn't explain this to me.

**Comment by philip-bl** [comment]
It turns out i needed to add something to `$PATH`.

**Comment by pmahnke** [comment]
@degville do we need update the tutorial?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
