### ISSUE TITLE
[Install and Configure Apache] gci.example.com not working

### ISSUE THREAD

**Issue by fabelizer** [canonical-web-and-design/tutorials.ubuntu.com#906]
Using Firefox 64 on Xubuntu 18.04 and no joy!
Last step says type "host name" in a browser, which I think is really the URL "gci.example.com", but it does not work, Firefox reports it is having trouble finding that site.
Navigate to the example file, it works.
Apache2 server example works.
I also tried from other machine, no worky. (either site).
Any suggestions? I saw someone thought a host file needed a line added??
Cheers, Dave

**Comment by pmahnke** [comment]
Same a #936

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
