### ISSUE TITLE
[Run Linux containers on Windows] <please add a title>

### ISSUE THREAD

**Issue by vishalakshminamuduri** [canonical-web-and-design/tutorials.ubuntu.com#908]
when i try to run the command docker images it shows the error message Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? from past 2 months i am facing the same error .. somebody pls help me.

I am running ubuntu as windows subsystem and loaded docker in ubuntu *18.04

**Comment by pmahnke** [comment]
Any tips @vorlonofportland?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
