### ISSUE TITLE
Conjure-up Instructions require installing Juju 

### ISSUE THREAD

**Issue by rmaultz** [canonical-web-and-design/tutorials.ubuntu.com#909]
Conjure-up Instructions require installing Juju 

Step 1 sudo snap install juju --classic 
After Installing juju -- classic  and running conjure-up again  the installer stalls  not allowing to Continue forward in installation Currently  I am Installing to a lightsail (Amazon) using Amazon AMI  of 18.04 Ubuntu

My Specs 

1 VCPU
2gb Memory  and 
60gb Storage  

![screenshot](https://user-images.githubusercontent.com/3631113/50709982-d9c6d900-1026-11e9-9f50-bfb79d7942ae.JPG)

**Comment by rmaultz** [comment]
URL: https://tutorials.ubuntu.com/tutorial/install-openstack-with-conjure-up#2

**Comment by pmahnke** [comment]
@clagom 	can you review this? or ask @cassiocassio

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
