### ISSUE TITLE
add some audio

### ISSUE THREAD

**Issue by springAppl** [canonical-web-and-design/tutorials.ubuntu.com#91]
audio is more helpful!

**Comment by grahambancroft** [comment]
Hi springAppl,

Many thanks for your suggestion, I’ll pass it on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
