### ISSUE TITLE
[Install Ubuntu desktop] No detailed explanations

### ISSUE THREAD

**Issue by q26g** [canonical-web-and-design/tutorials.ubuntu.com#911]
The tutorial guide is quite instructive though it's not exhaustive. Some details such as what kind of option(s)  one needs to choose in order to make sure the parallel OS installation and the safety of the existing OS/data on the disks.

**Comment by pmahnke** [comment]
@q26g 	I will take that as a request for adding tutorials on dual booting windows/mac and ubuntu?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
