### ISSUE TITLE
How to install Windows app on Ubuntu

### ISSUE THREAD

**Issue by ujjwaltwitx** [canonical-web-and-design/tutorials.ubuntu.com#912]

**Comment by pmahnke** [comment]
@ujjwaltwitx 	I assume you are asking for a tutorial on this, using Wine?

**Comment by Linconio** [comment]
https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/912#issue-399917777

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
