### ISSUE TITLE
[Get started with Kubeflow] How to access JuputerHub?

### ISSUE THREAD

**Issue by vochicong** [canonical-web-and-design/tutorials.ubuntu.com#913]
I think that JupyterHub is included in KubeFlow, but don't see in the tutorial how to access it.

**Comment by pmahnke** [comment]
@carmine any thoughts?

**Comment by carmine** [comment]
JupyterHub is included in Kubeflow.

The tutorial needs to be updated .. is on my list.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
