### ISSUE TITLE
[How to verify your Ubuntu download] Clarification suggestion

### ISSUE THREAD

**Issue by DU-ds** [canonical-web-and-design/tutorials.ubuntu.com#914]
Throughout the tutorial I had to add .txt to the SHA256SUMS file. The issue with the tutorial is that when running this command:

`sha256sum -c SHA256SUMS 2>&1 | grep OK`

the explanation says:
> If you get no results (or any result other than that shown above) then the ISO file does not match the checksum. This could be because the ISO has been altered, or it downloaded incorrectly - either way you should download a fresh ISO from a known good source.

when in reality adding the file extension may solve this issue. So, instead running:

`sha256sum -c SHA256SUMS.txt 2>&1 | grep OK`

may work, despite the explanation that this means there is an issue with the ISO.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
