### ISSUE TITLE
[Install and Configure Samba] Missing guest access

### ISSUE THREAD

**Issue by stokito** [canonical-web-and-design/tutorials.ubuntu.com#917]
Please add an example of Guest access to the share i.e. ` guest ok = yes` param:
```
[Guest Share]
        comment = Guest access share
        path = /path/to/dir/to/share
        browseable = yes
        read only = yes
        guest ok = yes
```

**Comment by pmahnke** [comment]
@stokito 	are you able to provide a PR of a recommended change?

**Comment by stokito** [comment]
sorry, I don't have a time for that

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
