### ISSUE TITLE
[Create a bootable USB stick on macOS]  “unable to find a medium containing a live file system”

### ISSUE THREAD

**Issue by brooke-heaton** [canonical-web-and-design/tutorials.ubuntu.com#918]
This didn't work in my case. I keep getting an error of:

 “unable to find a medium containing a live file system”

**Comment by pmahnke** [comment]
@brooke-heaton 	which version of macOS are you using?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
