### ISSUE TITLE
[How to burn a DVD on Windows] <please add a title>

### ISSUE THREAD

**Issue by westavery** [canonical-web-and-design/tutorials.ubuntu.com#920]
Right now the iso file I burned to the DVD is not being boot from when I restart the computer, ESC to boot manually, select the correct drive, the desktop's normal OS still boots...

**Comment by pmahnke** [comment]
@westavery 	when you burned the dvd, did you make sure it was make bootable?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
