### ISSUE TITLE
[Install Ubuntu Server] <please add a title>

### ISSUE THREAD

**Issue by cairotx** [canonical-web-and-design/tutorials.ubuntu.com#932]
the step where it tries to configure any network connections via DHCP, it won't figure it 100% and get stuck @ 50% and won't let move forward.

**Comment by pmahnke** [comment]
@powersj could you comment on this?  anything for us to do on the tutorial?

**Comment by powersj** [comment]
@cairotx Thanks for taking the time to try out the tutorial. Sorry you are running into an issue.

To help determine the cause, can you provide a little more detail about how you are using the Ubuntu Server install:

- Are you trying this on a spare computer you have or doing this in a virtual machine? 
- Are you sure the system is connected and expect it to be able to connect to the internet?
- Do you have DHCP on your network?

If you are familiar with IRC, you can always use freenode.net and join the #ubuntu-server channel. Another option is to send your question to the [ubuntu-server mailing list](https://lists.ubuntu.com/mailman/listinfo/ubuntu-server).

Thanks again for trying the tutorial.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
