### ISSUE TITLE
No workable instruction on how to download SHA256SUMS from http://releases.ubuntu.com/bionic/? available.

### ISSUE THREAD

**Issue by LuigiWriter** [canonical-web-and-design/tutorials.ubuntu.com#933]
https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#3

This Article assumes a user new to Ubuntu knows how to 
"fetch these files from the http://releases.ubuntu.com page for the relevant release."

The article needs an example of the command line needed to download SHA256SUMS from http://releases.ubuntu.com/bionic/

This seems the most simple question, however all I get at Ask.Ubuntu, stack exchange and gethub is theory, others problems, and posts of complications.

The root of the problem is
http://releases.ubuntu.com/bionic/ 
does not offer a copy or download option for the files. 

Other click on the file and all I get in Firefox is link choices, no download or copy to options. 
I have been warned in one of the above sources that copying and pasting contents into a file I create will fowl up the process, and others seem to confirm this.

So whether using
gpg --keyid-format long --keyserver-options auto-key-retrieve --verify SHA256SUMS.gpg
or
gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS
The result is always the same 

gpg: can't open `SHA256SUMS.gpg'
gpg: verify signatures failed: file open error

if the gpg files are not properly downloaded.

And how to do that is the vital step for which I presently can find no workable instructions to insert into 
https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#3

This is a Critical Issue in my view as the Install program failed and automatically submitted a bug report.
https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1816283
 I cannot add to that bug report or close it with a problem corrected comment if I cannot get past this bug in order to verify if it is the ISO download is corrupted or it is a good ISO on a faulty DVD that is the problem on that bug report.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
