### ISSUE TITLE
after snap revert, snap list command shows wrong Tracking.

### ISSUE THREAD

**Issue by Keyhad** [canonical-web-and-design/tutorials.ubuntu.com#934]
I did went through snap tutorial, in revert section I noticed snap list command shows wrong tracking value.
![image](https://user-images.githubusercontent.com/12716998/52944791-90311400-3370-11e9-9aa1-24e3affde3f0.png)

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Comment by pmahnke** [comment]
@Lukewh could you look at this, might be a snapd bug?

**Comment by Lukewh** [comment]
@Keyhad which tutorial did you use?

**Comment by Keyhad** [comment]
[https://tutorials.ubuntu.com/tutorial/basic-snap-usage#0](url)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
