### ISSUE TITLE
[Install and Configure Apache] Config virtual host in hosts file is missing

### ISSUE THREAD

**Issue by IvanCookie** [canonical-web-and-design/tutorials.ubuntu.com#936]
<describe the issue>

**Comment by IvanCookie** [comment]
At the end of tutorial I run my virtual host by typing it in web browser but it doesn't work, and it was because the host was not setted within etc/hosts file, and this step is not indicated in this tutorial.

**Comment by pmahnke** [comment]
@nottrobin can you comment on this?

**Comment by pmahnke** [comment]
@nottrobin 	also seen in #906 and #860

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
