### ISSUE TITLE
[Make a secure Ubuntu kiosk] Browser does not open because of virtual machine VGA

### ISSUE THREAD

**Issue by FurretUber** [canonical-web-and-design/tutorials.ubuntu.com#938]
On a Xubuntu 18.04 host, this tutorial fails because the Ubuntu Core virtual machine guest never loads the `chromium-mir-kiosk`.

This happens, apparently, because the QXL VGA does not have some needed feature (I just started with Ubuntu Core, need to learn how to get more meaningful logs). The command to start the Ubuntu Core guest originally was:
```
kvm -smp 2 -m 1500 -netdev user,id=mynet0,hostfwd=tcp::8022-:22,hostfwd=tcp::8090-:80 -device virtio-net-pci,netdev=mynet0 -vga qxl -drive file=ubuntu-core-18-amd64.img,format=raw
```
As the [official guide](https://www.ubuntu.com/download/iot/kvm) suggests. Fortunately, I have set up [Intel GVT-g](https://github.com/intel/gvt-linux/wiki/Dma_Buf_User_Guide) on the host, so I tested passing a virtual Intel HD Graphics 520 to the Ubuntu Core guest, which then allowed me to complete the tutorial. The command that was successful was:
```
kvm -smp 2 -m 1024 -netdev user,id=mynet0,hostfwd=tcp::8022-:22,hostfwd=tcp::8090-:80 -device virtio-net-pci,netdev=mynet0 -vga none -drive file=ubuntu-core-18-amd64.img,format=raw -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/7c6999bc-d8a6-11e8-951d-a75a7e70a07f,rombar=0,display=on,addr=0x3,id=iHD520 -display gtk,gl=on
```
It should be stated on the tutorial that it won't work with virtual machines VGAs or `mir-kiosk`, `chromium-mir-kiosk` and `mir-kiosk-apps` should be changed to work with Virtual Machine VGAs. As they are tutorial programs, many users will have the first contact with graphical user interfaces on Ubuntu Core with the programs from this tutorial, and failing here will make users confused. At least I was until I had the idea to pass a GPU to the Ubuntu Core guest.

**Comment by pmahnke** [comment]
@caldav where can I take this for help?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
