### ISSUE TITLE
[Build a nodejs service snap] The default "base: core18" created by snapcraft causes builds to fail

### ISSUE THREAD

**Issue by Seshpenguin** [canonical-web-and-design/tutorials.ubuntu.com#939]
Removing the base entry allows the snapcraft prime command to succeed as expected. Having it there creates multiple different issues depending on the NodeJS project preventing a successful build.

**Comment by pmahnke** [comment]
@degville 	can you take a look?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
