### ISSUE TITLE
Troubleshooting tutorials

### ISSUE THREAD

**Issue by ConnieNew** [canonical-web-and-design/tutorials.ubuntu.com#94]
I think tutorials for unique use cases are valuable, but have a limited audience. It would far more useful to have tutorials that deal with  1) Problems that new users will get that immediately affect their ability to be productive (e.g. step by step troubleshooting wifi connectivity issues) 2) Aspects that will make working much easier...(e.g. setting up Samba and file sharing within their network) 3) Things that users from other environments might need to  do within Linux which they were able to do easily before migrating (e.g video editing) 4) Later on things that Ubuntu will do better than other systems e.g working in converged environment.  Askubuntu  has been a godsend purely because the content is driven by those in need of help.  The content of these tutorials should be also similarly motivated.

**Comment by grahambancroft** [comment]
Hi ConnieNew,

Many thanks for your suggestions, I’ll pass them on to our tutorials team.

All the best,

Graham

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
