### ISSUE TITLE
MAAS pod tutorial out of date

### ISSUE THREAD

**Issue by mlda065** [canonical-web-and-design/tutorials.ubuntu.com#941]
I was just trying to do the tutorial titled:

> Create KVM pods with MAAS

File `./tutorials/server/maas-kvm-pod/maas-kvm-pod.md`, published [here](https://tutorials.ubuntu.com/tutorial/create-kvm-pods-with-maas#2).

It says:

> A testbed environment would require a server running the latest Ubuntu Server LTS 

Which means Ubuntu 18.04. That's what I'm using.

I got to the networking step.

> Edit `/etc/network/interfaces` to look like this:

But the problem is that on the specified version of Ubuntu (18), that file is no longer used. It's contents is

```
# ifupdown has been replaced by netplan(5) on this system.  See
# /etc/netplan for current configuration.
# To re-enable ifupdown on this system, you can run:
#    sudo apt install ifupdown
```

It's not immediately clear how to add a bridge to `/etc/netplan`. (The comments in that file say that it is generated from some other, unspecified source.)

The tutorial should be updated to reflect the new `netplan` way of doing things.

**Comment by pmahnke** [comment]
@cassiocassio can you look at this?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
