### ISSUE TITLE
Ubuntu 18.04 LTS desktop specific download

### ISSUE THREAD

**Issue by 10ag** [canonical-web-and-design/tutorials.ubuntu.com#946]
I would like to create a bootable SD drive with the Ubuntu 18.04 LTS desktop that would function on a HP Pavilion X360 laptop.
I would like it so every detail I need to know is provided in the answers. Thanks in advance.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
