### ISSUE TITLE
snap try with multipass

### ISSUE THREAD

**Issue by gandroz** [canonical-web-and-design/tutorials.ubuntu.com#949]
according to this [issue](https://forum.snapcraft.io/t/how-to-do-snap-try-when-building-using-multipass/9077), the tutorials about snap are not up to date. The linked issue offers a workaround to let us use `snap try` on un unpacked snap

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
