### ISSUE TITLE
Programming Course for Ubuntu Touch

### ISSUE THREAD

**Issue by mimecar** [canonical-web-and-design/tutorials.ubuntu.com#95]
Good evening.

I'm writing an Ubuntu Touch programming course from scratch. The course has several issues published in Spanish but now I am translating the chapters into English.

Can it interest you?
https://www.gitbook.com/book/mimecar/curso-de-programacion-de-ubuntu-phone-touch/details

**Comment by WillMoggridge** [comment]
Hi mimecar!
This sounds interesting, indeed. I will pass it along to the tutorials team.

In the near future, we want to create and document a process to allow community members to propose tutorials. We want to simplify this process and encourage people to contribute.

Thanks!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
