### ISSUE TITLE
[Install and Configure Samba] Last Step did not work

### ISSUE THREAD

**Issue by AndrewRRMoser** [canonical-web-and-design/tutorials.ubuntu.com#950]
When I tried to enter "smb://ip-address/smbshare" into the Connect to Server entry, it gave me an error saying "Oops! Something went wrong. Unhandled error message: Failed to mount Windows share: Invalid argument".

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
