### ISSUE TITLE
Fails to work on Mint

### ISSUE THREAD

**Issue by charlie-ogier** [canonical-web-and-design/tutorials.ubuntu.com#953]
The tutorial says it will work with Mint but it clearly states that it wont!
"Native builds aren't supported on Linux Mint. You can however use 'snapcraft cleanbuild' with a container."

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
