### ISSUE TITLE
[Configure SSH to use two-factor authentication]  AuthenticationMethods missing

### ISSUE THREAD

**Issue by Monschichi** [canonical-web-and-design/tutorials.ubuntu.com#955]
sshd_config option `AuthenticationMethods publickey,password publickey,keyboard-interactive` is missing.
Compare to Step 3 on https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
