### ISSUE TITLE
How to verify your Ubuntu download - gpg issue / question

### ISSUE THREAD

**Issue by wisdomlight** [canonical-web-and-design/tutorials.ubuntu.com#957]
I am trying to verify an ubuntu download

follwing the tutorial 
this [page](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#1) suggests the following check:

gpg --list-keys
here's the terminal:

```
sherab@sherab-pc:~$ gpg --list-keys
/home/sherab/.gnupg/pubring.kbx
-------------------------------
pub   rsa4096 2012-05-11 [SC]
      843938DF228D22F7B3742BC0D94AA3F0EFE21092
uid           [ unknown] Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

pub   dsa1024 2004-12-30 [SC]
      C5986B4F1257FFA86632CBA746181433FBB75451
uid           [ unknown] Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>
```

I downloaded the sha256sums.gpg and the sha256sums.txt to the same folder i downloaded the ubuntu.iso [/Downloads]

This [page](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu#3) says that : by entering this command gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS i shall know if i need to download or not the public keys.

the same page gives an error - which is useful because it gives the numbers of the keys we need to obtain from the ubuntu server.

but I get the following return from the terminal and I do not know what am I to do with it:
```
sherab@sherab-pc:~/Downloads$ gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS
gpg: can't open signed data 'SHA256SUMS'
gpg: can't hash datafile: No such file or directory
```

so something is not working.

**Comment by wisdomlight** [comment]
OK i resolved it
the problem was that the line of code
 `gpg --keyid-format long --verify SHA256SUMS.gpg SHA256SUMS`
actually misses .txt at the end of the SHA256SUMS

if you guys in ubuntu tutorials can add the .txt it will save a lot of hassle for beginners like me.
even though i did enjoy the process of finding the solution.

**Comment by evilnick** [comment]
The issue here is that the official repos do NOT have a '.txt' suffix, but many of the mirrors do. But it is worth adding a note to that effect, thanks

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
