### ISSUE TITLE
HTML error in Tutorial

### ISSUE THREAD

**Issue by 7slcode7** [canonical-web-and-design/tutorials.ubuntu.com#960]
Below link guides to configure Apache web server. It has a sample HTML document. There p tag <p> not closed properly.

https://tutorials.ubuntu.com/tutorial/install-and-configure-apache#2

It should be as below.
```
<html>
<head>
  <title> Ubuntu rocks! </title>
</head>
<body>
  <p> I'm running this website on an Ubuntu Server server! ### **</p>**
</body>
</html>

```

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
