### ISSUE TITLE
[Basic snap usage] FAQ needed

### ISSUE THREAD

**Issue by schorschie** [canonical-web-and-design/tutorials.ubuntu.com#962]
I installed a snap and it does not launch because `"cannot create user data directory: /home/.../snap/code/6"`.
This seems to be some basic issue, which I would like to be able to solve by myself.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
