### ISSUE TITLE
[Install a local Kubernetes with microk8s] <please add a title>

### ISSUE THREAD

**Issue by ricoris** [canonical-web-and-design/tutorials.ubuntu.com#964]
As a first time user, I want to log in in the web serviceses, exposed by K8, so that I can monitor the K8 services

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
