### ISSUE TITLE
What's the meaning of the badge like icon on the upper-right corner of an article?

### ISSUE THREAD

**Issue by Cypresslin** [canonical-web-and-design/tutorials.ubuntu.com#965]
The badge like icon on an article is a bit confusing, not sure what that means.
Perhaps we can have some explanations when you hover the cursor over it?
![screenshot](https://i.imgur.com/QaPEfqU.png)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
