### ISSUE TITLE
[Create a bootable USB stick on macOS] Mac OSX < 10.9

### ISSUE THREAD

**Issue by geppyz** [canonical-web-and-design/tutorials.ubuntu.com#967]
The tutorial mentions Etcher as an utility to create a bootable usb-drive.
Etcher is an fantastic tool, however it is based on the electron-framework, which implies it will only work on Mac's with Mac OSX 10.9 or higher. 

It would be nice to see an alternative for older Mac's.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
