### ISSUE TITLE
Ubuntu tutorial recommends Etcher which isn't GDPR compliant

### ISSUE THREAD

**Issue by kevcampb** [canonical-web-and-design/tutorials.ubuntu.com#968]
Etcher records PPI from the user's machine and sends it to 3rd party services with no way to opt-out. They have been aware of this issue for over 6 months.

https://github.com/balena-io/etcher/issues/2497

It's problematic if the ubuntu tutorial for installation on OSX is specifically recommending the use of Etcher and it has issues like this

https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#3

**Comment by caldav** [comment]
Thanks for raising this, useful to know. We'll look into alternatives.

**Comment by SilverWolf32** [comment]
Plain `dd` actually works quite well for me on OS X, although of course it doesn't have any safety checks to stop you from nuking the wrong drive.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
