### ISSUE TITLE
[Configure SSH to use two-factor authentication] Some steps missing

### ISSUE THREAD

**Issue by Hundhausen** [canonical-web-and-design/tutorials.ubuntu.com#969]
Before running the **google-authenticator** command, it should be mentioned to switch to the account you want to add the 2fa. Also there is no information on how to remove 2fa from an account. I guess just removing the **.google_authenticator** would do the job. When it's required for every account that uses ssh login, this should be mentioned.

A big problem was that a reboot was missing at the end. I locked myself out (got an IP Ban), because it won't accept my password. A server reboot helped but i guess only a specific service needs a restart, so it accepts the new method.

Also a question, that maybe should be answered in the tutorial. Can **su** also require 2fa? I mean when you only allow non root users for a ssh login and then switching to root, would make sense if to require a 2fa token as well at that point. Makes only sense when a password is required for that action.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
