### ISSUE TITLE
New steps for crouton install

### ISSUE THREAD

**Issue by ianganador** [canonical-web-and-design/tutorials.ubuntu.com#973]
The new chrome update requires a slight change to the crouton install instructions listed here https://tutorials.ubuntu.com/tutorial/install-ubuntu-on-chromebook#2. (See this link for more info, pertinent info is in screenshot https://tutorials.ubuntu.com/tutorial/install-ubuntu-on-chromebook#2)

![crouton install](https://user-images.githubusercontent.com/13442844/57484778-bf17a180-725e-11e9-8bdf-a196a24baa87.PNG)

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
