### ISSUE TITLE
[Create a bootable USB stick on Windows] Correct boot selection option?

### ISSUE THREAD

**Issue by irenkamalova** [canonical-web-and-design/tutorials.ubuntu.com#974]
At the step 4, there asked user to choose FreeDOS,
but later, after user choosed an iso-image, there no word about boot selection changed.
So, does user need to do the 4 step? It seems to be redudant.

**Comment by foobarbecue** [comment]
Duplicate of https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/847

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
