### ISSUE TITLE
[Create a bootable USB stick on Ubuntu] <please add a title>

### ISSUE THREAD

**Issue by BogusException** [canonical-web-and-design/tutorials.ubuntu.com#977]
You forgot one small detail: This only works for bootable LINUX distros... You cannot select an ISO file that is not. Your title is therefore annoyingly misleading.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
