### ISSUE TITLE
[Tutorial Content] 4GB stick on Windows, 2GB on Linux and Mac

### ISSUE THREAD

**Issue by RMuskovets** [canonical-web-and-design/tutorials.ubuntu.com#978]
The tutorial how to create bootable stick on Windows says **4GB pen drive or larger**, but on Mac and Linux pages it says **2GB drive or larger**.

Must it be 4GB+ or 2GB+?

![](https://i.imgur.com/ZdZRsb0g.jpg)

**Comment by T-E-N** [comment]
As of 18.04.3 LTS it must be 2.1 GB or more, cf. https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/1024

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
