### ISSUE TITLE
[Create a bootable USB stick on macOS] Etcher targets wrong partition.

### ISSUE THREAD

**Issue by jlbrewster** [canonical-web-and-design/tutorials.ubuntu.com#981]
Etcher will NOT target the physical volume (the one you made, named "ubuntu") only the physical "disk",(d1s2)overwriting any formatting that you did to the drive (on Mac, making the drive unreadable, unbootable).  Either something is wrong with the instructions, or IMO, Etcher...No workaround..
Apparently this WRONG tutorial has been around for 2 years, confusing people with "Etcher", when UNetBootIn has worked flawlessly for years!
FIX THE TUTORIAL! (It only works on Windows!)
USE UNetBootIn on Mac!

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
