### ISSUE TITLE
Mac USB TUTORIAL WRONG -- Use NetBootIn, NOT Etcher!

### ISSUE THREAD

**Issue by jlbrewster** [canonical-web-and-design/tutorials.ubuntu.com#982]
The tutorial is wrong.  If anyone reads this, UNetBootIn will work, as it has worked flawlessly for this task for many years.  Don't use Etcher! It will force you to make a Windows Flash drive!
https://unetbootin.github.io/

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
