### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#984]
issue link- https://github.com/canonical-web-and-design/tutorials.ubuntu.com/issues/984
status: needs more testing
priority: high

**comment to paste->**

Multiple issues ;do what you can, can be split into 4 others.

------------------------------------------------

For **Ubuntu**-

Accesibility of link-
On every page on https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows and others, increase the visibility of `Please file a bug`. Not everybody uses a magnifying glass that highlights important stuff, while browsing. 

**Doing it right**- Go to https://docs.microsoft.com/en-in/windows/apps/desktop/choose-your-platform#xamarin , under **Send feedback about:**, click on the **downwards arrow**  next to the "This page". That's one way.
On same page section, click on **This page** , this needs an approval by the user. That's the second way.

------------------------------------------
For **Kubuntu & Ubuntu**-

Installing on a laptop. Sony USM32GR flash drive(USB 2.0).

After following the tutorial, excluding step 4 (its useless) https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#9.

Go to https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop#3, do as it says, and reach an outcome..
>Select the second option, ‘Install Ubuntu', and press return to launch the desktop installer automatically. Alternatively, select the first option, ‘Try Ubuntu without installing',  to test Ubuntu 
Both lead to the same outcome. 

**outcome**- 
Pre-requisites - Kubuntu, only has no try kubuntu option in boot menu.

```pseudocode
Reach the wallpaper.
If Kubuntu, 
wait forever for anything to happen, the mouse pointer can be moved. But, the only thing there is a wallpaper.

Else If Ubuntu,
Reach the desktop.
if click on install Ubuntu, a window appears, select language `English`, click continue/install Ubuntu.
wait forever for anything to happen. Try clicking on anything, no response.
```

Post-outcome- Try different key combinations to get any response. Disconnect ethernet cable for an instant; then plug it in and wait for 5 minutes. Wait for 30 minutes. Wait for indefinite period of time. Then press power button to shutdown. Then press power button to start. Repeat 3 times for each ubuntu.

Key combinations-
1. To open a tty- `Ctrl + Alt + Fx`, no response, for x=1-8.
2. `Ctrl + Alt + Delete` . Restarts system, if long pressed.
3.  `Ctrl + Alt + Esc`
4.  Any other key that prints characters in a text editor; when pressed individually. All such keys in  combination.
5.  Every other key combination known to and used by humans.

-------------------------------------------

**For Ubuntu** -

In https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-desktop#3
>F12 is the most common key for bringing up your system's boot menu, but Escape, F2 and F10 are common

sometimes it is the ` Delete` key

-------------------------------------------

All  the best.

**Comment by snow8gaia** [comment]
Don't close.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
