### ISSUE TITLE
[Install and Configure Apache] ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by BrandonJW98** [canonical-web-and-design/tutorials.ubuntu.com#991]
Example site would not work until I specified an IP address with gci.example.com in the /etc/hosts file. Is there a way to do it with DNS?

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
