### ISSUE TITLE
[Run Linux containers on Windows] <old content>

### ISSUE THREAD

**Issue by peterennis** [canonical-web-and-design/tutorials.ubuntu.com#992]
<describe the issue>

Run Windows 10, 1809 for current release.
Doc is for 2017.
Needs an update or pointer to newer content

**Comment by rakibulhaq** [comment]
the current release does not require all these steps to run docker in windows and also the image the link points to is showing 404, it needs to be updated or at least point out that this content is outdated.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
