### ISSUE TITLE
Create a bootable USB Stick on Windows.

### ISSUE THREAD

**Issue by tmsd2001** [canonical-web-and-design/tutorials.ubuntu.com#993]
It can happen that some files are detected as virus, in my case the file "/ casper / vmlinuz".
And don't move to the USB Stick.
A hint would be helpful.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
