### ISSUE TITLE
for kubuntu team

### ISSUE THREAD

**Issue by ghost** [canonical-web-and-design/tutorials.ubuntu.com#994]
For **Kubuntu** -

### priority: ?

issue1:
The latest **kubuntu-19.04-desktop-amd64.iso** does not match the checksum in SHA256SUMS or SHA1SUMS.
### status: for 16 Jun ; not fixed

---

issue2:
Its also broken in VirtualBox. The Virtual Machine does not boot in to the OS.
status: the file was last updated on **2019-04-16 19:25**, so not fixed.

works - The 18.10-desktop-amd64.iso

go to-> https://kubuntu.org/getkubuntu/ and select version.

----

posting here  since kubuntu's bug reporting system is not on GitHub or GitLab.
and

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
