### ISSUE TITLE
[Install Ubuntu Server] <please add a title>

### ISSUE THREAD

**Issue by rem1010** [canonical-web-and-design/tutorials.ubuntu.com#995]
Section on LAMP installs missing section on DHCP missing section on DNS missing.
What happened to the server of "server" am I missing?
Used to be server setup was for web, mail, database, etc. What happened?
Where is this info now?

**Comment by evilnick** [comment]
Ubuntu Server is the operating system. 

There are other tutorials here dealing with setup and configuration of specific applications, or you can also see the detailed [Server guide](https://help.ubuntu.com/lts/serverguide/index.html) documentation.
