### ISSUE TITLE
[Install and Configure Samba] <Does not work with r710 & Ubuntu 18.04>

### ISSUE THREAD

**Issue by trilogy1475** [canonical-web-and-design/tutorials.ubuntu.com#996]
<describe the issue>//<nameofserver> not accessible. Have been trying for several days to get samba to work. Will not work with an r710, Ubuntu 18.04, and windows 7.

**Comment by steverydz** [comment]
Thanks for submitting an issue for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials.
